import { LumiaAlertValues } from './activity.types';

export enum LumiaEventListTypes {
	REDEMPTION = 'redemption',
	FOLLOWER = 'follower',
	BITS = 'bits',
	EXTENSION = 'extension',
	POINTS = 'points',
	DONATION = 'donation',
	SUBSCRIBERS = 'subscribers',
	GIFTS = 'gifts',
	HOSTS = 'hosts',
	RAIDS = 'raids',
	HYPETRAIN = 'hypetrain',
	SPELLS = 'spells',
	RETWEETS = 'retweets',
	LIKES = 'likes',
	PURCHASES = 'purchases',
	SUPERSTICKERS = 'superstickers',
	SUPERCHATS = 'superchats',
	STARS = 'stars',
	FANS = 'fans',
	SHARES = 'shares',
	RAFFLE = 'raffles',
	OTHERS = 'others',
}

export const LumiaMapAlertTypeToEventListType = {
	[LumiaAlertValues.LUMIASTREAM_DONATION]: LumiaEventListTypes.DONATION,
	[LumiaAlertValues.DONORDRIVE_DONATION]: LumiaEventListTypes.DONATION,
	[LumiaAlertValues.EXTRALIFE_DONATION]: LumiaEventListTypes.DONATION,
	[LumiaAlertValues.LUMIASTREAM_RAFFLE_START]: LumiaEventListTypes.RAFFLE,
	[LumiaAlertValues.LUMIASTREAM_RAFFLE_STOP]: LumiaEventListTypes.RAFFLE,
	[LumiaAlertValues.LUMIASTREAM_RAFFLE_WINNER]: LumiaEventListTypes.RAFFLE,
	[LumiaAlertValues.FACEBOOK_FAN]: LumiaEventListTypes.FANS,
	[LumiaAlertValues.FACEBOOK_FOLLOWER]: LumiaEventListTypes.FOLLOWER,
	[LumiaAlertValues.FACEBOOK_GIFT_SUBSCRIPTION]: LumiaEventListTypes.GIFTS,
	[LumiaAlertValues.FACEBOOK_REACTION]: LumiaEventListTypes.LIKES,
	[LumiaAlertValues.FACEBOOK_SHARE]: LumiaEventListTypes.SHARES,
	[LumiaAlertValues.FACEBOOK_STAR]: LumiaEventListTypes.STARS,
	[LumiaAlertValues.FACEBOOK_SUPPORT]: LumiaEventListTypes.SUBSCRIBERS,
	[LumiaAlertValues.KOFI_COMMISSION]: LumiaEventListTypes.PURCHASES,
	[LumiaAlertValues.KOFI_DONATION]: LumiaEventListTypes.DONATION,
	[LumiaAlertValues.KOFI_SHOPORDER]: LumiaEventListTypes.PURCHASES,
	[LumiaAlertValues.KOFI_SUBSCRIPTION]: LumiaEventListTypes.SUBSCRIBERS,
	[LumiaAlertValues.FOURTHWALL_DONATION]: LumiaEventListTypes.DONATION,
	[LumiaAlertValues.FOURTHWALL_SHOPORDER]: LumiaEventListTypes.PURCHASES,
	[LumiaAlertValues.FOURTHWALL_SUBSCRIPTION]: LumiaEventListTypes.SUBSCRIBERS,
	[LumiaAlertValues.FOURTHWALL_GIFTPURCHASE]: LumiaEventListTypes.PURCHASES,
	[LumiaAlertValues.FOURTHWALL_GIVEAWAY_STARTED]: LumiaEventListTypes.GIFTS,
	[LumiaAlertValues.FOURTHWALL_GIVEAWAY_ENDED]: LumiaEventListTypes.GIFTS,
	[LumiaAlertValues.FOURTHWALL_THANKYOU_SENT]: LumiaEventListTypes.OTHERS,
	[LumiaAlertValues.PATREON_PLEDGE]: LumiaEventListTypes.SUBSCRIBERS,
	[LumiaAlertValues.STREAMELEMENTS_DONATION]: LumiaEventListTypes.DONATION,
	[LumiaAlertValues.STREAMLABS_CHARITY]: LumiaEventListTypes.DONATION,
	[LumiaAlertValues.STREAMLABS_DONATION]: LumiaEventListTypes.DONATION,
	[LumiaAlertValues.STREAMLABS_MERCH]: LumiaEventListTypes.PURCHASES,
	[LumiaAlertValues.STREAMLABS_PRIMEGIFT]: LumiaEventListTypes.GIFTS,
	[LumiaAlertValues.STREAMLABS_REDEMPTION]: LumiaEventListTypes.PURCHASES,
	[LumiaAlertValues.TIKTOK_FOLLOWER]: LumiaEventListTypes.FOLLOWER,
	[LumiaAlertValues.TIKTOK_GIFT]: LumiaEventListTypes.GIFTS,
	[LumiaAlertValues.TIKTOK_LIKE]: LumiaEventListTypes.LIKES,
	[LumiaAlertValues.TIKTOK_TOTAL_LIKES]: LumiaEventListTypes.LIKES,
	[LumiaAlertValues.TIKTOK_SHARE]: LumiaEventListTypes.SHARES,
	[LumiaAlertValues.TIKTOK_SUBSCRIBER]: LumiaEventListTypes.SUBSCRIBERS,
	[LumiaAlertValues.KICK_FOLLOWER]: LumiaEventListTypes.FOLLOWER,
	[LumiaAlertValues.KICK_SESSION_FOLLOWERS]: LumiaEventListTypes.FOLLOWER,
	[LumiaAlertValues.KICK_GIFT_SUBSCRIPTION]: LumiaEventListTypes.GIFTS,
	[LumiaAlertValues.KICK_SESSION_GIFTS]: LumiaEventListTypes.GIFTS,
	[LumiaAlertValues.KICK_SUBSCRIBER]: LumiaEventListTypes.SUBSCRIBERS,
	[LumiaAlertValues.KICK_SESSION_SUBS]: LumiaEventListTypes.SUBSCRIBERS,
	[LumiaAlertValues.TILTIFY_DONATION]: LumiaEventListTypes.DONATION,
	[LumiaAlertValues.TIPEEESTREAM_DONATION]: LumiaEventListTypes.DONATION,
	[LumiaAlertValues.TREATSTREAM_TREAT]: LumiaEventListTypes.PURCHASES,
	[LumiaAlertValues.TROVO_FOLLOWER]: LumiaEventListTypes.FOLLOWER,
	[LumiaAlertValues.TROVO_GIFT_SUBSCRIPTION]: LumiaEventListTypes.GIFTS,
	[LumiaAlertValues.TROVO_RAID]: LumiaEventListTypes.RAIDS,
	[LumiaAlertValues.TROVO_SPELL]: LumiaEventListTypes.SPELLS,
	[LumiaAlertValues.TROVO_SUBSCRIBER]: LumiaEventListTypes.SUBSCRIBERS,
	[LumiaAlertValues.TWITCH_BITS]: LumiaEventListTypes.BITS,
	[LumiaAlertValues.TWITCH_SESSION_BITS]: LumiaEventListTypes.BITS,
	[LumiaAlertValues.TWITCH_POWERUPS]: LumiaEventListTypes.BITS,
	[LumiaAlertValues.TWITCH_POWERUPS_POINTS]: LumiaEventListTypes.POINTS,
	[LumiaAlertValues.TWITCH_CLIP]: LumiaEventListTypes.OTHERS,
	[LumiaAlertValues.TWITCH_EXTENSION]: LumiaEventListTypes.EXTENSION,
	[LumiaAlertValues.TWITCH_FOLLOWER]: LumiaEventListTypes.FOLLOWER,
	[LumiaAlertValues.TWITCH_SESSION_FOLLOWERS]: LumiaEventListTypes.FOLLOWER,
	[LumiaAlertValues.TWITCH_GIFT_SUBSCRIPTION]: LumiaEventListTypes.GIFTS,
	[LumiaAlertValues.TWITCH_SESSION_GIFTS]: LumiaEventListTypes.GIFTS,
	[LumiaAlertValues.TWITCH_HYPETRAIN_STARTED]: LumiaEventListTypes.HYPETRAIN,
	[LumiaAlertValues.TWITCH_POINTS]: LumiaEventListTypes.POINTS,
	[LumiaAlertValues.KICK_POINTS]: LumiaEventListTypes.POINTS,
	[LumiaAlertValues.TWITCH_RAID]: LumiaEventListTypes.RAIDS,
	[LumiaAlertValues.TWITCH_RAID_OUT]: LumiaEventListTypes.RAIDS,
	[LumiaAlertValues.KICK_HOST]: LumiaEventListTypes.HOSTS,
	[LumiaAlertValues.TWITCH_SHOUTOUT_RECEIVE]: LumiaEventListTypes.OTHERS,
	[LumiaAlertValues.TWITCH_SUBSCRIBER]: LumiaEventListTypes.SUBSCRIBERS,
	[LumiaAlertValues.TWITCH_SESSION_SUBS]: LumiaEventListTypes.SUBSCRIBERS,
	[LumiaAlertValues.TWITCH_CHARITY_DONATION]: LumiaEventListTypes.DONATION,
	[LumiaAlertValues.TWITCH_AD_STARTED]: LumiaEventListTypes.OTHERS,
	[LumiaAlertValues.TWITCH_AD_STOPPED]: LumiaEventListTypes.OTHERS,
	[LumiaAlertValues.TWITTER_FOLLOWER]: LumiaEventListTypes.FOLLOWER,
	[LumiaAlertValues.TWITTER_LIKE]: LumiaEventListTypes.LIKES,
	[LumiaAlertValues.TWITTER_RETWEET]: LumiaEventListTypes.RETWEETS,
	[LumiaAlertValues.WOOCOMMERCE_ORDER]: LumiaEventListTypes.PURCHASES,
	[LumiaAlertValues.YOUTUBE_MEMBER]: LumiaEventListTypes.SUBSCRIBERS,
	[LumiaAlertValues.YOUTUBE_SUBSCRIBER]: LumiaEventListTypes.FOLLOWER,
	[LumiaAlertValues.YOUTUBE_SUPERCHAT]: LumiaEventListTypes.SUPERCHATS,
	[LumiaAlertValues.YOUTUBE_SUPERSTICKER]: LumiaEventListTypes.SUPERSTICKERS,
	[LumiaAlertValues.YOUTUBE_LIKE]: LumiaEventListTypes.LIKES,
	[LumiaAlertValues.YOUTUBE_VIEWERS]: LumiaEventListTypes.OTHERS,
	[LumiaAlertValues.CROWDCONTROL_EFFECT]: LumiaEventListTypes.OTHERS,
};
