export const KickKicksData = [
	{
		value: 'Hell Yeah',
		label: 'Hell Yeah',
		amount: 1,
		helperText: '1 kick',
		imageUrl: 'https://files.kick.com/kicks/gifts/hell-yeah.webp',
		searchText: 'Hell Yeah hell_yeah 1 BASIC BASIC',
		giftId: 'hell_yeah',
	},
	{
		value: 'Hype',
		label: 'Hype',
		amount: 10,
		helperText: '10 kicks',
		imageUrl: 'https://files.kick.com/kicks/gifts/hype.webp',
		searchText: 'Hype hype 10 BASIC BASIC',
		giftId: 'hype',
	},
	{
		value: 'Skull Emoji',
		label: 'Skull Emoji',
		amount: 50,
		helperText: '50 kicks',
		imageUrl: 'https://files.kick.com/kicks/gifts/skull-emoji.webp',
		searchText: 'Skull Emoji skull_emoji 50 BASIC BASIC',
		giftId: 'skull_emoji',
	},
	{
		value: 'Full Send',
		label: 'Full Send',
		amount: 100,
		helperText: '100 kicks',
		imageUrl: 'https://files.kick.com/kicks/gifts/full-send.webp',
		searchText: 'Full Send full_send 100 BASIC BASIC',
		giftId: 'full_send',
	},
	{
		value: 'Rage Quit',
		label: 'Rage Quit',
		amount: 500,
		helperText: '500 kicks',
		imageUrl: 'https://files.kick.com/kicks/gifts/rage-quit.webp',
		searchText: 'Rage Quit rage_quit 500 MID LEVEL_UP',
		giftId: 'rage_quit',
	},
	{
		value: 'Pack It Up',
		label: 'Pack It Up',
		amount: 1000,
		helperText: '1000 kicks',
		imageUrl: 'https://files.kick.com/kicks/gifts/pack-it-up.webp',
		searchText: 'Pack It Up pack_it_up 1000 MID LEVEL_UP',
		giftId: 'pack_it_up',
	},
	{
		value: 'YAP',
		label: 'YAP',
		amount: 2000,
		helperText: '2000 kicks',
		imageUrl: 'https://files.kick.com/kicks/gifts/yap.webp',
		searchText: 'YAP yap 2000 MID LEVEL_UP',
		giftId: 'yap',
	},
	{
		value: 'Stomp',
		label: 'Stomp',
		amount: 5000,
		helperText: '5000 kicks',
		imageUrl: 'https://files.kick.com/kicks/gifts/stomp.webp',
		searchText: 'Stomp stomp 5000 HIGHER LEVEL_UP',
		giftId: 'stomp',
	},
	{
		value: 'Flex',
		label: 'Flex',
		amount: 10000,
		helperText: '10000 kicks',
		imageUrl: 'https://files.kick.com/kicks/gifts/flex.webp',
		searchText: 'Flex flex 10000 HIGHER LEVEL_UP',
		giftId: 'flex',
	},
	{
		value: 'BOOOOOM',
		label: 'BOOOOOM',
		amount: 50000,
		helperText: '50000 kicks',
		imageUrl: 'https://files.kick.com/kicks/gifts/boom.webp',
		searchText: 'BOOOOOM booooom 50000 HIGHER LEVEL_UP',
		giftId: 'booooom',
	},
];
