export enum SystemVariables {
	// Functions
	READ_FILE = 'read_file',
	READ_URL = 'read_url',
	SELECTION = 'selection',
	RANDOM = 'random',
	RANDOM_INPUT = 'random_input',
	SUM_VARIABLES = 'sum_variables',
	GET_COMMANDS = 'get_commands',
	GET_ALL_COMMANDS = 'get_all_commands',
	CONVERT_COLOR_TO_HEX = 'convert_color_to_hex',
	GET_LATEST_FILE_FROM_FOLDER = 'get_latest_file_from_folder',
	GET_RANDOM_FILE_FROM_FOLDER = 'get_random_file_from_folder',
	SCREENSHOT = 'screenshot',
	OBS_SCREENSHOT = 'obs_screenshot',
	OBS_REPLAY = 'obs_replay',
	OBS_VERTICAL_REPLAY = 'obs_vertical_replay',
	GET_QUEUE_COUNT = 'get_queue_count',
	GET_VAR_FROM_MSG = 'get_var_from_msg',
	GET_USER_LOYALTY_POINTS = 'get_user_loyalty_points',
	TRANSLATE = 'translate',

	COMMANDS_URL = 'commands_url',
	SESSION_START_DATE = 'session_start_date',

	// Games
	GAME_LAST_PLAYER = 'game_last_player',

	// Uptimes
	LUMIA_UPTIME = 'lumia_uptime',
	TWITCH_UPTIME = 'twitch_uptime',
	YOUTUBE_UPTIME = 'youtube_uptime',
	FACEBOOK_UPTIME = 'facebook_uptime',
	TROVO_UPTIME = 'trovo_uptime',
	TWITCH_LIVE = 'twitch_live',
	YOUTUBE_LIVE = 'youtube_live',
	TIKTOK_LIVE = 'tiktok_live',
	FACEBOOK_LIVE = 'facebook_live',
	KICK_LIVE = 'kick_live',
	OVERLAYS_BRB_CLIPS = 'overlays_brb_clips',

	// Donations
	LATEST_DONATOR = 'latest_donator',
	LATEST_DONATOR_AMOUNT = 'latest_donator_amount',
	LATEST_DONATOR_CURRENCY = 'latest_donator_currency',
	LATEST_DONATOR_CURRENCY_SYMBOL = 'latest_donator_currency_symbol',
	SESSION_TOP_DONATOR = 'session_top_donator',
	SESSION_TOP_DONATOR_AMOUNT = 'session_top_donator_amount',
	SESSION_TOP_DONATOR_CURRENCY = 'session_top_donator_currency',
	SESSION_TOP_DONATOR_CURRENCY_SYMBOL = 'session_top_donator_currency_symbol',
	TOP_DONATOR = 'top_donator',
	TOP_DONATOR_AMOUNT = 'top_donator_amount',
	TOP_DONATOR_CURRENCY = 'top_donator_currency',
	TOP_DONATOR_CURRENCY_SYMBOL = 'top_donator_currency_symbol',
	TOP_DONATOR_LIST = 'top_donator_list', // Last 10
	TOP_DONATOR_LIST_AMOUNT = 'top_donator_list_amount',
	TOP_DONATOR_LIST_CURRENCY = 'top_donator_list_currency',
	TOP_DONATOR_LIST_CURRENCY_SYMBOL = 'top_donator_list_currency_symbol',
	TOTAL_DONATION_AMOUNT = 'total_donation_amount',
	TOTAL_DONATION_AMOUNT_CURRENCY = 'total_donation_amount_currency',
	TOTAL_DONATION_AMOUNT_CURRENCY_SYMBOL = 'total_donation_amount_currency_symbol',
	SESSION_DONATION_AMOUNT = 'session_donation_amount',
	SESSION_DONATION_AMOUNT_CURRENCY = 'session_donation_amount_currency',
	SESSION_DONATION_AMOUNT_CURRENCY_SYMBOL = 'session_donation_amount_currency_symbol',
	DONATION_COUNT = 'donation_count',
	SESSION_DONATION_COUNT = 'session_donation_count',
	SESSION_DONATOR_LIST = 'session_donator_list',
	SESSION_DONATOR_LIST_WITH_AMOUNT = 'session_donator_list_with_amount',
	TOTAL_RAW_DONATION_AMOUNT = 'total_raw_donation_amount', // # This one doesn't care about currency

	// Games
	RAFFLE_TITLE = 'raffle_title',
	RAFFLE_DESCRIPTION = 'raffle_description',
	RAFFLE_ENTRIES = 'raffle_entries',
	RAFFLE_GENERATED_NUMBER = 'raffle_generated_number',
	RAFFLE_ENTRIES_COUNT = 'raffle_entries_count',
	RAFFLE_WINNERS = 'raffle_winners',
	RAFFLE_TYPE = 'raffle_type',
	RAFFLE_WINNER = 'raffle_winner',
	RAFFLE_WINNER_AVATAR = 'raffle_winner_avatar',
	RAFFLE_ENTRY_COMMAND = 'raffle_entry_command',
	VIEWERQUEUE_TITLE = 'viewerqueue_title',
	VIEWERQUEUE_ENTRY_COMMAND = 'viewerqueue_entry_command',
	VIEWERQUEUE_ENTRIES = 'viewerqueue_entries',
	VIEWERQUEUE_PLAYERS = 'viewerqueue_players',
	VIEWERQUEUE_ENTRIES_COUNT = 'viewerqueue_entries_count',
	VIEWERQUEUE_QUEUE_LIMIT = 'viewerqueue_queue_limit',
	API_ACTION_GLOBAL_RESPONSE = 'api_action_global_response',
	LAST_RANDOM_INPUT = 'last_random_input',
	LOYALTY_CURRENCY_NAME = 'loyalty_currency_name',

	// Platform Specific Variables, Deprecated: Do not use these for any future variables. Just use normal strings unless it isn't tied to an integration within the integration
	TWITCH_FOLLOWAGE = 'twitch_followage',
	TWITCH_NEXT_AD = 'twitch_next_ad',
	TWITCH_GET_AVATAR = 'twitch_get_avatar',
	TWITCH_USER_ID = 'twitch_user_id',
	TWITCH_USERNAME = 'twitch_username',
	TWITCH_CURRENT_VIEWER_COUNT = 'twitch_current_viewer_count',
	TWITCH_CURRENT_VIEWERS = 'twitch_current_viewers',
	TWITCH_TOTAL_FOLLOWER_COUNT = 'twitch_total_follower_count',
	TWITCH_CURRENT_FOLLOWERS = 'twitch_current_followers',
	TWITCH_SESSION_FOLLOWER_COUNT = 'twitch_session_follower_count',
	TWITCH_CURRENT_SUBSCRIBERS = 'twitch_current_subscribers',
	TWITCH_TOTAL_SUBSCRIBER_COUNT = 'twitch_total_subscriber_count',
	TWITCH_SESSION_SUBSCRIBERS_COUNT = 'twitch_session_subscribers_count',
	TWITCH_CURRENT_MODS = 'twitch_current_mods',
	TWITCH_LAST_FOLLOWER = 'twitch_last_follower',
	TWITCH_SESSION_FOLLOWERS = 'twitch_session_follower',
	TWITCH_LAST_SUBSCRIBER = 'twitch_last_subscriber',
	TWITCH_SESSION_SUBSCRIBERS = 'twitch_session_subscribers',
	TWITCH_SESSION_CHAT_COUNT = 'twitch_session_chat_count',
	TWITCH_CURRENT_FIRST_CHATTER = 'twitch_current_first_chatter',
	TWITCH_CURRENT_FIRST_CHATTER_COUNT = 'twitch_current_first_chatter_count',
	TWITCH_PREVIOUS_FIRST_CHATTER = 'twitch_previous_first_chatter',
	TWITCH_PREVIOUS_FIRST_CHATTER_COUNT = 'twitch_previous_first_chatter_count',
	TWITCH_LAST_CHATTER = 'twitch_last_chatter',
	TWITCH_LAST_RAIDER = 'twitch_last_raider',
	TWITCH_LAST_RAID_AMOUNT = 'twitch_last_raid_amount',
	TWITCH_SESSION_RAIDERS = 'twitch_session_raiders',
	TWITCH_TOTAL_BITS_COUNT = 'twitch_total_bits_count',
	TWITCH_SESSION_BITS_COUNT = 'twitch_session_bits_count',
	TWITCH_LAST_BIT = 'twitch_last_bit',
	TWITCH_LAST_BIT_AMOUNT = 'twitch_last_bit_amount',
	TWITCH_SESSION_BITS = 'twitch_session_bits',
	TWITCH_SESSION_BITS_WITH_AMOUNT = 'twitch_session_bits_with_amount',
	TWITCH_LAST_CLIP_ID = 'twitch_last_clip_id',
	TWITCH_LAST_CLIP_URL = 'twitch_last_clip_url',
	TWITCH_LAST_CLIP_THUMBNAIL_URL = 'twitch_last_clip_thumbnail_url',
	TWITCH_CHANNEL_TITLE = 'twitch_channel_title',
	TWITCH_CHANNEL_DESCRIPTION = 'twitch_channel_description',
	TWITCH_AVATAR = 'twitch_avatar',
	TWITCH_OFFLINE_IMAGE = 'twitch_offline_image',
	TWITCH_CATEGORY = 'twitch_category',
	TWITCH_CATEGORY_ID = 'twitch_category_id',
	TWITCH_CURRENT_POLL_ID = 'twitch_current_poll_id',
	TWITCH_CURRENT_PREDICTION_ID = 'twitch_current_prediction_id',

	YOUTUBE_SESSION_CHAT_COUNT = 'youtube_session_chat_count',
	YOUTUBE_CURRENT_FIRST_CHATTER = 'youtube_current_first_chatter',
	YOUTUBE_CURRENT_FIRST_CHATTER_COUNT = 'youtube_current_first_chatter_count',
	YOUTUBE_PREVIOUS_FIRST_CHATTER = 'youtube_previous_first_chatter',
	YOUTUBE_PREVIOUS_FIRST_CHATTER_COUNT = 'youtube_previous_first_chatter_count',
	YOUTUBE_LAST_CHATTER = 'youtube_last_chatter',
	YOUTUBE_SESSION_SUBSCRIBER_COUNT = 'youtube_session_subscriber_count',
	YOUTUBE_TOTAL_SUBSCRIBER_COUNT = 'youtube_total_subscriber_count',
	YOUTUBE_SESSION_SUPERCHAT_COUNT = 'youtube_session_superchat_count',
	YOUTUBE_LAST_SUPERCHATTER = 'youtube_last_superchatter',
	YOUTUBE_SESSION_SUPERCHATTERS = 'youtube_session_superchatters',
	YOUTUBE_SESSION_SUPERSTICKER_COUNT = 'youtube_session_supersticker_count',
	YOUTUBE_LAST_SUPERSTICKER = 'youtube_last_supersticker',
	YOUTUBE_SESSION_SUPERSTICKERS = 'youtube_session_superstickers',
	YOUTUBE_TOTAL_MEMBER_COUNT = 'youtube_total_member_count',
	YOUTUBE_SESSION_MEMBER_COUNT = 'youtube_session_member_count',
	YOUTUBE_LAST_MEMBER = 'youtube_last_member',
	YOUTUBE_SESSION_MEMBERS = 'youtube_session_members',
	YOUTUBE_LAST_SUBSCRIBER = 'youtube_last_subscriber',
	YOUTUBE_TOTAL_VIDEO_COUNT = 'youtube_total_video_count',
	YOUTUBE_TOTAL_VIEW_COUNT = 'youtube_total_view_count',

	FACEBOOK_SESSION_CHAT_COUNT = 'facebook_session_chat_count',
	FACEBOOK_CURRENT_FIRST_CHATTER = 'facebook_current_first_chatter',
	FACEBOOK_CURRENT_FIRST_CHATTER_COUNT = 'facebook_current_first_chatter_count',
	FACEBOOK_PREVIOUS_FIRST_CHATTER = 'facebook_previous_first_chatter',
	FACEBOOK_PREVIOUS_FIRST_CHATTER_COUNT = 'facebook_previous_first_chatter_count',
	FACEBOOK_LAST_CHATTER = 'facebook_last_chatter',
	FACEBOOK_TOTAL_FOLLOWER_COUNT = 'facebook_total_follower_count',
	FACEBOOK_SESSION_FOLLOWER_COUNT = 'facebook_session_follower_count',
	FACEBOOK_TOTAL_FAN_COUNT = 'facebook_total_fan_count',
	FACEBOOK_SESSION_FAN_COUNT = 'facebook_session_fan_count',
	FACEBOOK_REACTION_COUNT = 'facebook_reaction_count',
	FACEBOOK_LAST_STAR = 'facebook_last_star',
	FACEBOOK_LAST_STAR_AMOUNT = 'facebook_last_star_amount',
	FACEBOOK_SESSION_STARS = 'facebook_session_stars',
	FACEBOOK_SESSION_STARS_WITH_AMOUNT = 'facebook_session_stars_with_amount',

	TIKTOK_SESSION_CHAT_COUNT = 'tiktok_session_chat_count',
	TIKTOK_CURRENT_FIRST_CHATTER = 'tiktok_current_first_chatter',
	TIKTOK_CURRENT_FIRST_CHATTER_COUNT = 'tiktok_current_first_chatter_count',
	TIKTOK_PREVIOUS_FIRST_CHATTER = 'tiktok_previous_first_chatter',
	TIKTOK_PREVIOUS_FIRST_CHATTER_COUNT = 'tiktok_previous_first_chatter_count',
	TIKTOK_LAST_CHATTER = 'tiktok_last_chatter',
	TIKTOK_CURRENT_VIEWER_COUNT = 'tiktok_current_viewer_count',
	TIKTOK_TOTAL_FOLLOWER_COUNT = 'tiktok_total_follower_count',
	TIKTOK_SESSION_FOLLOWER_COUNT = 'tiktok_session_follower_count',
	TIKTOK_SESSION_SUBSCRIBER_COUNT = 'tiktok_session_subscriber_count',
	TIKTOK_SESSION_SHARE_COUNT = 'tiktok_session_share_count',
	TIKTOK_LAST_FOLLOWER = 'tiktok_last_follower',
	TIKTOK_LAST_SUBSCRIBER = 'tiktok_last_subscriber',
	TIKTOK_LAST_GIFTER = 'tiktok_last_gifter',
	TIKTOK_SESSION_GIFTERS = 'tiktok_session_gifters',
	TIKTOK_SESSION_GIFTS = 'tiktok_session_gifts',
	TIKTOK_TOTAL_GIFTS = 'tiktok_total_gifts',
	TIKTOK_TOTAL_LIKES = 'tiktok_total_likes',
	TIKTOK_VIDEO_COUNT = 'tiktok_video_count',

	TIKTOK_LAST_VIDEO_TITLE = 'tiktok_last_video_title',
	TIKTOK_LAST_VIDEO_ID = 'tiktok_last_video_id',
	TIKTOK_LAST_VIDEO_LINK = 'tiktok_last_video_link',
	TIKTOK_LAST_VIDEO_EMBED = 'tiktok_last_video_embed',

	KICK_USER_ID = 'kick_user_id',
	KICK_USERNAME = 'kick_username',
	KICK_CHANNEL_TITLE = 'kick_channel_title',
	KICK_CHANNEL_DESCRIPTION = 'kick_channel_description',
	KICK_AVATAR = 'kick_avatar',
	KICK_CATEGORY = 'kick_category',
	KICK_CATEGORY_ID = 'kick_category_id',
	KICK_STREAM_TITLE = 'kick_stream_title',
	KICK_SESSION_CHAT_COUNT = 'kick_session_chat_count',
	KICK_CURRENT_FIRST_CHATTER = 'kick_current_first_chatter',
	KICK_CURRENT_FIRST_CHATTER_COUNT = 'kick_current_first_chatter_count',
	KICK_PREVIOUS_FIRST_CHATTER = 'kick_previous_first_chatter',
	KICK_PREVIOUS_FIRST_CHATTER_COUNT = 'kick_previous_first_chatter_count',
	KICK_LAST_CHATTER = 'kick_last_chatter',
	KICK_CURRENT_VIEWER_COUNT = 'kick_current_viewer_count',
	KICK_TOTAL_FOLLOWER_COUNT = 'kick_total_follower_count',
	KICK_SESSION_FOLLOWER_COUNT = 'kick_session_follower_count',
	KICK_SESSION_SUBSCRIBER_COUNT = 'kick_session_subscriber_count',
	KICK_SESSION_SUBSCRIBERS = 'kick_session_subscribers',
	KICK_LAST_FOLLOWER = 'kick_last_follower',
	KICK_LAST_SUBSCRIBER = 'kick_last_subscriber',
	KICK_GET_AVATAR = 'kick_get_avatar',

	TROVO_LIVE = 'trovo_live',
	TROVO_SESSION_CHAT_COUNT = 'trovo_session_chat_count',
	TROVO_LAST_FOLLOWER = 'trovo_last_follower',
	TROVO_CURRENT_FIRST_CHATTER = 'trovo_current_first_chatter',
	TROVO_CURRENT_FIRST_CHATTER_COUNT = 'trovo_current_first_chatter_count',
	TROVO_PREVIOUS_FIRST_CHATTER = 'trovo_previous_first_chatter',
	TROVO_PREVIOUS_FIRST_CHATTER_COUNT = 'trovo_previous_first_chatter_count',
	TROVO_LAST_CHATTER = 'trovo_last_chatter',
	TROVO_LAST_RAIDER = 'trovo_last_raider',
	TROVO_LAST_RAID_AMOUNT = 'trovo_last_raid_amount',
	TROVO_SESSION_FOLLOWER_COUNT = 'trovo_session_follower_count',
	TROVO_SESSION_SUBSCRIBERS_COUNT = 'trovo_session_subscribers_count',
	TROVO_SESSION_RAIDERS = 'trovo_session_raiders',
	TROVO_LAST_SUBSCRIBER = 'trovo_last_subscriber',
	TROVO_SESSION_SUBSCRIBERS = 'trovo_session_subscribers',

	SPOTIFY_NOW_PLAYING_SONG = 'spotify_now_playing_song',
	SPOTIFY_NOW_PLAYING_IMAGE = 'spotify_now_playing_image',
	SPOTIFY_NOW_PLAYING_ARTIST = 'spotify_now_playing_artist',
	SPOTIFY_NOW_PLAYING_ID = 'spotify_now_playing_id',
	SPOTIFY_NOW_PLAYING_URL = 'spotify_now_playing_url',
	SPOTIFY_NOW_PLAYING_URI = 'spotify_now_playing_uri',
	SPOTIFY_NEXT_SONG = 'spotify_next_song',
	SPOTIFY_NEXT_IMAGE = 'spotify_next_image',
	SPOTIFY_NEXT_ARTIST = 'spotify_next_artist',
	SPOTIFY_NEXT_ID = 'spotify_next_id',
	SPOTIFY_NEXT_URL = 'spotify_next_url',
	SPOTIFY_NEXT_URI = 'spotify_next_uri',
	SPOTIFY_QUEUE = 'spotify_queue',

	YOUTUBEMUSIC_NOW_PLAYING_SONG = 'youtubemusic_now_playing_song',
	YOUTUBEMUSIC_NOW_PLAYING_IMAGE = 'youtubemusic_now_playing_image',
	YOUTUBEMUSIC_NOW_PLAYING_ARTIST = 'youtubemusic_now_playing_artist',
	YOUTUBEMUSIC_NOW_PLAYING_ID = 'youtubemusic_now_playing_id',
	YOUTUBEMUSIC_NOW_PLAYING_URL = 'youtubemusic_now_playing_url',
	YOUTUBEMUSIC_NEXT_SONG = 'youtubemusic_next_song',
	YOUTUBEMUSIC_NEXT_IMAGE = 'youtubemusic_next_image',
	YOUTUBEMUSIC_NEXT_ARTIST = 'youtubemusic_next_artist',
	YOUTUBEMUSIC_NEXT_ID = 'youtubemusic_next_id',
	YOUTUBEMUSIC_NEXT_URL = 'youtubemusic_next_url',
	YOUTUBEMUSIC_QUEUE = 'youtubemusic_queue',

	NOW_PLAYING_ID = 'now_playing_id',
	NOW_PLAYING_TITLE = 'now_playing_title',
	NOW_PLAYING_ARTWORK = 'now_playing_artwork',
	NOW_PLAYING_ARTIST = 'now_playing_artist',
	NOW_PLAYING_ALBUM = 'now_playing_album',
	NOW_PLAYING_LABEL = 'now_playing_label',
	NOW_PLAYING_BPM = 'now_playing_bpm',
	NOW_PLAYING_RATING = 'now_playing_rating',
	NOW_PLAYING_LENGTH = 'now_playing_length',
	NOW_PLAYING_COMMENT = 'now_playing_comment',
	NOW_PLAYING_KEY = 'now_playing_key',
	NOW_PLAYING_URL = 'now_playing_url',
	NOW_PLAYING_SPOTIFY_URL = 'now_playing_spotify_url',
	NOW_PLAYING_BEATPORT_URL = 'now_playing_beatport_url',
	NOW_PLAYING_BEATPORT_ID = 'now_playing_beatport_id',
	NOW_PLAYING_FILE_PATH = 'now_playing_file_path',

	VLC_NOW_PLAYING_MEDIA = 'vlc_now_playing_media',
	VLC_NOW_PLAYING_IMAGE = 'vlc_now_playing_image',
	VLC_NOW_PLAYING_ARTIST = 'vlc_now_playing_artist',
	VLC_NOW_PLAYING_ID = 'vlc_now_playing_id',
	VLC_NOW_PLAYING_URL = 'vlc_now_playing_url',
	VLC_NOW_PLAYING_URI = 'vlc_now_playing_uri',

	VOICEMOD_VOICE_CHANGER_ON = 'voicemod_voice_changer_on',
	VOICEMOD_PREVIOUS_VOICE = 'voicemod_previous_voice',
	VOICEMOD_CURRENT_VOICE = 'voicemod_current_voice',

	WOOCOMMERCE_LAST_ORDER_NAME = 'woocommerce_last_order_name',
	WOOCOMMERCE_LAST_ORDER_FIRST_NAME = 'woocommerce_last_order_first_name',
	WOOCOMMERCE_LAST_ORDER_LAST_NAME = 'woocommerce_last_order_last_name',
	WOOCOMMERCE_LAST_ORDER_ITEM = 'woocommerce_last_order_item',
	WOOCOMMERCE_LAST_ORDER_ITEMS = 'woocommerce_last_order_items',
	WOOCOMMERCE_LAST_ORDER_AMOUNT = 'woocommerce_last_order_amount',
	WOOCOMMERCE_LAST_ORDER_AMOUNT_CURRENCY = 'woocommerce_last_order_amount_currency',

	OBS_IS_STREAMING = 'obs_is_streaming',
	OBS_IS_RECORDING = 'obs_is_recording',
	OBS_LAST_RECORDING_PATH = 'obs_last_recording_path',
	OBS_STUDIO_MODE = 'obs_studio_mode',
	OBS_CURRENT_PROFILE = 'obs_current_profile',
	OBS_CURRENT_SCENE = 'obs_current_scene',
	OBS_PREVIOUS_SCENE = 'obs_previous_scene',
	OBS_CURRENT_TRANSITION = 'obs_current_transition',
	OBS_LAST_REPLAY_BUFFER_PATH = 'obs_last_replay_buffer_path',
	OBS_LAST_VERTICAL_BACKTRACK_PATH = 'obs_last_vertical_backtrack_path',

	SLOBS_CURRENT_SCENE = 'slobs_current_scene',
	SLOBS_PREVIOUS_SCENE = 'slobs_previous_scene',
	SLOBS_CURRENT_SCENE_COLLECTION = 'slobs_current_scene_collection',

	STREAMERBOT_LAST_ACTION = 'streamerbot_last_action',

	VTUBESTUDIO_CURRENT_MODEL = 'vtubestudio_current_model',
	VTUBESTUDIO_CURRENT_BACKGROUND = 'vtubestudio_current_background',
	VTUBESTUDIO_LAST_HOTKEY_TRIGGERED = 'vtubestudio_last_hotkey_triggered',

	ABLETON_BPM = 'ableton_bpm',
	HEARTRATE_BPM = 'heartrate_bpm',
}

export const ReservedVariables = [
	'lumia',
	'lumiastream',
	'lumiacove',
	'read',
	'readFile',
	'readApi',
	'variable',
	'variables',
	'username',
	'displayname',
	'full_message',
	'userId',
	'value',
	'site',
	'command',
	'merch',
	'message',
	'rawMessage',
	'userColor',
	'userColorRgb',
	'platform',
	'points',
	'title',
	'topUserLevel',
	'userLevels',
	'userLevelsRaw',
	'badges',
	'badgesRaw',
	'bits',
	'hasEmotes',
	'emotes',
	'emotesRaw',
	'spell',
	'spell_quantity',
	'spell_type',
	'spell_value',
	'spell_combined_value',
	'spell_mana_value',
	'spell_mana_combined_value',
	'spell_elixir_value',
	'spell_elixir_combined_value',
	'avatar',
	'redemption',
	'amount',
	'currency',
	'viewers',
	'tier',
	'treat',
	'scene',
	'reaction',
	'item',
	'profile',
	'heartrate',
	'cooldown_time_remaining',
	'min_heartrate',
	'max_heartrate',
	'calories',
	'giftAmount',
	'recipient',
	'totalGifts',
	'subMonths',
	'streakMonths',
	'subPlanName',
	'oscValue',
	'osc_value',
	'midi_value',
	'velocity_value',
	'velocity',
	'midiValue',
	'artnet_value',
	'artnetValue',
	'cycles',
	'duration',
	'checkTimingType',
	'timingType',
	'twitch_clip_id',
	'twitchClipId',
	'commands',
	'commands_url',
	'user_levels',
	'user_levels_raw',
	'twitch_user_id',
	'twitch_username',
	'clip_shoutout_url',
	'clip_title',
	'clip_url',
	'clip_target_username',
	'clip_target_userid',
	'clip_target_avatar',
	'clip_thumbnail_url',
	'clip_duration',
	'clip_target_channel',
	'clip_embed_url',
	'clip_id',
	'clip_creator_id',
	'clip_creator_name',
	'clip_game_id',
	'clip_language',
	'clip_view_count',
	'clip_created_at',
	'clip_target_displayname',
	'clip_target_language',
	'clip_target_category_id',
	'clip_target_category',
	'clip_target_channel_title',
	'clip_target_channel_tags',
	'follow_time',
	'uptime',
];

export const AllVariables = {
	lumiastream: {
		variables: [
			'read_file',
			'read_url',
			'selection',
			'random',
			'random_input',
			'sum_variables',
			'get_commands',
			'get_all_commands',
			'convert_color_to_hex',
			'get_latest_file_from_folder',
			'get_random_file_from_folder',
			'screenshot',
			'get_queue_count',
			'get_var_from_msg',
			'get_user_loyalty_points',
			'translate',
			'commands_url',
			'session_start_date',
			'game_last_player',
			'lumia_uptime',
			'overlays_brb_clips',
			'latest_donator',
			'latest_donator_amount',
			'latest_donator_currency',
			'latest_donator_currency_symbol',
			'session_top_donator',
			'session_top_donator_amount',
			'session_top_donator_currency',
			'session_top_donator_currency_symbol',
			'top_donator',
			'top_donator_amount',
			'top_donator_currency',
			'top_donator_currency_symbol',
			'top_donator_list_amount',
			'top_donator_list_currency',
			'top_donator_list_currency_symbol',
			'total_donation_amount',
			'total_donation_amount_currency',
			'total_donation_amount_currency_symbol',
			'session_donation_amount',
			'session_donation_amount_currency',
			'session_donation_amount_currency_symbol',
			'donation_count',
			'session_donation_count',
			'session_donator_list',
			'session_donator_list_with_amount',
			'raffle_title',
			'raffle_description',
			'raffle_entries',
			'raffle_generated_number',
			'raffle_entries_count',
			'raffle_winners',
			'raffle_type',
			'raffle_winner',
			'raffle_winner_avatar',
			'raffle_entry_command',
			'viewerqueue_title',
			'viewerqueue_entry_command',
			'viewerqueue_entries',
			'viewerqueue_players',
			'viewerqueue_entries_count',
			'viewerqueue_queue_limit',
			'api_action_global_response',
			'last_random_input',
			'loyalty_currency_name',
			'now_playing_id',
			'now_playing_title',
			'now_playing_artwork',
			'now_playing_artist',
			'now_playing_album',
			'now_playing_label',
			'now_playing_bpm',
			'now_playing_rating',
			'now_playing_length',
			'now_playing_comment',
			'now_playing_key',
			'now_playing_url',
			'now_playing_spotify_url',
			'now_playing_beatport_url',
			'now_playing_beatport_id',
			'now_playing_file_path',
			'heartrate_bpm',
		],
		chat: {
			cooldowns: ['cooldown_time_remaining'],
			command: [
				'username',
				'displayname',
				'userId',
				'avatar',
				'userLevels',
				'userLevelsRaw',
				'channelDescription',
				'channelViews',
				'command',
				'message',
				'messageId',
				'rawMessage',
				'userColor',
				'platform',
				'badgesRaw',
				'hasEmotes',
				'emotes',
				'emotesRaw',
				'timestamp',
				'points_cost',
			],
			chatbotCommand: [
				'username',
				'displayname',
				'userId',
				'avatar',
				'userLevels',
				'userLevelsRaw',
				'channelDescription',
				'channelViews',
				'command',
				'message',
				'messageId',
				'rawMessage',
				'userColor',
				'platform',
				'badgesRaw',
				'hasEmotes',
				'emotes',
				'emotesRaw',
				'timestamp',
			],
			twitchPoints: ['username', 'displayname', 'userId', 'avatar', 'channelDescription', 'channelViews', 'command', 'prompt', 'message', 'rawMessage', 'points', 'title', 'timestamp'],
			kickPoints: ['username', 'displayname', 'userId', 'avatar', 'channelDescription', 'channelViews', 'command', 'prompt', 'message', 'rawMessage', 'points', 'title', 'timestamp'],
			trovoSpells: [
				'username',
				'displayname',
				'spell',
				'spell_quantity',
				'spell_type',
				'spell_value',
				'spell_combined_value',
				'spell_mana_value',
				'spell_mana_combined_value',
				'spell_elixir_value',
				'spell_elixir_combined_value',
				'timestamp',
			],
			twitchExtensions: ['username', 'displayname', 'userId', 'avatar', 'channelDescription', 'channelViews', 'command', 'prompt', 'message', 'bits', 'timestamp', 'points_cost'],
			fileWatcher: ['content', 'file', 'path', 'timestamp'],
			chatmatch: ['language_detect_result', 'detected_language', 'detected_language_code'],

			commands: [
				'get_all_commands',
				'get_commands',
				'username',
				'displayname',
				'userId',
				'avatar',
				'userLevels',
				'userLevelsRaw',
				'channelDescription',
				'channelViews',
				'command',
				'message',
				'messageId',
				'rawMessage',
				'userColor',
				'platform',
				'badgesRaw',
				'hasEmotes',
				'emotes',
				'emotesRaw',
				'timestamp',
			],
			shoutout: [
				'clip_shoutout_url',
				'clip_title',
				'clip_url',
				'clip_target_username',
				'clip_target_userid',
				'clip_target_avatar',
				'clip_thumbnail_url',
				'clip_duration',
				'clip_target_channel',
				'clip_embed_url',
				'clip_id',
				'clip_creator_id',
				'clip_creator_name',
				'clip_game_id',
				'clip_language',
				'clip_view_count',
				'clip_created_at',
				'clip_target_displayname',
				'clip_target_language',
				'clip_target_category_id',
				'clip_target_category',
				'clip_target_channel_title',
				'clip_target_channel_tags',
				'username',
				'displayname',
				'userId',
				'avatar',
				'userLevels',
				'userLevelsRaw',
				'channelDescription',
				'channelViews',
				'command',
				'message',
				'messageId',
				'rawMessage',
				'userColor',
				'platform',
				'badgesRaw',
				'hasEmotes',
				'emotes',
				'emotesRaw',
				'timestamp',
			],
			followage: [
				'follow_time',
				'username',
				'displayname',
				'userId',
				'avatar',
				'userLevels',
				'userLevelsRaw',
				'channelDescription',
				'channelViews',
				'command',
				'message',
				'messageId',
				'rawMessage',
				'userColor',
				'platform',
				'badgesRaw',
				'hasEmotes',
				'emotes',
				'emotesRaw',
				'timestamp',
			],
			uptime: [
				'uptime',
				'username',
				'displayname',
				'userId',
				'avatar',
				'userLevels',
				'userLevelsRaw',
				'channelDescription',
				'channelViews',
				'command',
				'message',
				'messageId',
				'rawMessage',
				'userColor',
				'platform',
				'badgesRaw',
				'hasEmotes',
				'emotes',
				'emotesRaw',
				'timestamp',
			],
			aichat: [
				'ai_response',
				'username',
				'displayname',
				'userId',
				'avatar',
				'userLevels',
				'userLevelsRaw',
				'channelDescription',
				'channelViews',
				'command',
				'message',
				'messageId',
				'rawMessage',
				'userColor',
				'platform',
				'badgesRaw',
				'hasEmotes',
				'emotes',
				'emotesRaw',
				'timestamp',
			],
			loyaltyPoints: [
				'points_balance',
				'user_rank',
				'total_rank',
				'loyalty_currency_name',
				'get_user_loyalty_points',
				'username',
				'displayname',
				'userId',
				'avatar',
				'userLevels',
				'userLevelsRaw',
				'channelDescription',
				'channelViews',
				'command',
				'message',
				'messageId',
				'rawMessage',
				'userColor',
				'platform',
				'badgesRaw',
				'hasEmotes',
				'emotes',
				'emotesRaw',
				'timestamp',
			],
			roulette: [
				'roulette_result',
				'ball_position',
				'outcome_amount',
				'username',
				'displayname',
				'userId',
				'avatar',
				'userLevels',
				'userLevelsRaw',
				'channelDescription',
				'channelViews',
				'command',
				'message',
				'messageId',
				'rawMessage',
				'userColor',
				'platform',
				'badgesRaw',
				'hasEmotes',
				'emotes',
				'emotesRaw',
				'timestamp',
			],
			duel: [
				'duel_result',
				'duel_winner',
				'duel_loser',
				'duel_target_username',
				'duel_duration',
				'outcome_amount',
				'username',
				'displayname',
				'userId',
				'avatar',
				'userLevels',
				'userLevelsRaw',
				'channelDescription',
				'channelViews',
				'command',
				'message',
				'messageId',
				'rawMessage',
				'userColor',
				'platform',
				'badgesRaw',
				'hasEmotes',
				'emotes',
				'emotesRaw',
				'timestamp',
			],
			slots: [
				'slots_result',
				'slots_combo',
				'outcome_amount',
				'username',
				'displayname',
				'userId',
				'avatar',
				'userLevels',
				'userLevelsRaw',
				'channelDescription',
				'channelViews',
				'command',
				'message',
				'messageId',
				'rawMessage',
				'userColor',
				'platform',
				'badgesRaw',
				'hasEmotes',
				'emotes',
				'emotesRaw',
				'timestamp',
			],
			raffleEntry: [
				'raffle_title',
				'raffle_description',
				'raffle_entries',
				'raffle_generated_number',
				'raffle_entries_count',
				'raffle_winners',
				'raffle_type',
				'raffle_winner',
				'raffle_winner_avatar',
				'raffle_entry_command',
				'username',
				'displayname',
				'userId',
				'avatar',
				'userLevels',
				'userLevelsRaw',
				'channelDescription',
				'channelViews',
				'command',
				'message',
				'messageId',
				'rawMessage',
				'userColor',
				'platform',
				'badgesRaw',
				'hasEmotes',
				'emotes',
				'emotesRaw',
				'timestamp',
			],
			viewerQueueEntry: [
				'viewerqueue_title',
				'viewerqueue_entry_command',
				'viewerqueue_entries',
				'viewerqueue_players',
				'viewerqueue_entries_count',
				'viewerqueue_queue_limit',
				'username',
				'displayname',
				'userId',
				'avatar',
				'userLevels',
				'userLevelsRaw',
				'channelDescription',
				'channelViews',
				'command',
				'message',
				'messageId',
				'rawMessage',
				'userColor',
				'platform',
				'badgesRaw',
				'hasEmotes',
				'emotes',
				'emotesRaw',
				'timestamp',
			],
		},
		alerts: {
			lumiaOpened: ['date'],
			lumiaClosed: ['date'],
			streammodeOn: ['date'],
			streammodeOff: ['date'],
			donation: ['username', 'avatar', 'sender_social_link', 'currency', 'amount', 'message', 'anonymous', 'command'],
			spinwheelWinner: ['spinwheel_winner', 'spinwheel_item', 'spinwheel_item_id', 'spinwheel_item_image', 'spinwheel_item_quantity_remaining', 'spinwheel_item_quantity_initial'],
			raffleStart: ['raffle_title', 'raffle_description', 'raffle_type', 'raffle_entry_command', 'raffle_generated_number'],
			raffleStop: ['raffle_title', 'raffle_description', 'raffle_type', 'raffle_entry_command', 'duration', 'raffle_generated_number'],
			raffleWinner: [
				'raffle_title',
				'raffle_description',
				'raffle_type',
				'raffle_winner',
				'raffle_winner_avatar',
				'raffle_winners',
				'raffle_entry_command',
				'duration',
				'raffle_generated_number',
			],
			pollStarted: ['poll_title', 'poll_id', 'poll_choices'],
			pollProgressed: ['poll_title', 'poll_id', 'poll_choices', 'poll_winning_title', 'poll_winning_id', 'poll_winning_votes', 'poll_total_votes'],
			pollEnded: ['poll_id', 'poll_title', 'poll_choices', 'poll_winning_title', 'poll_winning_id', 'poll_winning_votes', 'poll_total_votes'],
			viewerqueueStarted: ['viewerqueue_title', 'viewerqueue_entry_command', 'viewerqueue_entries', 'viewerqueue_players', 'viewerqueue_entries_count'],
			viewerqueueEnded: ['viewerqueue_title', 'viewerqueue_entry_command', 'viewerqueue_entries', 'viewerqueue_players', 'viewerqueue_entries_count'],
			rouletteWinner: ['username', 'outcome_amount', 'ball_position'],
			slotsWinner: ['username', 'outcome_amount', 'slots_combo'],
		},
	},
	ableton: {
		variables: ['ableton_bpm'],
	},
	crowdcontrol: {
		alerts: {
			effect: ['username', 'displayname', 'avatar', 'platform', 'effect', 'effectId', 'game', 'gameId', 'artwork', 'message', 'duration'],
		},
	},
	discord: {
		alerts: {
			firstChatter: ['username', 'userId', 'displayname', 'avatar', 'first_count', 'message'],
			entrance: ['username', 'userId', 'displayname', 'avatar', 'message'],
		},
	},
	donordrive: {
		alerts: {
			donation: ['username', 'currency', 'amount'],
		},
	},
	extralife: {
		alerts: {
			donation: ['username', 'currency', 'amount'],
		},
	},
	facebook: {
		variables: [
			'facebook_uptime',
			'facebook_live',
			'facebook_session_chat_count',
			'facebook_current_first_chatter',
			'facebook_current_first_chatter_count',
			'facebook_previous_first_chatter',
			'facebook_previous_first_chatter_count',
			'facebook_last_chatter',
			'facebook_total_follower_count',
			'facebook_session_follower_count',
			'facebook_total_fan_count',
			'facebook_session_fan_count',
			'facebook_reaction_count',
			'facebook_last_star',
			'facebook_last_star_amount',
			'facebook_session_stars',
			'facebook_session_stars_with_amount',
		],
		alerts: {
			streamLive: [],
			streamOffline: [],
			firstChatter: ['username', 'first_count', 'message'],
			entrance: ['username', 'message'],
			follower: ['username'],
			fan: ['username'],
			reaction: ['username', 'reaction'],
			star: ['username', 'amount'],
			support: ['username', 'amount'],
			subscriptionGift: ['username', 'recipient', 'recipients', 'recipientsRaw', 'gifter', 'giftAmount', 'message'],
			share: ['username'],
		},
	},
	fourthwall: {
		alerts: {
			donation: ['username', 'email', 'message', 'currency', 'amount', 'raw'],
			subscription: ['username', 'email', 'currency', 'amount', 'interval', 'raw'],
			commission: ['username', 'email', 'message', 'currency', 'amount', 'raw'],
			shopOrder: ['username', 'email', 'message', 'currency', 'amount', 'raw'],
			giftPurchase: ['username', 'email', 'message', 'currency', 'amount', 'raw'],
		},
	},
	kick: {
		variables: [
			'kick_user_id',
			'kick_username',
			'kick_channel_title',
			'kick_channel_description',
			'kick_avatar',
			'kick_category',
			'kick_category_id',
			'kick_live',
			'kick_get_avatar={{message}}',
			'kick_stream_title',
			'kick_session_chat_count',
			'kick_current_first_chatter',
			'kick_current_first_chatter_count',
			'kick_previous_first_chatter',
			'kick_previous_first_chatter_count',
			'kick_last_chatter',
			'kick_current_viewer_count',
			'kick_total_follower_count',
			'kick_session_follower_count',
			'kick_session_subscriber_count',
			'kick_session_subscribers',
			'kick_last_follower',
			'kick_last_subscriber',
			'kick_get_avatar',
		],
		alerts: {
			firstChatter: ['username', 'userId', 'displayname', 'avatar', 'first_count', 'message'],
			entrance: ['username', 'userId', 'displayname', 'avatar', 'message'],
			follower: ['username'],
			subscriber: ['username', 'avatar', 'tier', 'recipient', 'subMonths', 'streakMonths', 'message', 'subPlan', 'subPlanName'],
			subscriptionGift: ['username', 'avatar', 'tier', 'giftAmount', 'recipients', 'recipientsRaw', 'gifter', 'totalGifts', 'subMonths', 'streakMonths', 'message', 'subPlan', 'subPlanName'],
			host: ['username', 'avatar', 'viewers'],
			banned: ['username', 'userId', 'bannedByUsername', 'bannedByUserId', 'expires'],
			unbanned: ['username', 'userId', 'unbannedByUsername', 'unbannedByUserId'],
		},
	},
	kofi: {
		variables: ['kofi_last_order_name', 'kofi_last_order_amount', 'kofi_last_order_amount_currency'],
		alerts: {
			donation: ['username', 'email', 'currency', 'amount'],
			subscription: ['username', 'email', 'currency', 'amount', 'tier'],
			commission: ['username', 'email', 'currency', 'amount'],
			shopOrder: ['username', 'email', 'currency', 'amount'],
		},
	},
	meld: {
		alerts: {
			streamStarting: [],
			streamStopping: [],
			recordingStarting: [],
			recordingStopping: [],
		},
	},
	nowplaying: {
		variables: [
			'now_playing_id',
			'now_playing_title',
			'now_playing_artwork',
			'now_playing_artist',
			'now_playing_album',
			'now_playing_label',
			'now_playing_bpm',
			'now_playing_rating',
			'now_playing_length',
			'now_playing_comment',
			'now_playing_key',
			'now_playing_url',
			'now_playing_spotify_url',
			'now_playing_beatport_url',
			'now_playing_beatport_id',
			'now_playing_file_path',
		],
		alerts: {
			switchSong: ['id', 'title', 'artwork', 'artist', 'album', 'label', 'bpm', 'rating', 'length', 'comment', 'key', 'url', 'spotify_url', 'beatport_url', 'beatport_id', 'file_key'],
		},
	},
	obs: {
		variables: [
			'obs_screenshot',
			'obs_replay',
			'obs_vertical_replay',
			'obs_is_streaming',
			'obs_is_recording',
			'obs_last_recording_path',
			'obs_studio_mode',
			'obs_current_profile',
			'obs_current_scene',
			'obs_previous_scene',
			'obs_current_transition',
			'obs_last_replay_buffer_path',
			'obs_last_vertical_backtrack_path',
		],
		alerts: {
			switchScene: ['scene'],
			sceneItemVisibility: ['item'],
			sceneItemHidden: ['item'],
			switchProfile: ['profile'],
			switchTransition: ['transition'],
			transitionBegin: ['transition'],
			transitionEnd: ['transition'],
			streamStarting: [],
			streamStopping: [],
			recordingStarting: ['output_key'],
			recordingStopping: ['output_key'],
			replayBufferSaved: ['saved_key'],
			verticalBacktrackSaved: ['saved_key', 'height', 'width'],
			vendorEvent: ['eventType', 'eventData', 'vendorName'],
		},
	},
	patreon: {
		alerts: {
			campaignPledge: ['username', 'currency', 'amount'],
		},
	},
	pulse: {
		alerts: {
			heartrate: ['heartrate', 'min_heartrate', 'max_heartrate'],
			calories: [],
		},
	},
	slobs: {
		variables: ['slobs_current_scene', 'slobs_previous_scene', 'slobs_current_scene_collection'],
		alerts: {
			switchScene: ['scene'],
			switchSceneCollection: ['collection'],
			sceneItemVisibility: ['item'],
			sceneItemHidden: ['item'],
		},
	},
	spotify: {
		variables: [
			'spotify_now_playing_song',
			'spotify_now_playing_image',
			'spotify_now_playing_id',
			'spotify_now_playing_artist',
			'spotify_now_playing_uri',
			'spotify_now_playing_url',
			'spotify_next_song',
			'spotify_next_image',
			'spotify_next_artist',
			'spotify_next_id',
			'spotify_next_url',
			'spotify_next_uri',
			'spotify_queue',
		],
		alerts: {
			switchSong: ['name', 'uri', 'image'],
			songPlayed: ['name', 'uri', 'image'],
			songPaused: ['name', 'uri', 'image'],
		},
	},
	streamelements: {
		alerts: {
			donation: ['username', 'currency', 'amount', 'message'],
		},
	},
	streamerbot: {
		variables: ['streamerbot_last_action'],
		alerts: {
			action: ['action', 'actionId'],
		},
	},
	streamlabs: {
		alerts: {
			donation: ['username', 'currency', 'amount', 'message'],
			charity: ['username', 'currency', 'amount', 'message'],
			merch: ['username', 'merch', 'message'],
			redemption: ['username', 'redemption', 'message'],
			primeGift: ['username'],
		},
	},
	tiktok: {
		variables: [
			'tiktok_live',
			'tiktok_session_chat_count',
			'tiktok_current_first_chatter',
			'tiktok_current_first_chatter_count',
			'tiktok_previous_first_chatter',
			'tiktok_previous_first_chatter_count',
			'tiktok_last_chatter',
			'tiktok_current_viewer_count',
			'tiktok_total_follower_count',
			'tiktok_session_follower_count',
			'tiktok_session_subscriber_count',
			'tiktok_session_share_count',
			'tiktok_last_follower',
			'tiktok_last_subscriber',
			'tiktok_last_gifter',
			'tiktok_session_gifters',
			'tiktok_session_gifts',
			'tiktok_total_gifts',
			'tiktok_total_likes',
			'tiktok_video_count',
			'tiktok_last_video_title',
			'tiktok_last_video_id',
			'tiktok_last_video_link',
			'tiktok_last_video_embed',
		],
		alerts: {
			firstChatter: ['username', 'userId', 'displayname', 'avatar', 'first_count', 'message'],
			entrance: ['username', 'userId', 'displayname', 'avatar', 'message'],
			follower: ['username', 'userId', 'displayname', 'avatar'],
			subscriber: ['username', 'displayname', 'subMonths', 'avatar'],
			gift: ['username', 'userId', 'profilePictureUrl', 'describe', 'coins', 'giftId', 'giftName', 'giftPictureUrl', 'giftType', 'isNewGifter', 'receiverUserId', 'repeatCount', 'repeatEnd'],
			like: ['username', 'userId', 'displayname', 'avatar', 'userLikeCount', 'totalLikeCount'],
			share: ['username', 'userId', 'displayname', 'avatar'],
			streamEnd: ['eventTime'],
			newVideo: ['title', 'description', 'embed', 'link', 'id', 'duration', 'likes', 'shares', 'views', 'comments'],
		},
	},
	tiltify: {
		alerts: {
			campaignDonation: ['username', 'currency', 'amount'],
		},
	},
	tipeeestream: {
		alerts: {
			donation: ['username', 'currency', 'amount'],
		},
	},
	treatstream: {
		alerts: {
			treat: ['username', 'treat'],
		},
	},
	trovo: {
		variables: [
			'trovo_uptime',
			'trovo_live',
			'trovo_session_chat_count',
			'trovo_last_follower',
			'trovo_current_first_chatter',
			'trovo_current_first_chatter_count',
			'trovo_previous_first_chatter',
			'trovo_previous_first_chatter_count',
			'trovo_last_chatter',
			'trovo_last_raider',
			'trovo_last_raid_amount',
			'trovo_session_follower_count',
			'trovo_session_subscribers_count',
			'trovo_session_raiders',
			'trovo_last_subscriber',
			'trovo_session_subscribers',
		],
		alerts: {
			streamLive: [],
			streamOffline: [],
			firstChatter: ['username', 'displayname', 'avatar', 'first_count', 'message'],
			entrance: ['username', 'displayname', 'avatar', 'message'],
			channelJoin: ['username', 'displayname', 'sub_tier', 'sub_level', 'avatar', 'roles', 'medals'],
			follower: ['username'],
			subscriber: ['username', 'displayname', 'sub_tier', 'sub_level', 'avatar', 'roles', 'medals'],
			subscriptionGift: [
				'username',
				'displayname',
				'avatar',
				'tier',
				'giftAmount',
				'recipients',
				'recipientsRaw',
				'gifter',
				'totalGifts',
				'subMonths',
				'streakMonths',
				'message',
				'subPlan',
				'subPlanName',
				'roles',
				'medals',
			],
			raid: ['username', 'viewers', 'displayname', 'viewers', 'sub_tier', 'sub_level', 'avatar', 'roles', 'medals'],
		},
	},
	twitch: {
		variables: [
			'twitch_uptime',
			'twitch_live',
			'twitch_followage={{username}}',
			'twitch_next_ad',
			'twitch_get_avatar={{message}}',
			'twitch_followage',
			'twitch_get_avatar',
			'twitch_user_id',
			'twitch_username',
			'twitch_current_viewer_count',
			'twitch_current_viewers',
			'twitch_total_follower_count',
			'twitch_current_followers',
			'twitch_session_follower_count',
			'twitch_current_subscribers',
			'twitch_total_subscriber_count',
			'twitch_session_subscribers_count',
			'twitch_current_mods',
			'twitch_last_follower',
			'twitch_session_follower',
			'twitch_last_subscriber',
			'twitch_session_subscribers',
			'twitch_session_chat_count',
			'twitch_current_first_chatter',
			'twitch_current_first_chatter_count',
			'twitch_previous_first_chatter',
			'twitch_previous_first_chatter_count',
			'twitch_last_chatter',
			'twitch_last_raider',
			'twitch_last_raid_amount',
			'twitch_session_raiders',
			'twitch_total_bits_count',
			'twitch_session_bits_count',
			'twitch_last_bit',
			'twitch_last_bit_amount',
			'twitch_session_bits',
			'twitch_session_bits_with_amount',
			'twitch_last_clip_id',
			'twitch_last_clip_url',
			'twitch_last_clip_thumbnail_url',
			'twitch_channel_title',
			'twitch_channel_description',
			'twitch_avatar',
			'twitch_offline_image',
			'twitch_category',
			'twitch_category_id',
			'twitch_current_poll_id',
			'twitch_current_prediction_id',
		],
		alerts: {
			streamLive: ['eventTime'],
			streamOffline: [],
			firstChatter: ['username', 'userId', 'displayname', 'avatar', 'first_count', 'message'],
			entrance: ['username', 'userId', 'displayname', 'avatar', 'message'],
			follower: ['username', 'avatar'],
			subscriber: ['username', 'avatar', 'tier', 'recipient', 'subMonths', 'streakMonths', 'message', 'subPlan', 'subPlanName'],
			giftSubscription: ['username', 'avatar', 'tier', 'giftAmount', 'recipients', 'recipientsRaw', 'gifter', 'totalGifts', 'subMonths', 'streakMonths', 'message', 'subPlan', 'subPlanName'],
			bits: ['username', 'avatar', 'amount', 'message', 'rawMessage', 'full_message'],
			raid: ['username', 'avatar', 'viewers'],
			hypetrainStarted: ['total', 'progress', 'goal'],
			hypetrainProgressed: ['level', 'total', 'progress', 'goal'],
			hypetrainLevelProgressed: ['level', 'total', 'progress', 'goal'],
			hypetrainEnded: ['level', 'total'],
			pollStarted: ['poll_title', 'poll_id', 'poll_choices', 'poll_started_at', 'poll_ends_at'],
			pollProgressed: ['poll_title', 'poll_id', 'poll_choices', 'poll_winning_title', 'poll_winning_id', 'poll_winning_votes', 'poll_started_at', 'poll_ends_at'],
			pollEnded: ['poll_id', 'poll_title', 'poll_choices', 'poll_winning_title', 'poll_winning_id', 'poll_winning_votes', 'poll_started_at', 'poll_ends_at'],
			predictionStarted: [
				'prediction_title',
				'prediction_id',
				'prediction_possible_outcomes',
				'prediction_outcome1_title',
				'prediction_outcome1_points',
				'prediction_outcome1_color',
				'prediction_outcome2_title',
				'prediction_outcome2_points',
				'prediction_outcome2_color',
				'prediction_started_at',
				'prediction_ends_at',
			],
			predictionProgressed: [
				'prediction_title',
				'prediction_id',
				'prediction_possible_outcomes',
				'prediction_winning_outcome_title',
				'prediction_winning_outcome_points',
				'prediction_winning_outcome_color',
				'prediction_outcome1_title',
				'prediction_outcome1_points',
				'prediction_outcome1_color',
				'prediction_outcome2_title',
				'prediction_outcome2_points',
				'prediction_outcome2_color',
				'prediction_started_at',
				'prediction_ends_at',
			],
			predictionLocked: [
				'prediction_title',
				'prediction_id',
				'prediction_possible_outcomes',
				'prediction_winning_outcome_title',
				'prediction_winning_outcome_points',
				'prediction_winning_outcome_color',
				'prediction_outcome1_title',
				'prediction_outcome1_points',
				'prediction_outcome1_color',
				'prediction_outcome2_title',
				'prediction_outcome2_points',
				'prediction_outcome2_color',
				'prediction_started_at',
				'prediction_ends_at',
			],
			predictionEnded: [
				'prediction_title',
				'prediction_id',
				'prediction_possible_outcomes',
				'prediction_winning_outcome_title',
				'prediction_winning_outcome_points',
				'prediction_winning_outcome_color',
				'prediction_outcome1_title',
				'prediction_outcome1_points',
				'prediction_outcome1_color',
				'prediction_outcome2_title',
				'prediction_outcome2_points',
				'prediction_outcome2_color',
				'prediction_started_at',
				'prediction_ends_at',
			],
			goalStarted: ['goal_type', 'goal_id', 'goal_description', 'goal_amount', 'goal_target_amount'],
			goalProgressed: ['goal_type', 'goal_id', 'goal_description', 'goal_amount', 'goal_target_amount'],
			goalEnded: ['goal_type', 'goal_id', 'goal_description', 'goal_amount', 'goal_target_amount', 'goal_achieved', 'goal_status'],
			charityDonation: ['userId', 'username', 'displayname', 'amount', 'currency', 'campaign_id', 'charity_name', 'charity_description', 'charity_logo', 'charity_website'],
			charityCampaignStarted: ['charity_name', 'charity_description', 'charity_logo', 'charity_amount', 'charity_target_amount', 'charity_website', 'currency', 'started_at'],
			charityCampaignProgressed: ['charity_name', 'charity_description', 'charity_logo', 'charity_amount', 'charity_target_amount', 'charity_website', 'currency'],
			charityCampaignStopped: ['charity_name', 'charity_description', 'charity_logo', 'charity_amount', 'charity_target_amount', 'charity_website', 'currency', 'ended_at'],
			categoryChanged: ['category_name', 'category_id', 'channel_title'],
			clip: [
				'username',
				'avatar',
				'displayname',
				'userId',
				'clip_url',
				'clip_id',
				'clip_title',
				'clip_duration',
				'clip_user_is_mod',
				'clip_user_is_vip',
				'clip_user_is_sub',
				'clip_user_is_follower',
			],
			channelJoin: ['username', 'avatar'],
			channelLeave: ['username', 'avatar'],
			banned: ['username', 'userId', 'avatar', 'reason'],
			timeout: ['username', 'userId', 'avatar', 'timeout_duration', 'expiration_ms', 'reason'],
			timeoutOver: ['username', 'userId', 'avatar', 'timeout_duration', 'expiration_ms', 'reason'],
			shoutoutReceive: ['username', 'userId', 'displayname', 'avatar', 'viewer_count', 'started_at'],
			adStarted: ['length', 'is_automatic', 'started_at', 'twitch_next_ad'],
			adStopped: ['length', 'is_automatic', 'started_at', 'twitch_next_ad'],
			powerups: ['username', 'avatar', 'type', 'amount', 'message', 'rawMessage', 'full_message'],
			powerupsPoints: ['username', 'avatar', 'type', 'amount', 'message', 'rawMessage', 'full_message'],
		},
	},
	twitter: {
		variables: [
			'twitter_last_tweet',
			'twitter_last_tweet_id',
			'twitter_last_tweet_link',
			'twitter_likes_count',
			'twitter_retweets_count',
			'twitter_last_follower_username',
			'twitter_last_follower_id',
			'twitter_last_follower_avatar',
			'twitter_last_follower_tweet',
			'twitter_last_follower_tweet_url',
			'twitter_last_follower_background_color',
			'twitter_last_follower_link_color',
			'twitter_follower_count',
			'twitter_following_count',
			'twitter_tweets_count',
			'twitter_last_tweet_likes_count',
			'twitter_last_tweet_retweets_count',
			'twitter_last_retweeter_username',
			'twitter_last_retweeter_id',
			'twitter_last_retweeter_avatar',
			'twitter_last_retweeter_tweet',
			'twitter_last_retweeter_background_color',
			'twitter_last_retweeter_link_color',
		],
		alerts: {
			follower: ['username', 'userId', 'displayname', 'avatar', 'followers'],
			like: ['value', 'likes'],
			retweet: [
				'retweets',
				'avatar',
				'username',
				'userId',
				'displayname',
				'banner',
				'profile_background_color',
				'profile_link_color',
				'user_followers',
				'user_likes',
				'is_following',
				'following_count',
				'verified',
				'private',
			],
		},
	},
	vlc: {
		variables: ['vlc_now_playing_media', 'vlc_now_playing_image', 'vlc_now_playing_id', 'vlc_now_playing_artist', 'vlc_now_playing_uri', 'vlc_now_playing_url'],
		alerts: {
			switchSong: ['name', 'uri', 'image'],
			songPlayed: ['name', 'uri', 'image'],
			songPaused: ['name', 'uri', 'image'],
		},
	},
	voicemod: {
		variables: ['voicemod_voice_changer_on', 'voicemod_previous_voice', 'voicemod_current_voice'],
	},
	vtubestudio: {
		variables: ['vtubestudio_current_model', 'vtubestudio_current_background', 'vtubestudio_last_hotkey_triggered'],
		alerts: {
			hotkeyTriggered: ['name', 'modelName', 'modelId'],
			modelLoaded: ['name', 'modelName', 'modelId'],
			animationStart: ['name', 'modelName', 'modelId', 'animationName', 'animationLength'],
			animationEnd: ['name', 'modelName', 'modelId', 'animationName', 'animationLength'],
			itemAdded: ['name'],
			itemRemoved: ['name'],
			backgroundChanged: ['name'],
		},
	},
	woocommerce: {
		variables: [
			'woocommerce_last_order_name',
			'woocommerce_last_order_first_name',
			'woocommerce_last_order_last_name',
			'woocommerce_last_order_items',
			'woocommerce_last_order_item',
			'woocommerce_last_order_amount',
			'woocommerce_last_order_amount_currency',
		],
		alerts: {
			order: [],
		},
	},
	youtube: {
		variables: [
			'youtube_uptime',
			'youtube_live',
			'youtube_session_chat_count',
			'youtube_current_first_chatter',
			'youtube_current_first_chatter_count',
			'youtube_previous_first_chatter',
			'youtube_previous_first_chatter_count',
			'youtube_last_chatter',
			'youtube_session_subscriber_count',
			'youtube_total_subscriber_count',
			'youtube_session_superchat_count',
			'youtube_last_superchatter',
			'youtube_session_superchatters',
			'youtube_session_supersticker_count',
			'youtube_last_supersticker',
			'youtube_session_superstickers',
			'youtube_total_member_count',
			'youtube_session_member_count',
			'youtube_last_member',
			'youtube_session_members',
			'youtube_last_subscriber',
			'youtube_total_video_count',
			'youtube_total_view_count',
		],
		alerts: {
			streamLive: ['eventTime'],
			streamOffline: [],
			firstChatter: ['username', 'displayname', 'userId', 'avatar', 'first_count', 'message'],
			entrance: ['username', 'displayname', 'userId', 'avatar', 'message'],
			subscriber: ['username', 'displayname', 'avatar', 'userId'],
			member: ['username', 'displayname', 'avatar', 'tier', 'subMonths', 'streakMonths', 'message', 'subPlan', 'subPlanName'],
			superchat: ['username', 'displayname', 'currency', 'amount', 'message'],
			supersticker: ['username', 'displayname', 'amount'],
		},
	},
	youtubemusic: {
		variables: [
			'youtubemusic_now_playing_song',
			'youtubemusic_now_playing_image',
			'youtubemusic_now_playing_id',
			'youtubemusic_now_playing_artist',
			'youtubemusic_now_playing_url',
			'youtubemusic_next_song',
			'youtubemusic_next_image',
			'youtubemusic_next_artist',
			'youtubemusic_next_id',
			'youtubemusic_next_url',
			'youtubemusic_queue',
		],
		alerts: {
			switchSong: [
				'youtubemusic_now_playing_song',
				'youtubemusic_now_playing_image',
				'youtubemusic_now_playing_id',
				'youtubemusic_now_playing_artist',
				'youtubemusic_now_playing_url',
				'youtubemusic_next_song',
				'youtubemusic_next_image',
				'youtubemusic_next_artist',
				'youtubemusic_next_id',
				'youtubemusic_next_url',
				'youtubemusic_queue',
			],
			songPlayed: [
				'youtubemusic_now_playing_song',
				'youtubemusic_now_playing_image',
				'youtubemusic_now_playing_id',
				'youtubemusic_now_playing_artist',
				'youtubemusic_now_playing_url',
				'youtubemusic_next_song',
				'youtubemusic_next_image',
				'youtubemusic_next_artist',
				'youtubemusic_next_id',
				'youtubemusic_next_url',
				'youtubemusic_queue',
			],
			songPaused: [
				'youtubemusic_now_playing_song',
				'youtubemusic_now_playing_image',
				'youtubemusic_now_playing_id',
				'youtubemusic_now_playing_artist',
				'youtubemusic_now_playing_url',
				'youtubemusic_next_song',
				'youtubemusic_next_image',
				'youtubemusic_next_artist',
				'youtubemusic_next_id',
				'youtubemusic_next_url',
				'youtubemusic_queue',
			],
		},
	},
};
