export const YoutubeSuperstickersData = [
	{
		value: 'pearfect_hey_you_ja_v2',
		label: "Pear character turning around waving his hand, saying 'Hey you' while lowering his glasses",
		amount: '2.00',
		currency: 'USD',
		helperText: '$2.00',
		imageUrl: 'https://lh3.googleusercontent.com/zVG21MhHLyNs7q9oGcMX6KPybyjiur3tFoG3mybnmgmrcRqiX86OPjwvPfpURWDNuWiZ3Elv7okHZkjKnQ',
		searchText: "pearfect_hey_you_ja_v2 Pear character turning around waving his hand, saying 'Hey you' while lowering his glasses 2.00 USD",
	},
	{
		value: 'pearfect_cool_ja_v2',
		label: "Pear character doing a shaka sign with his hand saying 'Cool'",
		amount: '2.00',
		currency: 'USD',
		helperText: '$2.00',
		imageUrl: 'https://lh3.googleusercontent.com/95qZ1PbzSWF5tEV0cZXSH0zhPCE9HeYLgshe0TvG-aREbhybDzpq3Yo0rXojATP3i4Q4XV61wE6CB9Q1kk0',
		searchText: "pearfect_cool_ja_v2 Pear character doing a shaka sign with his hand saying 'Cool' 2.00 USD",
	},
	{
		value: 'pearfect_blush_v2',
		label: 'Pear character putting his hand in front of his mouth while blushing',
		amount: '2.00',
		currency: 'USD',
		helperText: '$2.00',
		imageUrl: 'https://lh3.googleusercontent.com/ifw1vqdg4sLzlUg0FDlanS3aMp-O3huw_qZItKWZo-00mIqTt7r6XdaFxcIJcAb70RHkd14uTl_JPkXcFg',
		searchText: 'pearfect_blush_v2 Pear character putting his hand in front of his mouth while blushing 2.00 USD',
	},
	{
		value: 'pearfect_fist_bump_ja_v2',
		label: "Pear character punching the air with 'Fist' and 'Bump' written on his knuckles",
		amount: '3.00',
		currency: 'USD',
		helperText: '$3.00',
		imageUrl: 'https://lh3.googleusercontent.com/sH0b0RsjOYPLCWeiJEMx0Otf7xmOaAHDpF-GN9Dts4McdXo5_64M31zCxptE3JwfKyOaipew-v4I0T4bpQ',
		searchText: "pearfect_fist_bump_ja_v2 Pear character punching the air with 'Fist' and 'Bump' written on his knuckles 3.00 USD",
	},
	{
		value: 'pearfect_thumbs_up_v2',
		label: 'Pear character stretching his arm forward raising his thumb up',
		amount: '3.00',
		currency: 'USD',
		helperText: '$3.00',
		imageUrl: 'https://lh3.googleusercontent.com/y4t53UFh4eWO9FmuXgELtXn0cWsZEAJOWCExbumx2vcNclm2VYJkd4Omo7lKLxOg78zaXBmukrN0ONPRDwM',
		searchText: 'pearfect_thumbs_up_v2 Pear character stretching his arm forward raising his thumb up 3.00 USD',
	},
	{
		value: 'pearfect_blowing_hearts_v2',
		label: 'Pear character with lovey dovey eyes blowing red hearts in the air',
		amount: '3.00',
		currency: 'USD',
		helperText: '$3.00',
		imageUrl: 'https://lh3.googleusercontent.com/aQTC6r0gjuns5TwJTMoA_mqOH3mizXxzlAJqh_CpLx8lWyKiUgS_EjTATRTX0Qzm8MlZyXAg7r6kFzlH8HgS',
		searchText: 'pearfect_blowing_hearts_v2 Pear character with lovey dovey eyes blowing red hearts in the air 3.00 USD',
	},
	{
		value: 'pearfect_offer_coffee_v2',
		label: 'Pear character exaggeratedly stretching his arm forward to offer a cup of coffee',
		amount: '4.00',
		currency: 'USD',
		helperText: '$4.00',
		imageUrl: 'https://lh3.googleusercontent.com/agY5_IS-HWYMQiU6TrnmjVS74Lq241PS45M6-TqnnE0JxPiM9I4Qx5HEWDpF3bjLrywcrV3e2le-KYkGo3E',
		searchText: 'pearfect_offer_coffee_v2 Pear character exaggeratedly stretching his arm forward to offer a cup of coffee 4.00 USD',
	},
	{
		value: 'pearfect_lol_ja_v2',
		label: 'Pear character holding his belly laughing out loud',
		amount: '5.00',
		currency: 'USD',
		helperText: '$5.00',
		imageUrl: 'https://lh3.googleusercontent.com/ml-E_opQwbQZvcG5EkfMdXHCVFx9R7-z4BUgRQawoW02VPBsw3sHTfKdATtK9figDnbJZsNH_egFKca4TQ',
		searchText: 'pearfect_lol_ja_v2 Pear character holding his belly laughing out loud 5.00 USD',
	},
	{
		value: 'pearfect_hows_it_going_ja_v2',
		label: "Pear character lying on the side, raising his arm while saying 'How's it going?'",
		amount: '5.00',
		currency: 'USD',
		helperText: '$5.00',
		imageUrl: 'https://lh3.googleusercontent.com/wszUk8nXUAEZq7oh_ukoF1alcqB5eJDGJlCVHeKiDfVAPMUfi9uIvXLLfLFON91-Snl3s8be4ihhrPA07cg',
		searchText: "pearfect_hows_it_going_ja_v2 Pear character lying on the side, raising his arm while saying 'How's it going?' 5.00 USD",
	},
	{
		value: 'pearfect_horn_v2',
		label: 'Pear character cheerfully blowing a party horn',
		amount: '5.00',
		currency: 'USD',
		helperText: '$5.00',
		imageUrl: 'https://lh3.googleusercontent.com/GBmHK4z49AGnV2T1fmdcuwRQXRJ-Z4-_-qtypUTTjP8r_VXBs7wisr-L0rmHloa5gYPHF6kbPl_zyYCoAJo',
		searchText: 'pearfect_horn_v2 Pear character cheerfully blowing a party horn 5.00 USD',
	},
	{
		value: 'pearfect_mic_drop_v2',
		label: 'Pear character doing a classic mic drop',
		amount: '5.00',
		currency: 'USD',
		helperText: '$5.00',
		imageUrl: 'https://lh3.googleusercontent.com/1bDFA_G_SRs2Jr5zwOgTvRVf3pRyhS1Xf8dOMtUz8A2r4AI8kcBQMlnW1EP6EjtrCM8o4xCiaAFDpKjvXHo',
		searchText: 'pearfect_mic_drop_v2 Pear character doing a classic mic drop 5.00 USD',
	},
	{
		value: 'pearfect_keep_it_up_ja_v2',
		label: "Pear character lifting some weights saying 'Keep it up'",
		amount: '5.00',
		currency: 'USD',
		helperText: '$5.00',
		imageUrl: 'https://lh3.googleusercontent.com/bPTouaCakCIoX_TCIrCLpUeybslbvoIUdQcu6B9jjFG-JHpLb31gWkSS5voAc2LdwtC04vmJHTaQWPYRBQ',
		searchText: "pearfect_keep_it_up_ja_v2 Pear character lifting some weights saying 'Keep it up' 5.00 USD",
	},
	{
		value: 'pearfect_flying_v2',
		label: 'Pear character flying in the air with a red cape and a smile on his face',
		amount: '10.00',
		currency: 'USD',
		helperText: '$10.00',
		imageUrl: 'https://lh3.googleusercontent.com/oUIeg07YsvEuUcF7wOg6U3o1dOCANoBWuF1DYr2jGPFOyQ-bEFRiFm-6gU3urJPaX_AqtZgsNpGb0KNimA',
		searchText: 'pearfect_flying_v2 Pear character flying in the air with a red cape and a smile on his face 10.00 USD',
	},
	{
		value: 'pearfect_number_1_fan_ja_v2',
		label: "Pear character jumping up and down saying '#1 Fan'",
		amount: '10.00',
		currency: 'USD',
		helperText: '$10.00',
		imageUrl: 'https://lh3.googleusercontent.com/uJx7Q9Kn9EGwX96OCDDGq3dYF1fsjyy0C1XDOZO6IbQ-is3EdUHZvSciVWPB5Tjy2knro1OzecFOd_lSwCE',
		searchText: "pearfect_number_1_fan_ja_v2 Pear character jumping up and down saying '#1 Fan' 10.00 USD",
	},
	{
		value: 'pearfect_thank_you_ja_v2',
		label: "Pear character bowing down saying 'Thank you'",
		amount: '10.00',
		currency: 'USD',
		helperText: '$10.00',
		imageUrl: 'https://lh3.googleusercontent.com/q2B3qN0DPbw091ufds_crhFMbkieqTSOUSI1_UsPIecZSAW7uFsm6_ecsGfqUDXLrDv52Tk-K1rTsSQWfFgk',
		searchText: "pearfect_thank_you_ja_v2 Pear character bowing down saying 'Thank you' 10.00 USD",
	},
	{
		value: 'pearfect_rofl',
		label: 'Pear character rolling on the floor laughing',
		amount: '10.00',
		currency: 'USD',
		helperText: '$10.00',
		imageUrl: 'https://lh3.googleusercontent.com/17N6PxLsKivyMFACXsTv2JWKOZrz65pbsymeQkSEDMrDOhg2gWYaJrXlicl9eRAQ4OV14Yha5JP_0knz4lYQ',
		searchText: 'pearfect_rofl Pear character rolling on the floor laughing 10.00 USD',
	},
	{
		value: 'pearfect_goal_ja_v2',
		label: 'Pear character sliding on the floor on his knees saying "GOAL"',
		amount: '20.00',
		currency: 'USD',
		helperText: '$20.00',
		imageUrl: 'https://lh3.googleusercontent.com/ou-NArsokwtxbK7vYe87kurItzctKziTLGhlKH5b5Yh574zpnAB78CxMfG4kqxwAKXFy8eSpKCy536egnw',
		searchText: 'pearfect_goal_ja_v2 Pear character sliding on the floor on his knees saying "GOAL" 20.00 USD',
	},
	{
		value: 'pearfect_thanks_heart_mirror_ja_v2',
		label: "Pear character looking at himself in the mirror, saying 'Thanks for being you' with hearts popping out of his eyes",
		amount: '20.00',
		currency: 'USD',
		helperText: '$20.00',
		imageUrl: 'https://lh3.googleusercontent.com/ea1gScbZ4QM2_jwqUPEsmKvALfjCkQT-hnytuHw_IBDPT0THu0oQ-x7kawhBsYsKLTAEDStR5EG6Vod7E2w',
		searchText: "pearfect_thanks_heart_mirror_ja_v2 Pear character looking at himself in the mirror, saying 'Thanks for being you' with hearts popping out of his eyes 20.00 USD",
	},
	{
		value: 'pearfect_you_are_amazing_ja_v2',
		label: "Pear character dancing under a rain of confetti and taking his hat off to say 'You are amazing'",
		amount: '20.00',
		currency: 'USD',
		helperText: '$20.00',
		imageUrl: 'https://lh3.googleusercontent.com/GIgOjJ-v3k5vQgXbjfTspXkroXtWnWPIVYe1zSBanlow0jpQbe48BTUZHjlkGiGiNqfZBLPhjr3yzYU8yfjn',
		searchText: "pearfect_you_are_amazing_ja_v2 Pear character dancing under a rain of confetti and taking his hat off to say 'You are amazing' 20.00 USD",
	},
	{
		value: 'pearfect_building_riot_v2',
		label: 'Giant Pear character waving flags and turning around, making the buildings in front of him tremble',
		amount: '50.00',
		currency: 'USD',
		helperText: '$50.00',
		imageUrl: 'https://lh3.googleusercontent.com/PQlPxOdeVk_oY3D_Ow0JRXvV3AbVIEoApzvenbfgsAHoLF4_EgxCV7Dsd-kqMsCAqhHhNG0vUY2Ssoa03iW_',
		searchText: 'pearfect_building_riot_v2 Giant Pear character waving flags and turning around, making the buildings in front of him tremble 50.00 USD',
	},
	{
		value: 'pearfect_ride_rocket_explode',
		label: 'Pear character riding a firework rocket disappearing away before bursting in the sky',
		amount: '50.00',
		currency: 'USD',
		helperText: '$50.00',
		imageUrl: 'https://lh3.googleusercontent.com/acEg1wXa4J4aifq3jYum0I6H9QwSmQDkSdiFe4W9sWSqYPbCnkzBybpdO-gjqiN6mirUrEHfojY2_7fO-w',
		searchText: 'pearfect_ride_rocket_explode Pear character riding a firework rocket disappearing away before bursting in the sky 50.00 USD',
	},
	{
		value: 'hi_po_po_1up',
		label: 'A pixelated hippo chomps on a 1up',
		amount: '2.00',
		currency: 'USD',
		helperText: '$2.00',
		imageUrl: 'https://lh3.googleusercontent.com/uvDsxVrGmXBek8mI088npeMakgaPMDkI8tYbi4EyDIK3RJHL5VSRPeyrfqrpNfEv7dSa4p23A8W8qqX4gw',
		searchText: 'hi_po_po_1up A pixelated hippo chomps on a 1up 2.00 USD',
	},
	{
		value: 'hi_po_po_game_over_v2',
		label: "A ghost of our hippo character floats in front of the words 'Game Over'",
		amount: '2.00',
		currency: 'USD',
		helperText: '$2.00',
		imageUrl: 'https://lh3.googleusercontent.com/KyHZmpHIrAEiSo5FGJGp-gnDbNEJz3U5vO7vYKdHUv1oSHWKn1sipA5vBHP8n7ProW5CSNFCiEKGj9K61w',
		searchText: "hi_po_po_game_over_v2 A ghost of our hippo character floats in front of the words 'Game Over' 2.00 USD",
	},
	{
		value: 'hi_po_po_next_time_v2',
		label: "Hippo character waves goodbye with the words 'Next Time' behind him",
		amount: '3.00',
		currency: 'USD',
		helperText: '$3.00',
		imageUrl: 'https://lh3.googleusercontent.com/cNaxv7eSqrGD9zbUv1jxhuqmv1Q-t2bdaaDnsRr0xvUS1YI0JnNyMLwYmEvC1MiZubVZ6w3qWb3E9yHWYg',
		searchText: "hi_po_po_next_time_v2 Hippo character waves goodbye with the words 'Next Time' behind him 3.00 USD",
	},
	{
		value: 'hi_po_po_pilot_gesture',
		label: 'Hippo character in tactical gear does tactical flanking maneuver hand gestures',
		amount: '3.00',
		currency: 'USD',
		helperText: '$3.00',
		imageUrl: 'https://lh3.googleusercontent.com/1ZS94gQL-0F2yb47ZBEgfB78L-tMl9_Ktm45OSJx5Fo9NumzpdGHMtQSVHC0iiM5hiIoRXmUrRVhdTKfJQ',
		searchText: 'hi_po_po_pilot_gesture Hippo character in tactical gear does tactical flanking maneuver hand gestures 3.00 USD',
	},
	{
		value: 'hi_po_po_collar_tug',
		label: 'Hippo character waves his hand in front of his neck with an awkward look on his face to signal that the player is done',
		amount: '4.00',
		currency: 'USD',
		helperText: '$4.00',
		imageUrl: 'https://lh3.googleusercontent.com/iJcZ-EA1rMLLoFBTMwXk0UsRqKy4mk8-5rJbQRlE4XaIelJrHbR2uOW8OPrjkG41Cx_HsxRxQmhsHCO0sn_J',
		searchText: 'hi_po_po_collar_tug Hippo character waves his hand in front of his neck with an awkward look on his face to signal that the player is done 4.00 USD',
	},
	{
		value: 'hi_po_po_omg',
		label: 'Hippo character smacks his hands onto his face and looks around to see if anyone saw what he just saw',
		amount: '4.00',
		currency: 'USD',
		helperText: '$4.00',
		imageUrl: 'https://lh3.googleusercontent.com/L7_s1loXw0cmMPDcuDTK8j6PhRLWNyn0vroF83gGXzBcTtm0pK1TuusTxntz09xv_IZYWYhElHfBKKU3dIo',
		searchText: 'hi_po_po_omg Hippo character smacks his hands onto his face and looks around to see if anyone saw what he just saw 4.00 USD',
	},
	{
		value: 'hi_po_po_hype_v2',
		label: "Hippo character with stars growing in his eyes, pumping his arms in the air with the word 'Hype' pulsating above him",
		amount: '5.00',
		currency: 'USD',
		helperText: '$5.00',
		imageUrl: 'https://lh3.googleusercontent.com/Vx6cJUqDuX3R-fTg2TP3So9-lgkLJ6oRoIVeGill4ehleBUo5I_k-8hSc2lItnZuQN8aLusBj8pwQ_ZlFsI',
		searchText: "hi_po_po_hype_v2 Hippo character with stars growing in his eyes, pumping his arms in the air with the word 'Hype' pulsating above him 5.00 USD",
	},
	{
		value: 'hi_po_po_git_gud_v2',
		label: "Hippo character repeatedly points to the streamer while chanting 'Git Gud'",
		amount: '5.00',
		currency: 'USD',
		helperText: '$5.00',
		imageUrl: 'https://lh3.googleusercontent.com/QmBlswgp9muf5gMV2ZaRrFQDtj0g2JWWmiAiGDq4pbcCSK2KmK1XJprtgo2DxhElmEMRm__A6l68_jcSIw',
		searchText: "hi_po_po_git_gud_v2 Hippo character repeatedly points to the streamer while chanting 'Git Gud' 5.00 USD",
	},
	{
		value: 'hi_po_po_gg',
		label: 'Hippo character applauds whilst nodding in approval, saying ‘GG’',
		amount: '5.00',
		currency: 'USD',
		helperText: '$5.00',
		imageUrl: 'https://lh3.googleusercontent.com/rUbx-Dfxq-jxzhmpjgx8UzYxIlZ03ri3DIrK9yI1LlG5ICd3dboM2B0jByVWg0ln38ZoneBBj7ChcVJntjs',
		searchText: 'hi_po_po_gg Hippo character applauds whilst nodding in approval, saying ‘GG’ 5.00 USD',
	},
	{
		value: 'hi_po_po_running_fast_v2',
		label: 'Hippo character runs at high speed, his legs forming a ball-like blur',
		amount: '5.00',
		currency: 'USD',
		helperText: '$5.00',
		imageUrl: 'https://lh3.googleusercontent.com/w100I3enX3ZDjr0pW7TynDApLdaXNFVf1SYu8tklSQoeZpQDg3WNJzsQV6yTu3Tyg8PifKyouRCCXi44rviL',
		searchText: 'hi_po_po_running_fast_v2 Hippo character runs at high speed, his legs forming a ball-like blur 5.00 USD',
	},
	{
		value: 'hi_po_po_squad',
		label: "Hippo character's head pops out of water, surounded by his hippo squad",
		amount: '5.00',
		currency: 'USD',
		helperText: '$5.00',
		imageUrl: 'https://lh3.googleusercontent.com/iaXFY_xpmoEytuxknC0M0UyO8tE1QKkHhaNZfnySUeL2zLV5HFlAkj7SBIK3FIc6kGSs_MvL2gBiPGuqONc',
		searchText: "hi_po_po_squad Hippo character's head pops out of water, surounded by his hippo squad 5.00 USD",
	},
	{
		value: 'hi_po_po_chair_spin_yay',
		label: 'Hippo character spins around in his chair, arms flung up in the air',
		amount: '10.00',
		currency: 'USD',
		helperText: '$10.00',
		imageUrl: 'https://lh3.googleusercontent.com/8V2odx-XA6xpmVbMVEh7k1qRIHMucDYxyuC5gIIFEWWHMbWodVxSJoO9LuuII_b-mXOC8Ero0PqeOrVmDZU',
		searchText: 'hi_po_po_chair_spin_yay Hippo character spins around in his chair, arms flung up in the air 10.00 USD',
	},
	{
		value: 'hi_po_po_ko_uppercut_v2',
		label: "Hippo character throwing a blazing upper cut into the air while the word 'KO' appears in the background",
		amount: '10.00',
		currency: 'USD',
		helperText: '$10.00',
		imageUrl: 'https://lh3.googleusercontent.com/ietADCHfxmlGd1FfSq57UWQ8FxKRamqy-ElRHrIOGY7TFU08fUuFfGGOwqWQHlDS1V7CckN2TrTrkHdHQ0jX',
		searchText: "hi_po_po_ko_uppercut_v2 Hippo character throwing a blazing upper cut into the air while the word 'KO' appears in the background 10.00 USD",
	},
	{
		value: 'hi_po_po_chair_drift',
		label: 'Hippo character going really fast on his chair, propelling the chair across the room',
		amount: '10.00',
		currency: 'USD',
		helperText: '$10.00',
		imageUrl: 'https://lh3.googleusercontent.com/wJ5ljiOSGqI641C2m1j98_Z6OSjTSU3gx04j9LC9pzm6HpClIVum533QMTZfyZXrgXeyFO9MaRQsF5mKXTo',
		searchText: 'hi_po_po_chair_drift Hippo character going really fast on his chair, propelling the chair across the room 10.00 USD',
	},
	{
		value: 'hi_po_po_rekt_v2',
		label: "Hippo character collapses to the ground as his chair breaks, while the words 'REKT' appear above him",
		amount: '10.00',
		currency: 'USD',
		helperText: '$10.00',
		imageUrl: 'https://lh3.googleusercontent.com/bo6h7VZLtDCkoZUItEk94QADjBYxmW09kF_PKvX0dy-htiJgKlUNH_1_otyMjAHFow3rHVz1h--88-Il_HI',
		searchText: "hi_po_po_rekt_v2 Hippo character collapses to the ground as his chair breaks, while the words 'REKT' appear above him 10.00 USD",
	},
	{
		value: 'hi_po_po_backwards_hat_thumbs_up_v2',
		label: 'Hippo character with a pink hat, flips it backward and raises his thumb up in the air',
		amount: '10.00',
		currency: 'USD',
		helperText: '$10.00',
		imageUrl: 'https://lh3.googleusercontent.com/dASeTly1tLj23IX49gupPGn44wqagvu8z37YGLDl01cjGHuqr6e3o_NK79p7pqyVaddIGGQ3mumgVRKsxAg',
		searchText: 'hi_po_po_backwards_hat_thumbs_up_v2 Hippo character with a pink hat, flips it backward and raises his thumb up in the air 10.00 USD',
	},
	{
		value: 'hi_po_po_op_v2',
		label: "Hippo character stands idle whilst his new and most powerful body attachments do their thing, with the word 'OP' in the background",
		amount: '20.00',
		currency: 'USD',
		helperText: '$20.00',
		imageUrl: 'https://lh3.googleusercontent.com/gTfgFlj4u1_9WfH618ZQpM3_eXR2e6h5hlm8Kt31hYNyl8479-QCnRD6ep8LLW1UI8b5lm2ancI8zDyz3JI',
		searchText: "hi_po_po_op_v2 Hippo character stands idle whilst his new and most powerful body attachments do their thing, with the word 'OP' in the background 20.00 USD",
	},
	{
		value: 'hi_po_po_victory_v2',
		label: "Hippo character flips around and does a V sign with his hand while the word 'Victory' appears in the background",
		amount: '20.00',
		currency: 'USD',
		helperText: '$20.00',
		imageUrl: 'https://lh3.googleusercontent.com/vioxl6BlYVnevbMDkhU3FYxt-TkP16NxvvhryFpY20oSTmIUVgwD2atk10KMtJ8RpePh1CTGYkIZHKeQFQ',
		searchText: "hi_po_po_victory_v2 Hippo character flips around and does a V sign with his hand while the word 'Victory' appears in the background 20.00 USD",
	},
	{
		value: 'hi_po_po_epic_fail_v2',
		label: "Hippo character falling to the ground in a dramatic way, bursting into tears with the words 'Epic Fail' in the background",
		amount: '20.00',
		currency: 'USD',
		helperText: '$20.00',
		imageUrl: 'https://lh3.googleusercontent.com/TNVPEaEXpMM2NHqGMtPYlEZT4xFY3KtrRCxyszKC4Jw1-k0FSj-gROrhd6bXDBYdMw8z0PHj52qvXQUtYg',
		searchText: "hi_po_po_epic_fail_v2 Hippo character falling to the ground in a dramatic way, bursting into tears with the words 'Epic Fail' in the background 20.00 USD",
	},
	{
		value: 'hi_po_po_tossing_money',
		label: 'Hippo character wearing cool sunglasses comes out of a treasure chest tossing coins around him',
		amount: '50.00',
		currency: 'USD',
		helperText: '$50.00',
		imageUrl: 'https://lh3.googleusercontent.com/zrHmOt7yfHtHlfpZGp7UNPJjKHsW_Kfo_uJ0OE7TXL7bofch96Fvf0ryTbE0iBRoIrL3tcY4ubXa0QMDEKgl',
		searchText: 'hi_po_po_tossing_money Hippo character wearing cool sunglasses comes out of a treasure chest tossing coins around him 50.00 USD',
	},
	{
		value: 'hi_po_po_mecha_transform_v2',
		label: 'Hippo character sitting into an office chair, when they both transform into a mecha chair / hippo hero',
		amount: '50.00',
		currency: 'USD',
		helperText: '$50.00',
		imageUrl: 'https://lh3.googleusercontent.com/BhLcBLpuQ1R5H9WKAXsoQTgrqKU3azJLeSS1uwYm4jJK2HCdbOjVrld9EFUAWT9OWd_EKgWovO4GrbBGLQ',
		searchText: 'hi_po_po_mecha_transform_v2 Hippo character sitting into an office chair, when they both transform into a mecha chair / hippo hero 50.00 USD',
	},
	{
		value: 'bushiba_heart_wobble',
		label: 'Shiba dog shaking his body from left to right, surrounded by red hearts',
		amount: '2.00',
		currency: 'USD',
		helperText: '$2.00',
		imageUrl: 'https://lh3.googleusercontent.com/whWdCHvpK52qWkxadxxRiATHijar8KkJZCHtmwa3KeLyzf1hT3jqIGKE5FTJvvrmWWxneg1CGQ7VuQ624HKy',
		searchText: 'bushiba_heart_wobble Shiba dog shaking his body from left to right, surrounded by red hearts 2.00 USD',
	},
	{
		value: 'bushiba_head_tilt',
		label: 'Shiba dog with a big smile on his face, tilting his head',
		amount: '2.00',
		currency: 'USD',
		helperText: '$2.00',
		imageUrl: 'https://lh3.googleusercontent.com/HCflKXDsNb70vxZTcfZEugWY7Tq66Y4nrLJ_qjWYssFWvv9GnH5MxulV2n7dPEbKYDzrFmv1vU3eVInAHAE',
		searchText: 'bushiba_head_tilt Shiba dog with a big smile on his face, tilting his head 2.00 USD',
	},
	{
		value: 'bushiba_number_one',
		label: 'Shiba dog raises and lowers his index finger to get noticed',
		amount: '2.00',
		currency: 'USD',
		helperText: '$2.00',
		imageUrl: 'https://lh3.googleusercontent.com/1aIk6vlk4gZ2ytc42j3WcIHYtWFWo2uVWVqbHFuxiGHO4XwyAS0u8vuu6VkiX5eR6uy9mfAupyP786_TbP0',
		searchText: 'bushiba_number_one Shiba dog raises and lowers his index finger to get noticed 2.00 USD',
	},
	{
		value: 'bushiba_greeting',
		label: "Shiba dog raising an arm to greet someone, asking 'How is it going?'",
		amount: '3.00',
		currency: 'USD',
		helperText: '$3.00',
		imageUrl: 'https://lh3.googleusercontent.com/8F7hderXhK12c3IsdFH9IkL0o7yZ8QoJv1AnXzbXbWfcLksDtZSaGVkI6jxjJ4TsBsORo-LUl82n0DdWnmRE',
		searchText: "bushiba_greeting Shiba dog raising an arm to greet someone, asking 'How is it going?' 3.00 USD",
	},
	{
		value: 'bushiba_goodbye',
		label: 'Shiba dog moves his arm saying goodbye',
		amount: '3.00',
		currency: 'USD',
		helperText: '$3.00',
		imageUrl: 'https://lh3.googleusercontent.com/SMDbzpXw5_J59DGzHlDt7wFvh845sOBFSnOWevAi5AjLIY5ilT8Kjma9cHPAI3wglAvAsa7c10x6aBmVaQ',
		searchText: 'bushiba_goodbye Shiba dog moves his arm saying goodbye 3.00 USD',
	},
	{
		value: 'bushiba_massage_cheeks',
		label: 'Shiba dog happily massaging his cheeks with his mouth wide open',
		amount: '3.00',
		currency: 'USD',
		helperText: '$3.00',
		imageUrl: 'https://lh3.googleusercontent.com/YdmPA_ww8jo-N_boZLrAmMm3jG6tSvgVFj1a7IAaLqL4l0wbUfzJm3QHQJr8PWsLdy9rq5XwMslVx6gfEg',
		searchText: 'bushiba_massage_cheeks Shiba dog happily massaging his cheeks with his mouth wide open 3.00 USD',
	},
	{
		value: 'bushiba_hero',
		label: "Shiba dog with sparkles in his eyes saying 'My hero'",
		amount: '3.00',
		currency: 'USD',
		helperText: '$3.00',
		imageUrl: 'https://lh3.googleusercontent.com/jnqWW1Fxf_BbuAtFnLSsIVlTc-SOU9U8KxHSmIuEAEniFEm7smRYGP02nqeaLV6HsdQtZxGzdiMAF34rzw',
		searchText: "bushiba_hero Shiba dog with sparkles in his eyes saying 'My hero' 3.00 USD",
	},
	{
		value: 'bushiba_bone_bow',
		label: 'Shiba dog gifting a large bone, bowing respectfully',
		amount: '4.00',
		currency: 'USD',
		helperText: '$4.00',
		imageUrl: 'https://lh3.googleusercontent.com/61vwa6NIdGiGqcnUfvSNjlfqxom58Y-ZG_AVq2o4rovdPIq458ijTL8_vMdY6wt6ZhKtvoBES7AMk1d6HQ',
		searchText: 'bushiba_bone_bow Shiba dog gifting a large bone, bowing respectfully 4.00 USD',
	},
	{
		value: 'bushiba_blush_laugh',
		label: 'Shiba dog laughing slightly while blushing and covering his mouth with one arm',
		amount: '5.00',
		currency: 'USD',
		helperText: '$5.00',
		imageUrl: 'https://lh3.googleusercontent.com/eTGUUs4igdOaNmgQZXIbKyBtMxExjnZYErNb-L9ih8yDOPtaGA_I1jQIVMbmvYaUQ-mlgUTVymBGTtUWC0k',
		searchText: 'bushiba_blush_laugh Shiba dog laughing slightly while blushing and covering his mouth with one arm 5.00 USD',
	},
	{
		value: 'bushiba_bow',
		label: 'Shiba dog bowing respectfully',
		amount: '5.00',
		currency: 'USD',
		helperText: '$5.00',
		imageUrl: 'https://lh3.googleusercontent.com/xI8walHhVGsLeMUSDY5eTPmUPmkypApw_vIsvm8jQnM-Le-MNXY5xktkzUhGofXDoyPJnQhYgNLtxpLxAGo',
		searchText: 'bushiba_bow Shiba dog bowing respectfully 5.00 USD',
	},
	{
		value: 'bushiba_clapping',
		label: 'Shiba dog clapping his hands',
		amount: '5.00',
		currency: 'USD',
		helperText: '$5.00',
		imageUrl: 'https://lh3.googleusercontent.com/qUL5j6d0fw7vRxVjNGWspPBtE_m71Nkbe9baHIMiMrQzlueLBYw_ReleYcWamTb0hsgkQiIbYkoC3IshxfU',
		searchText: 'bushiba_clapping Shiba dog clapping his hands 5.00 USD',
	},
	{
		value: 'bushiba_hey_you',
		label: "Shiba dog saying 'Hey you', greeting joyfully",
		amount: '5.00',
		currency: 'USD',
		helperText: '$5.00',
		imageUrl: 'https://lh3.googleusercontent.com/UdMuIslpZlaMoVq6ob0cthXH-3QBLic56gJtLq-3O7CNcMVlEEJbk5D6DuqatsxsNr8I-MC0pZ7j2mSjcn8',
		searchText: "bushiba_hey_you Shiba dog saying 'Hey you', greeting joyfully 5.00 USD",
	},
	{
		value: 'bushiba_combat',
		label: 'Shiba dog in a combat position',
		amount: '5.00',
		currency: 'USD',
		helperText: '$5.00',
		imageUrl: 'https://lh3.googleusercontent.com/yqdaRISXob65yQDzbTpy9G4SNmTGyuOd-mqwWsosQCF3Sse-pWN6GJmvA2Cuwt9qYcQXkZo_vMlUumv6Iqs5',
		searchText: 'bushiba_combat Shiba dog in a combat position 5.00 USD',
	},
	{
		value: 'bushiba_number_one_paper',
		label: "Shiba dog writing with a brush, writing 'Number 1' on a piece of paper",
		amount: '5.00',
		currency: 'USD',
		helperText: '$5.00',
		imageUrl: 'https://lh3.googleusercontent.com/mfL84W0tX_w0hVYMkues-i_a03JIMRGIyoAeFHH7cJWb5ICs-rCznR_6xCMFmYquhEidcNx8It2cxHPTmg',
		searchText: "bushiba_number_one_paper Shiba dog writing with a brush, writing 'Number 1' on a piece of paper 5.00 USD",
	},
	{
		value: 'bushiba_thumbs_up',
		label: "Shiba dog saying 'Good job' while raising his thumb up",
		amount: '5.00',
		currency: 'USD',
		helperText: '$5.00',
		imageUrl: 'https://lh3.googleusercontent.com/EtOr1BR303TkjD8bMKiPYY0wPNI92vMxu5Wjx8i5Pn6mYxpn7TYPToNdn0II-qgUnC52e9VeSgCrLaNvrk8C',
		searchText: "bushiba_thumbs_up Shiba dog saying 'Good job' while raising his thumb up 5.00 USD",
	},
	{
		value: 'bushiba_fan_wave',
		label: 'Shiba dog dressed in a traditional outfit waving Japanese fans',
		amount: '10.00',
		currency: 'USD',
		helperText: '$10.00',
		imageUrl: 'https://lh3.googleusercontent.com/1GF4XO0fhtEnQiPQwgLDQ49XhFOJxV7aJW3ku9eJEJptm1UwdE-vzQb4wTF5Utg5rcsSJuBY7sCkwyTLkeg',
		searchText: 'bushiba_fan_wave Shiba dog dressed in a traditional outfit waving Japanese fans 10.00 USD',
	},
	{
		value: 'bushiba_rofl',
		label: 'Shiba dog rolling on the floor, laughing out loud',
		amount: '10.00',
		currency: 'USD',
		helperText: '$10.00',
		imageUrl: 'https://lh3.googleusercontent.com/nm7xs2j5R7Yuo21TJ-DRDiAiCIh-Go8KR2z3eeA6yHVsuco0JrZ8AJ42LvewXVOoVc9QIylNFyTKPfkFQu0',
		searchText: 'bushiba_rofl Shiba dog rolling on the floor, laughing out loud 10.00 USD',
	},
	{
		value: 'bushiba_good_luck',
		label: 'Shiba dog shouting good luck in a megaphone',
		amount: '10.00',
		currency: 'USD',
		helperText: '$10.00',
		imageUrl: 'https://lh3.googleusercontent.com/b3fUOLrgmV-e7CWJFzm7UXnj6i838RoZC8KpdWynMaFXNeQdR295IC53-CZmCpDLB2oZmnQ6GC3TyhUFkYY',
		searchText: 'bushiba_good_luck Shiba dog shouting good luck in a megaphone 10.00 USD',
	},
	{
		value: 'bushiba_squeeze_heart',
		label: 'Shiba dog squeezing a big red heart',
		amount: '10.00',
		currency: 'USD',
		helperText: '$10.00',
		imageUrl: 'https://lh3.googleusercontent.com/Yj6rzvUaC591kgcbp6YLj53HJP6BswTniySl4xoQlygU1luGaMTFeGUMe5oUAC96mrssuoUw5qoqpZzBRDA',
		searchText: 'bushiba_squeeze_heart Shiba dog squeezing a big red heart 10.00 USD',
	},
	{
		value: 'bushiba_thank_you',
		label: "Shiba dog shaking his hips saying 'Thank you'",
		amount: '10.00',
		currency: 'USD',
		helperText: '$10.00',
		imageUrl: 'https://lh3.googleusercontent.com/cDhsL836Oih9FUmQMbNJHN2tecgCDacPD-bE82riHf_plCEoLFuntYfSbBjkTWBgLuk_VS18jea4CoUh3XE',
		searchText: "bushiba_thank_you Shiba dog shaking his hips saying 'Thank you' 10.00 USD",
	},
	{
		value: 'bushiba_samurai_trophy',
		label: 'Shiba dog in samurai armor holding a golden trophy',
		amount: '20.00',
		currency: 'USD',
		helperText: '$20.00',
		imageUrl: 'https://lh3.googleusercontent.com/Jjtm3lOHd2NhMaetLeauWxBNx9CA7vArr8PfG3FXcCtHw6v9A8I1U5uOGdu79x4igOzXCjCVLgD1xvBxEbhZ',
		searchText: 'bushiba_samurai_trophy Shiba dog in samurai armor holding a golden trophy 20.00 USD',
	},
	{
		value: 'bushiba_samurai_number_one_flag',
		label: 'Shiba dog in samurai armour, waving a banner saying #1',
		amount: '20.00',
		currency: 'USD',
		helperText: '$20.00',
		imageUrl: 'https://lh3.googleusercontent.com/YUJib2PNhUPp3Mi3hw1LncagvqUsVvrRDVK3q-mxD6wVO3sw_6wuDrQ2-U46ZoCIMnCtPtcqF_E-AqNwTQ',
		searchText: 'bushiba_samurai_number_one_flag Shiba dog in samurai armour, waving a banner saying #1 20.00 USD',
	},
	{
		value: 'bushiba_samurai_amazing',
		label: "Shiba dog wearing samurai armor writing 'You're amazing' in the air with sparklers",
		amount: '50.00',
		currency: 'USD',
		helperText: '$50.00',
		imageUrl: 'https://lh3.googleusercontent.com/k4OwpD05s52dcfXQ88DUcco5bLW38cHkpfmQftjSNzuXJTOOHsXoa-trHRRnoRYGZSxti7APvOha265X9P4',
		searchText: "bushiba_samurai_amazing Shiba dog wearing samurai armor writing 'You're amazing' in the air with sparklers 50.00 USD",
	},
	{
		value: 'bushiba_fireworks',
		label: 'Shiba dog jumping in the air with fireworks around him',
		amount: '50.00',
		currency: 'USD',
		helperText: '$50.00',
		imageUrl: 'https://lh3.googleusercontent.com/F9hYM8LBLkP2zc_eoSPntXri750IJMttj2tyyaUQmpa-4tVqV0nyqQsozgcXYYtW8se6FVieYzfINOO2VF7b',
		searchText: 'bushiba_fireworks Shiba dog jumping in the air with fireworks around him 50.00 USD',
	},
	{
		value: 'biggest_fans_heart_shaped_sunglasses_lowered_stare',
		label: 'Fan character wearing heart shaped sunglasses',
		amount: '2.00',
		currency: 'USD',
		helperText: '$2.00',
		imageUrl: 'https://lh3.googleusercontent.com/xQFrhHx1ER-mqB3Igo0ZInjnfHEJoZtNwmBvNQeVNwHaaiDx34yckZEtvkI4IcAsQXsUDDcSi40X_lN9H5g',
		searchText: 'biggest_fans_heart_shaped_sunglasses_lowered_stare Fan character wearing heart shaped sunglasses 2.00 USD',
	},
	{
		value: 'biggest_fans_hand_pick_me_ja',
		label: 'Character waving their hand saying "Me!"',
		amount: '2.00',
		currency: 'USD',
		helperText: '$2.00',
		imageUrl: 'https://lh3.googleusercontent.com/PR_TkTOkfqParLO4UQEpF7vBWXbDUQRHqW5mgHZ5ibQAgX1U5RajHhF9MZNSkz2BGTb3cpvdq7LiFekzRA',
		searchText: 'biggest_fans_hand_pick_me_ja Character waving their hand saying "Me!" 2.00 USD',
	},
	{
		value: 'biggest_fans_fist_bump_handshake',
		label: 'Hands doing a fist bump',
		amount: '2.00',
		currency: 'USD',
		helperText: '$2.00',
		imageUrl: 'https://lh3.googleusercontent.com/dassRcxQM2qUe0bQCmQXoG_1Gn7KBZhzRsnqUDsVvYN5Ofh018FfsmBYWAMsE6DD6zla15tMTlDlN-yjepA',
		searchText: 'biggest_fans_fist_bump_handshake Hands doing a fist bump 2.00 USD',
	},
	{
		value: 'biggest_fans_brb_ja',
		label: 'A post it note with the text "I\'ll be back" appearing on it',
		amount: '3.00',
		currency: 'USD',
		helperText: '$3.00',
		imageUrl: 'https://lh3.googleusercontent.com/zEhiy9814VDwSDxYeErbh2Jdk7lHrYWEI6MLVGHHByzGrRW9VU_34AgU6oIOLwPyOVIYa1gljrhnU0K_LQ',
		searchText: 'biggest_fans_brb_ja A post it note with the text "I\'ll be back" appearing on it 3.00 USD',
	},
	{
		value: 'biggest_fans_how_you_doing_jp_v2',
		label: 'Character holding their head in their hand saying "How is it going?"',
		amount: '3.00',
		currency: 'USD',
		helperText: '$3.00',
		imageUrl: 'https://lh3.googleusercontent.com/4zajgqFL3w6XXZHKJjDkP-TFAptVNTT4CqXZs8HZq_29aTX93cCu_q6kGTuWFIt5U4Q-ltRhQnLo1SPYyQ',
		searchText: 'biggest_fans_how_you_doing_jp_v2 Character holding their head in their hand saying "How is it going?" 3.00 USD',
	},
	{
		value: 'biggest_fans_hands_horn_sign',
		label: 'Hands doing the sign of the horns with sparkles around',
		amount: '3.00',
		currency: 'USD',
		helperText: '$3.00',
		imageUrl: 'https://lh3.googleusercontent.com/lN6QKcCVpXH_TdCWqcjcVrVLsFV-SGXTwqMggtImzyHiVoCnqTKdfo9f1gRJc52mC5HaYPkmfUVwxGbY1QrR',
		searchText: 'biggest_fans_hands_horn_sign Hands doing the sign of the horns with sparkles around 3.00 USD',
	},
	{
		value: 'biggest_fans_thumbs_up_ja',
		label: 'A thumps-up hand gesture with the words "Top!"',
		amount: '3.00',
		currency: 'USD',
		helperText: '$3.00',
		imageUrl: 'https://lh3.googleusercontent.com/R7psY-l0U0ROvCcb55iFTmaaff_z4rEO60UGvaisN_MG8KdzWzttcDsn8B1REpPQP13-IFWaYSobNjLmUQ',
		searchText: 'biggest_fans_thumbs_up_ja A thumps-up hand gesture with the words "Top!" 3.00 USD',
	},
	{
		value: 'biggest_fans_have_some_coffee_jp_v2',
		label: 'Character handing over a cup of coffee saying "For you"',
		amount: '4.00',
		currency: 'USD',
		helperText: '$4.00',
		imageUrl: 'https://lh3.googleusercontent.com/zmcEBhYr6R_-dwl7CNPNtVPegvVTuMU138RoNKy0fG14ClsX3BbKz_Ykff5XFnZZBJQ9pApM5H80FxpfHfU',
		searchText: 'biggest_fans_have_some_coffee_jp_v2 Character handing over a cup of coffee saying "For you" 4.00 USD',
	},
	{
		value: 'biggest_fans_lol_cry_ja',
		label: 'Fan character laughing out loud, with tears in their eyes',
		amount: '5.00',
		currency: 'USD',
		helperText: '$5.00',
		imageUrl: 'https://lh3.googleusercontent.com/H7iAwec3FaL2H9a_TyRpvMoZY8t4I3QjacKS3Bz1goPq-dOjzj1njsfN4t2THB40DL5cRxKwbCLcoUks3w',
		searchText: 'biggest_fans_lol_cry_ja Fan character laughing out loud, with tears in their eyes 5.00 USD',
	},
	{
		value: 'biggest_fans_head_in_hands_heart_wink_ja',
		label: 'Character holding their head in their hands, saying "You\'re my #1"',
		amount: '5.00',
		currency: 'USD',
		helperText: '$5.00',
		imageUrl: 'https://lh3.googleusercontent.com/CR7Io9aaaoZ5Owfpmd_MrAtCJ5ZejJ8RMsF37HGR9mYVABVkXiHnhOtO2aEhFjj8i0qc8ce7Eg7nZ_aqpjOc',
		searchText: 'biggest_fans_head_in_hands_heart_wink_ja Character holding their head in their hands, saying "You\'re my #1" 5.00 USD',
	},
	{
		value: 'biggest_fans_whoa_shake_head_ja',
		label: 'Character looking really impressed saying "Whoa"',
		amount: '5.00',
		currency: 'USD',
		helperText: '$5.00',
		imageUrl: 'https://lh3.googleusercontent.com/f7iVANXYolRQuSnXXQw-dpm2MoP4KLu142m5wefislAS0Sb4bJDf-6QHTN92TEpqLhkE3DRKLZTDko6CitE',
		searchText: 'biggest_fans_whoa_shake_head_ja Character looking really impressed saying "Whoa" 5.00 USD',
	},
	{
		value: 'biggest_fans_flex_bicep_you_rock_jp_v2',
		label: 'Character saying "You rock" whilst showing their pumped bicep',
		amount: '5.00',
		currency: 'USD',
		helperText: '$5.00',
		imageUrl: 'https://lh3.googleusercontent.com/6OKp2pOv7HWrJa6uMQsNYWm1M1m4rtYzIxCPxsmrl-i94ctf0UC560K1muxwMQQRnk6baGWj-fTGDt1iNtQ',
		searchText: 'biggest_fans_flex_bicep_you_rock_jp_v2 Character saying "You rock" whilst showing their pumped bicep 5.00 USD',
	},
	{
		value: 'biggest_fans_hiya_jp_v2',
		label: 'Character appearing from behind a cloud saying "Hiya"',
		amount: '5.00',
		currency: 'USD',
		helperText: '$5.00',
		imageUrl: 'https://lh3.googleusercontent.com/fxsnJ9MMUFx1rMrQOLz3xP1vJnZ4lfMOWHu1E1y407T5W6ggLFWllrTi5timH4s2hscv9RqNAdeM4Gcr2RU',
		searchText: 'biggest_fans_hiya_jp_v2 Character appearing from behind a cloud saying "Hiya" 5.00 USD',
	},
	{
		value: 'biggest_fans_hands_high_five',
		label: 'Hands doing a high five',
		amount: '5.00',
		currency: 'USD',
		helperText: '$5.00',
		imageUrl: 'https://lh3.googleusercontent.com/0wvdks8y_PX52Yl8vLAEsSixjXflL4HZvWYXj-2D3UJUMD-ZM3H848SDpMfwcc8Pq5STIN1b4cnxxQ8UmuY',
		searchText: 'biggest_fans_hands_high_five Hands doing a high five 5.00 USD',
	},
	{
		value: 'biggest_fans_face_in_hands_incredible_ja',
		label: 'Character holding their head in their hands saying "Incredible"',
		amount: '5.00',
		currency: 'USD',
		helperText: '$5.00',
		imageUrl: 'https://lh3.googleusercontent.com/bG3wFu1JI9Nda-O6nyMihh1SWj2eRSpoZmUsuyQTXzDmCYmP5tILtn-t3YTKcLH-YdIZjkZoJGXnsE8EcKM',
		searchText: 'biggest_fans_face_in_hands_incredible_ja Character holding their head in their hands saying "Incredible" 5.00 USD',
	},
	{
		value: 'biggest_fans_blush_v2',
		label: 'Fan character with eyes wide open, blushing',
		amount: '10.00',
		currency: 'USD',
		helperText: '$10.00',
		imageUrl: 'https://lh3.googleusercontent.com/-fBF9LoJu0aa0P_bDDu1ehchaYBOqhsp-AFxRNAqsoWQD5R782iM9IDqp6JQHnrhLRZv-mTeWoc2LmBxUMw',
		searchText: 'biggest_fans_blush_v2 Fan character with eyes wide open, blushing 10.00 USD',
	},
	{
		value: 'biggest_fans_rofl_fist_pound_ja',
		label: 'Character on the floor laughing really hard',
		amount: '10.00',
		currency: 'USD',
		helperText: '$10.00',
		imageUrl: 'https://lh3.googleusercontent.com/4QZRPQhc6MZ0q8-ckcWZNhcKbLOffI3uVpHPwyQ5dZW-I8GiLgfAyPP2lxO68brpY1xrH5eucajAcuhRIF2v',
		searchText: 'biggest_fans_rofl_fist_pound_ja Character on the floor laughing really hard 10.00 USD',
	},
	{
		value: 'biggest_fans_clasp_hands_thanks_jp_v2',
		label: 'Character holding their hands together saying "Thanks"',
		amount: '10.00',
		currency: 'USD',
		helperText: '$10.00',
		imageUrl: 'https://lh3.googleusercontent.com/NG-TSFI_8BdVWpSdUXPZ7D8WpPY4s7HaGT1VL8N_sIPUpQqV4NP82oDugC-2kCFgEaN0S-If10tHj2uMkKM',
		searchText: 'biggest_fans_clasp_hands_thanks_jp_v2 Character holding their hands together saying "Thanks" 10.00 USD',
	},
	{
		value: 'biggest_fans_cheerleader_air_jump',
		label: 'Fan character dressed as a cheerleader jumping in the air',
		amount: '10.00',
		currency: 'USD',
		helperText: '$10.00',
		imageUrl: 'https://lh3.googleusercontent.com/WtHjpCnBi5Q9OlDrcDjvn2MkppjPEEt-rmXF8mGg9cpyAAE_gA6Wubw5favaeJ_h8lEwgnil5Wu6PxkH44c',
		searchText: 'biggest_fans_cheerleader_air_jump Fan character dressed as a cheerleader jumping in the air 10.00 USD',
	},
	{
		value: 'biggest_fans_jump_hurray_jp_v2',
		label: 'Character jumping in the air joyfully, saying "Yippee"',
		amount: '10.00',
		currency: 'USD',
		helperText: '$10.00',
		imageUrl: 'https://lh3.googleusercontent.com/Lt9dO1KmY8sjjF3cw266AFE8NHanr7Bc3o2TcCVCI1lPXsb3895QzqLGv5Oluk8OsUYO7jIDaPQ9hQoJ6A',
		searchText: 'biggest_fans_jump_hurray_jp_v2 Character jumping in the air joyfully, saying "Yippee" 10.00 USD',
	},
	{
		value: 'biggest_fans_heart_hands_v2',
		label: 'Fan character sending hearts with their hands',
		amount: '20.00',
		currency: 'USD',
		helperText: '$20.00',
		imageUrl: 'https://lh3.googleusercontent.com/bt8iOTjsWDcf8mqQfSj9sWYfbuBTeLCNis6hVWWYNboKnOPxsHBmpuhXzxT51MSEEV3ULMECXS26NliUfw',
		searchText: 'biggest_fans_heart_hands_v2 Fan character sending hearts with their hands 20.00 USD',
	},
	{
		value: 'biggest_fans_ponytail_heart_star_eyes_v2',
		label: 'Fan character bouncing their heart shaped ponytail, with stars in their eye',
		amount: '20.00',
		currency: 'USD',
		helperText: '$20.00',
		imageUrl: 'https://lh3.googleusercontent.com/j0Gk-llxuY_h1A85Ep0V-wHuTL1xleoIlHncomroNivu0QyJoSiKfzcKOksUOZhtCna74csC0W25NGGVzY8',
		searchText: 'biggest_fans_ponytail_heart_star_eyes_v2 Fan character bouncing their heart shaped ponytail, with stars in their eye 20.00 USD',
	},
	{
		value: 'biggest_fans_cheerleader_jumps_in_front_of_heart',
		label: 'Fan character jumping in the air in front of a big red heart with pompom in their hands',
		amount: '50.00',
		currency: 'USD',
		helperText: '$50.00',
		imageUrl: 'https://lh3.googleusercontent.com/6whK9POrm9wu0-v4WdDPfcAmhlPLuFDvMVncHfcyLf1OEFJfhQkT2bo0CgUB-Te-cP_TYMyYC0qdxxawYe4',
		searchText: 'biggest_fans_cheerleader_jumps_in_front_of_heart Fan character jumping in the air in front of a big red heart with pompom in their hands 50.00 USD',
	},
	{
		value: 'biggest_fans_fireworks_sunglass_amazed',
		label: 'Fan character wearing sunglasses with fireworks appearing on the lenses',
		amount: '50.00',
		currency: 'USD',
		helperText: '$50.00',
		imageUrl: 'https://lh3.googleusercontent.com/VWPUURLWXM9MhZjE1gOUgn8SNw5XOBQjTUKgt9kEmg3NU9lfJ6MIGZvAjrux2DjsarLG2qWu3seWSEP2Bo9X',
		searchText: 'biggest_fans_fireworks_sunglass_amazed Fan character wearing sunglasses with fireworks appearing on the lenses 50.00 USD',
	},
	{
		value: 'energetic_lemon_and_baby_lemon_superhero',
		label: 'Baby Lemon looking up to our lemon character standing in a super hero position',
		amount: '2.00',
		currency: 'USD',
		helperText: '$2.00',
		imageUrl: 'https://lh3.googleusercontent.com/BUUHBzpEM36kYgVamm_I_VXzIweEBQNG1cDVqmg8sytwK95YpWyXFL45oRLVH9xGMqaDDl7PdTvHQcAX-3rM',
		searchText: 'energetic_lemon_and_baby_lemon_superhero Baby Lemon looking up to our lemon character standing in a super hero position 2.00 USD',
	},
	{
		value: 'energetic_lemon_and_baby_lemon_running_kneel',
		label: 'Lemon character running then kneeling on the floor, his arms wide open and a slice of lemon appearing behind him',
		amount: '2.00',
		currency: 'USD',
		helperText: '$2.00',
		imageUrl: 'https://lh3.googleusercontent.com/Ezqrr0fGmiMVmjh5B5Pf9p-pwKEABXz7ggC6tO_9dl2AqQX4LXfSL7fbUbgbryo-NZxdKV-ZKxqLTt5X5d0',
		searchText: 'energetic_lemon_and_baby_lemon_running_kneel Lemon character running then kneeling on the floor, his arms wide open and a slice of lemon appearing behind him 2.00 USD',
	},
	{
		value: 'energetic_lemon_and_baby_lemon_blow_heart',
		label: 'Lemon character blowing a big red heart',
		amount: '2.00',
		currency: 'USD',
		helperText: '$2.00',
		imageUrl: 'https://lh3.googleusercontent.com/Aj1ogDvPPPa0WAFh3jlOxwVuX5v_qCnTUe-99JOdaXirDeOHHz4aC6pBO4sWoFeIFpRXxfELXJBAwJov2Q',
		searchText: 'energetic_lemon_and_baby_lemon_blow_heart Lemon character blowing a big red heart 2.00 USD',
	},
	{
		value: 'energetic_lemon_and_baby_lemon_wave_hello',
		label: 'Lemon character waving his arm to say hello with his mouth open',
		amount: '3.00',
		currency: 'USD',
		helperText: '$3.00',
		imageUrl: 'https://lh3.googleusercontent.com/1Y9ZUBcChBgdbFfIJuzjpg10nP4-TSqFhvjWTIwaqP88ryiF1HlPaQTh2NIsejNQhovvr9uIox2mHNQ_yno',
		searchText: 'energetic_lemon_and_baby_lemon_wave_hello Lemon character waving his arm to say hello with his mouth open 3.00 USD',
	},
	{
		value: 'energetic_lemon_and_baby_lemon_wink_goodbye',
		label: 'Lemon character waving goodbye while winking and sending a shooting star',
		amount: '3.00',
		currency: 'USD',
		helperText: '$3.00',
		imageUrl: 'https://lh3.googleusercontent.com/Yhq0czCM5RMRPmaKMQ620ffWp9UUaBaMSXXuSwtiMjL51FcCkhfsfinXfvg6BuN-L5mMGUxdqKOK_cReQTw',
		searchText: 'energetic_lemon_and_baby_lemon_wink_goodbye Lemon character waving goodbye while winking and sending a shooting star 3.00 USD',
	},
	{
		value: 'energetic_lemon_and_baby_lemon_two_thumbs_up',
		label: 'Lemon character raising both his thumbs up',
		amount: '3.00',
		currency: 'USD',
		helperText: '$3.00',
		imageUrl: 'https://lh3.googleusercontent.com/7gBP8emhv8B6eBHWWeN0I7WO2CQgIypq4AWT-FOfInHaF2Mwb7ar1Rt-_5z_kO94AYw9b3axqdKTAgZ9JJE',
		searchText: 'energetic_lemon_and_baby_lemon_two_thumbs_up Lemon character raising both his thumbs up 3.00 USD',
	},
	{
		value: 'energetic_lemon_and_baby_lemon_cheerleading',
		label: 'Baby Lemon with pom poms in his hands, cheerleading',
		amount: '3.00',
		currency: 'USD',
		helperText: '$3.00',
		imageUrl: 'https://lh3.googleusercontent.com/VKSV9Ku_rLYa9bse1MhNSi0ch8YGr1RRB5jkA_DaggTi0hRG6iu93jbrW_V613w63JQm5fKHz0nWMOSG6M0',
		searchText: 'energetic_lemon_and_baby_lemon_cheerleading Baby Lemon with pom poms in his hands, cheerleading 3.00 USD',
	},
	{
		value: 'energetic_lemon_and_baby_lemon_gift',
		label: 'Lemon character offering a gift to Baby Lemon',
		amount: '4.00',
		currency: 'USD',
		helperText: '$4.00',
		imageUrl: 'https://lh3.googleusercontent.com/S5wtfxLWBJBnr6ySSQtJCrUAfidyZgG16qZKyetXOHeRCkf_9EHfVzm3utrU1lqnaBdUJjjB3PRu1F9LG2s',
		searchText: 'energetic_lemon_and_baby_lemon_gift Lemon character offering a gift to Baby Lemon 4.00 USD',
	},
	{
		value: 'energetic_lemon_and_baby_lemon_hehe',
		label: 'Lemon character holding his hand in front of his mouth, grinning',
		amount: '5.00',
		currency: 'USD',
		helperText: '$5.00',
		imageUrl: 'https://lh3.googleusercontent.com/hkr7gND4-FGe9Ex3vFSMyeOZR02t_bIQj49ngMvBUuXKwuNNYekYqrHh1gTWdG2UW6ceCboRfvWsjIEC1O0',
		searchText: 'energetic_lemon_and_baby_lemon_hehe Lemon character holding his hand in front of his mouth, grinning 5.00 USD',
	},
	{
		value: 'energetic_lemon_and_baby_lemon_heart_eyes',
		label: 'Lemon character moving his head from left to right with his mouth wide open and red hearts in his eyes',
		amount: '5.00',
		currency: 'USD',
		helperText: '$5.00',
		imageUrl: 'https://lh3.googleusercontent.com/LhwH6NUC4DpY6JhATjqXf_t49ON9hCVneKIC6hMTI9r46IjywPKLVDfhF48R3iZ5uUrRIWkCRlYEh8mi0w',
		searchText: 'energetic_lemon_and_baby_lemon_heart_eyes Lemon character moving his head from left to right with his mouth wide open and red hearts in his eyes 5.00 USD',
	},
	{
		value: 'energetic_lemon_and_baby_lemon_lift_congratulate',
		label: 'Lemon character lifting Baby Lemon in the air to congratulate him',
		amount: '5.00',
		currency: 'USD',
		helperText: '$5.00',
		imageUrl: 'https://lh3.googleusercontent.com/ImYQMsYGvt9mPDLdSPcm8tp7MCoQwJqjGILdBwUPYtPpVv0FVKF7CPetTSXsnBuOFzXh1wvF-DI7U3kafeU',
		searchText: 'energetic_lemon_and_baby_lemon_lift_congratulate Lemon character lifting Baby Lemon in the air to congratulate him 5.00 USD',
	},
	{
		value: 'energetic_lemon_and_baby_lemon_sunglass_greeting',
		label: 'Lemon character taking his sunglasses off and raising his arm to greet someone, imitated by Baby Lemon',
		amount: '5.00',
		currency: 'USD',
		helperText: '$5.00',
		imageUrl: 'https://lh3.googleusercontent.com/I__n-CgGrxFZAKjrSGZ9Rs75QByoNoLUtvDgC9lLjfAwAr8wpBg9AYTxp2SaSKNbw6xJuRv22hpxLHJY0KQ',
		searchText: 'energetic_lemon_and_baby_lemon_sunglass_greeting Lemon character taking his sunglasses off and raising his arm to greet someone, imitated by Baby Lemon 5.00 USD',
	},
	{
		value: 'energetic_lemon_and_baby_lemon_horns',
		label: 'Lemon character and Baby Lemon blowing a party horn while marching',
		amount: '5.00',
		currency: 'USD',
		helperText: '$5.00',
		imageUrl: 'https://lh3.googleusercontent.com/vOn7OAZH7UwquF19uoq_7wDojXw3KOVkaSrYQxGzCO8Trh_eI0gxnCJqunDwwwcJT0IRuwCJ3EExWQMF',
		searchText: 'energetic_lemon_and_baby_lemon_horns Lemon character and Baby Lemon blowing a party horn while marching 5.00 USD',
	},
	{
		value: 'energetic_lemon_and_baby_lemon_high_five',
		label: 'Lemon character and Baby Lemon jumping in the air to do a high five',
		amount: '5.00',
		currency: 'USD',
		helperText: '$5.00',
		imageUrl: 'https://lh3.googleusercontent.com/daIAHbLGWS--vODKS8o6YAZrOqkeSoANXZjUSCJnoxGnvMnb0y3E1Dx3gLSBr5LsPYpeRJ74-Kttk_oQ0A',
		searchText: 'energetic_lemon_and_baby_lemon_high_five Lemon character and Baby Lemon jumping in the air to do a high five 5.00 USD',
	},
	{
		value: 'energetic_lemon_and_baby_lemon_shimmy',
		label: 'Lemon character doing shoulder shimmy dance moves',
		amount: '5.00',
		currency: 'USD',
		helperText: '$5.00',
		imageUrl: 'https://lh3.googleusercontent.com/O7slqOG4YAZi9i4jFdb7JNGLIqvIoQxSILqiMGbqEqc-cMGq4mGsrIsIaw_TeUqX3bFtGCUUxeA3_tAeUA',
		searchText: 'energetic_lemon_and_baby_lemon_shimmy Lemon character doing shoulder shimmy dance moves 5.00 USD',
	},
	{
		value: 'energetic_lemon_and_baby_lemon_heart_thump',
		label: 'Lemon character jumping in excitement with his heart beating out of his chest',
		amount: '10.00',
		currency: 'USD',
		helperText: '$10.00',
		imageUrl: 'https://lh3.googleusercontent.com/bIDrC2ORwlT9cMKeVTujtaAjMiY8rA7DgV4Gk1Q49ej_Ho20DBmrgy6MY4NG0Qi3tJADfgMuWS4Z2dXzlqU',
		searchText: 'energetic_lemon_and_baby_lemon_heart_thump Lemon character jumping in excitement with his heart beating out of his chest 10.00 USD',
	},
	{
		value: 'energetic_lemon_and_baby_lemon_lol',
		label: 'Lemon character laughing out loud',
		amount: '10.00',
		currency: 'USD',
		helperText: '$10.00',
		imageUrl: 'https://lh3.googleusercontent.com/3GyN7KYykB9bEXlHpfWCIgfRhI0yO4aWP-U84jS-ChOvuVjCQdS3e6tdE69hf9i27QMkrHQN6iSpxi4d5otQ',
		searchText: 'energetic_lemon_and_baby_lemon_lol Lemon character laughing out loud 10.00 USD',
	},
	{
		value: 'energetic_lemon_and_baby_lemon_yay',
		label: 'Lemon character moving in excitement',
		amount: '10.00',
		currency: 'USD',
		helperText: '$10.00',
		imageUrl: 'https://lh3.googleusercontent.com/djInM-cbStB4ROCCoPffH7jQ_CxzvwDlxRXSrpRnpQcKYuAHjttZSYqclNPEw9bEVcvPBhYowrJcoXnya8E',
		searchText: 'energetic_lemon_and_baby_lemon_yay Lemon character moving in excitement 10.00 USD',
	},
	{
		value: 'energetic_lemon_and_baby_lemon_maracas',
		label: 'Lemon character doing a victory dance with maracas in his hands',
		amount: '10.00',
		currency: 'USD',
		helperText: '$10.00',
		imageUrl: 'https://lh3.googleusercontent.com/OkxToYxHDAsPsQ-M4oM9cOLON6nPOTDaIsd5A07aaXBrFvxi6Sf7E-pEfrYRwZIkwnQksBqEuQIVMvqSJw',
		searchText: 'energetic_lemon_and_baby_lemon_maracas Lemon character doing a victory dance with maracas in his hands 10.00 USD',
	},
	{
		value: 'energetic_lemon_and_baby_lemon_grateful',
		label: 'Lemon character holding his hands with gratitude on his face',
		amount: '10.00',
		currency: 'USD',
		helperText: '$10.00',
		imageUrl: 'https://lh3.googleusercontent.com/wXyFlmLAaDdjkB39R7_5KX8WYy4SiwoACZju1mkOQKxe8UVpkRDopTvpnOhRC3BJpw5akIETw1LClSf0_5hX',
		searchText: 'energetic_lemon_and_baby_lemon_grateful Lemon character holding his hands with gratitude on his face 10.00 USD',
	},
	{
		value: 'energetic_lemon_and_baby_lemon_bowing_heart',
		label: 'Lemon character bowing his head while spreading hearts with his arms',
		amount: '20.00',
		currency: 'USD',
		helperText: '$20.00',
		imageUrl: 'https://lh3.googleusercontent.com/annlyNGYGwu4DcvioYeC5OQrpVtoXdL7FF0cEU75u2Hnu0iTlDIOxtLn2V_VRXydgHmWvuc_anzlx5P8oCI',
		searchText: 'energetic_lemon_and_baby_lemon_bowing_heart Lemon character bowing his head while spreading hearts with his arms 20.00 USD',
	},
	{
		value: 'energetic_lemon_and_baby_lemon_jump_hug',
		label: "Baby Lemon jumping in our lemon character's arms to hug him",
		amount: '20.00',
		currency: 'USD',
		helperText: '$20.00',
		imageUrl: 'https://lh3.googleusercontent.com/EtK9moll0KtyscCFYFeJ307cCK-lu1bfn7QD-v-QoptzZlnJRdS8N_xTPhS3RJsrrTJJYQXhLo6IvcOO1ig0',
		searchText: "energetic_lemon_and_baby_lemon_jump_hug Baby Lemon jumping in our lemon character's arms to hug him 20.00 USD",
	},
	{
		value: 'energetic_lemon_and_baby_lemon_twirl_hug',
		label: 'Lemon character and Baby Lemon twirling around in the air, hugging',
		amount: '50.00',
		currency: 'USD',
		helperText: '$50.00',
		imageUrl: 'https://lh3.googleusercontent.com/uZGyamQNmL6a8M4nPdA_3tqzoABuZGvOGoKQ_dOnEIg05zS6VZLgnJNqrG0g80nOX-eiadm0kat0iDVaenIj',
		searchText: 'energetic_lemon_and_baby_lemon_twirl_hug Lemon character and Baby Lemon twirling around in the air, hugging 50.00 USD',
	},
	{
		value: 'energetic_lemon_and_baby_lemon_fireworks',
		label: 'Lemon character and Baby Lemon jumping in the air with fireworks behind them',
		amount: '50.00',
		currency: 'USD',
		helperText: '$50.00',
		imageUrl: 'https://lh3.googleusercontent.com/X8x3DMBVEqmQL5qW821IUhLsU7p7gGLT0rmBAzxj8ybtMTKCwZtdIUrmUYCJnLR5mMAfeW_mAmmxoh5Rz-ZT',
		searchText: 'energetic_lemon_and_baby_lemon_fireworks Lemon character and Baby Lemon jumping in the air with fireworks behind them 50.00 USD',
	},
	{
		value: 'youtube_object_thumbs_up_red',
		label: 'A thumbs up',
		amount: '1.99',
		currency: 'USD',
		helperText: '$1.99',
		imageUrl: 'https://lh3.googleusercontent.com/5wOB_7MitsAPQG1vpCYSSLOLHdiRIwwsf97yfzW63YZihVf0B6MulS65DRFeftFul6rd6BNCxZ5h0wrIvkA',
		searchText: 'youtube_object_thumbs_up_red A thumbs up 1.99 USD',
	},
	{
		value: 'youtube_object_on_set',
		label: 'Director\'s chair with the words "ON SET"',
		amount: '1.99',
		currency: 'USD',
		helperText: '$1.99',
		imageUrl: 'https://lh3.googleusercontent.com/KP--Ps9ho0bWIFUA9lqnCJ1kI4Z721WAdOMa0zUEFLLVpEjH6VGcOfmqqBILfeHQR3bTR0o9CXtKdUqStQ',
		searchText: 'youtube_object_on_set Director\'s chair with the words "ON SET" 1.99 USD',
	},
	{
		value: 'youtube_object_vlog',
		label: 'Cursive red lettering spelling out "vlog"',
		amount: '1.99',
		currency: 'USD',
		helperText: '$1.99',
		imageUrl: 'https://lh3.googleusercontent.com/_rHufCYaHtN5V_UtbWWNg5uxLeFQu2H-lqhxtIaj0ur9HxD_p6a8oAeOzWPyNJW5qoYb8tpRaUPCwLbBGZY',
		searchText: 'youtube_object_vlog Cursive red lettering spelling out "vlog" 1.99 USD',
	},
	{
		value: 'youtube_object_thanks',
		label: '"Thanks!" written on top of a purple heart',
		amount: '1.99',
		currency: 'USD',
		helperText: '$1.99',
		imageUrl: 'https://lh3.googleusercontent.com/vesFbZnWWHrCOfCQ9laSsO-olblSsCahc4Rc7hPoV8l5AbkyOsG-7JMGVxrwtvqfYo2J6be1i7mokFIvwDA',
		searchText: 'youtube_object_thanks "Thanks!" written on top of a purple heart 1.99 USD',
	},
	{
		value: 'youtube_object_unboxing',
		label: 'An opened cardboard box with the word "Unboxing"',
		amount: '1.99',
		currency: 'USD',
		helperText: '$1.99',
		imageUrl: 'https://lh3.googleusercontent.com/eTP6Qh-XyZ82p90D7iPmDY2oOTDNsIotSdqhrFgtJw-HAVraIKwBSaayu-XsPRvWoYaA302jsq_swP4Rerw',
		searchText: 'youtube_object_unboxing An opened cardboard box with the word "Unboxing" 1.99 USD',
	},
	{
		value: 'youtube_object_sneak_peek',
		label: 'An open eye with the words "SNEAK PEEK!"',
		amount: '1.99',
		currency: 'USD',
		helperText: '$1.99',
		imageUrl: 'https://lh3.googleusercontent.com/VdfViJB2ox-nyJUQSqjogVXj5NkF3g67xPdAnCnvNSXDpLfc7qqnOUGs5sAAZFzS3F5zZeKuZamkrzfwqg4',
		searchText: 'youtube_object_sneak_peek An open eye with the words "SNEAK PEEK!" 1.99 USD',
	},
	{
		value: 'youtube_object_arrow_here',
		label: 'A red down arrow with vertical words "HERE"',
		amount: '1.99',
		currency: 'USD',
		helperText: '$1.99',
		imageUrl: 'https://lh3.googleusercontent.com/nOBnHMX77wedx3o71L7yo8rCpgoN4tpR4wfHbOW9iU86qGfQEPzCXwZF-2ewUatCihJY5jz49PPu7h9Jn7jF',
		searchText: 'youtube_object_arrow_here A red down arrow with vertical words "HERE" 1.99 USD',
	},
	{
		value: 'youtube_object_tired',
		label: 'A coffee cup with the words "TIRED"',
		amount: '1.99',
		currency: 'USD',
		helperText: '$1.99',
		imageUrl: 'https://lh3.googleusercontent.com/z9cE1XTlAn2tYcYcnOVV6QSwrVGdXFNCmBuxsDoNM6ji5hnmlOHPtBez5v56Xw9x5FxZgy2qzr-c-Fa21Xs',
		searchText: 'youtube_object_tired A coffee cup with the words "TIRED" 1.99 USD',
	},
	{
		value: 'youtube_object_spoiler_alert',
		label: 'A beacon light with words "SPOILER ALERT"',
		amount: '1.99',
		currency: 'USD',
		helperText: '$1.99',
		imageUrl: 'https://lh3.googleusercontent.com/93OS0ad-iH1VTbyCKa0Dbiv5M6OcI3WOY7HCH64-FCS7mTXwHuOLT8OmEcbb1g91hJhnwWNHVVONqSRyGUM',
		searchText: 'youtube_object_spoiler_alert A beacon light with words "SPOILER ALERT" 1.99 USD',
	},
	{
		value: 'youtube_object_wait_for_it',
		label: '"Wait for it..." words with a clock as the "a"',
		amount: '1.99',
		currency: 'USD',
		helperText: '$1.99',
		imageUrl: 'https://lh3.googleusercontent.com/3e9Q37CQWBrZkWOTvHfq15h42-Xh6djjyuKx9eIXVfkCkImmGEt9TPRfGNr6c9QbRKgTS4GA4BJ7pmSJkknA',
		searchText: 'youtube_object_wait_for_it "Wait for it..." words with a clock as the "a" 1.99 USD',
	},
	{
		value: 'youtube_object_behind_the_scenes',
		label: 'A rainbow clapperboard with the words "BEHIND the SCENES"',
		amount: '1.99',
		currency: 'USD',
		helperText: '$1.99',
		imageUrl: 'https://lh3.googleusercontent.com/ZAuUCVICIZNtV1hJawnOnL9aI0Q2HnrlPZnYwvDJIUIJzb-GO0y2UHGwBXl-JqvTFkxlEP4b_DYqu2O1l7A',
		searchText: 'youtube_object_behind_the_scenes A rainbow clapperboard with the words "BEHIND the SCENES" 1.99 USD',
	},
	{
		value: 'youtube_object_mood',
		label: '"mood" written with smiley faces as the "oo"',
		amount: '1.99',
		currency: 'USD',
		helperText: '$1.99',
		imageUrl: 'https://lh3.googleusercontent.com/WHli40THNlWJuH7u-t9nPaxkDoQtElHChf-MiC8Lmt5FUj0LeJAtwoPpzto0Auq7Cas4Arxmxv-H9duB4YA9',
		searchText: 'youtube_object_mood "mood" written with smiley faces as the "oo" 1.99 USD',
	},
	{
		value: 'youtube_object_yum',
		label: 'Cursive teal lettering spelling out "Yum!"',
		amount: '1.99',
		currency: 'USD',
		helperText: '$1.99',
		imageUrl: 'https://lh3.googleusercontent.com/dkeq3p96iAb3EXCVVQU0swzyc0kSkUU6zgqMLFWgaZmrkxvuW0yDVSDzScgqCJ9dEPjB4kmiPdBNYgceJdI',
		searchText: 'youtube_object_yum Cursive teal lettering spelling out "Yum!" 1.99 USD',
	},
	{
		value: 'youtube_object_vibes',
		label: '"vibes" surrounded with little purple stars',
		amount: '1.99',
		currency: 'USD',
		helperText: '$1.99',
		imageUrl: 'https://lh3.googleusercontent.com/MBSHRXwz62vS0RSDhMzGHNYcY3TVqrdfu_e9-Kh88Yb8bIjVq5HGOXtjkPTwrMyKjkk4kKID03SRkQF3kA',
		searchText: 'youtube_object_vibes "vibes" surrounded with little purple stars 1.99 USD',
	},
	{
		value: 'youtube_object_point_up',
		label: 'A red hand pointing up',
		amount: '1.99',
		currency: 'USD',
		helperText: '$1.99',
		imageUrl: 'https://lh3.googleusercontent.com/je8GLqhCjZ3RSCU7krNFW9xcx-dkrabUkKn2TRa50OKWAw9LWJMHwXXGIEKrXaGC_LvZSTpJUu-ldB_zaABy',
		searchText: 'youtube_object_point_up A red hand pointing up 1.99 USD',
	},
	{
		value: 'youtube_object_heart',
		label: 'A red heart',
		amount: '1.99',
		currency: 'USD',
		helperText: '$1.99',
		imageUrl: 'https://lh3.googleusercontent.com/svP4llsw-MrtAFpcCnvSogzZqb8MvZ8Hs1zl2BMlsPAbipq1TFdIwQVGJ_db6AFC4N2uKBHThsw3iQOring',
		searchText: 'youtube_object_heart A red heart 1.99 USD',
	},
	{
		value: 'youtube_object_coming_soon',
		label: '"COMING SOON" surrounded by yellow stars',
		amount: '1.99',
		currency: 'USD',
		helperText: '$1.99',
		imageUrl: 'https://lh3.googleusercontent.com/gDtEleSF7R2C-hYJF5qofoGBNMdDuChYtvAK-MgYuAUTAlprOeDpXKw58x8yFpmw54w2Seb-HtrZ0LfHyY5m',
		searchText: 'youtube_object_coming_soon "COMING SOON" surrounded by yellow stars 1.99 USD',
	},
	{
		value: 'youtube_object_new',
		label: '"NEW" lettering in red, orange, and yellow',
		amount: '1.99',
		currency: 'USD',
		helperText: '$1.99',
		imageUrl: 'https://lh3.googleusercontent.com/AcZC-J4H6wlt1F2h1zTBCDxHIFnFcHsM7gn56NeXFztGqQsxZR27Re5VEbBlfyurKk0vzOjJPqkb87xJYOI',
		searchText: 'youtube_object_new "NEW" lettering in red, orange, and yellow 1.99 USD',
	},
	{
		value: 'youtube_object_game_over',
		label: '"GAME OVER" written in a pixellated way',
		amount: '1.99',
		currency: 'USD',
		helperText: '$1.99',
		imageUrl: 'https://lh3.googleusercontent.com/JRIRMZSo0cULfHAh5vE7EH9MJYziZvByXATQ3YRoFnZMA8Kb4Qd8nvHN8tiGNvttK9N36pqZQgw0h5Akdaw',
		searchText: 'youtube_object_game_over "GAME OVER" written in a pixellated way 1.99 USD',
	},
	{
		value: 'youtube_object_work',
		label: 'A laptop computer with "WORK" on the screen',
		amount: '1.99',
		currency: 'USD',
		helperText: '$1.99',
		imageUrl: 'https://lh3.googleusercontent.com/G0QIFNZeGoaFo0cAgvaXk6kDuXGIBFUjYOB9NDPqlqqxcQGY2VrNNG_UiuegBlGetB6VcDF25PDK9oN9r7g',
		searchText: 'youtube_object_work A laptop computer with "WORK" on the screen 1.99 USD',
	},
	{
		value: 'youtube_object_microphone',
		label: 'A microphone',
		amount: '1.99',
		currency: 'USD',
		helperText: '$1.99',
		imageUrl: 'https://lh3.googleusercontent.com/GGBPJqud9Z0ERTQchY2xn9YYhT_Anu1AGabiN5ajZfKWFp49cTFrZIN8m1GEg8o8lRkKsXCCuvMCq6zw8g',
		searchText: 'youtube_object_microphone A microphone 1.99 USD',
	},
	{
		value: 'youtube_object_luggage',
		label: 'An orange suitcase with travel stickers',
		amount: '1.99',
		currency: 'USD',
		helperText: '$1.99',
		imageUrl: 'https://lh3.googleusercontent.com/tQit6-YANATtK25zf3vE-dIoU9xIZwVGPFUpSZGY4-b-Wl-UXRwxbsnPMlXlj5xCR3orudVPYh1WnetcuQ',
		searchText: 'youtube_object_luggage An orange suitcase with travel stickers 1.99 USD',
	},
	{
		value: 'grab_bag_1_unicorn',
		label: 'A white unicorn with rainbow hair',
		amount: '1.49',
		currency: 'USD',
		helperText: '$1.49',
		imageUrl: 'https://lh3.googleusercontent.com/Op215FSXkF_QA8N5WyDrilqcv11gS-W1Ux2GQejQAZ1FLNuHl5TCmoPjbvixOZ4CCgm04I6acx5vzwj9J6M',
		searchText: 'grab_bag_1_unicorn A white unicorn with rainbow hair 1.49 USD',
	},
	{
		value: 'grab_bag_1_peach',
		label: 'A peach',
		amount: '1.49',
		currency: 'USD',
		helperText: '$1.49',
		imageUrl: 'https://lh3.googleusercontent.com/tbtssokxAFA_mtf6uLLv4f1ldefwB314SqAcjK1P6_kpHpICVYVSQ9_nv-jTU78kC8I9LYDJbDlhBd7_r6U',
		searchText: 'grab_bag_1_peach A peach 1.49 USD',
	},
	{
		value: 'grab_bag_1_salt_shaker',
		label: 'A salt shaker',
		amount: '1.49',
		currency: 'USD',
		helperText: '$1.49',
		imageUrl: 'https://lh3.googleusercontent.com/9LnlbkyhAIsiUKIKNr34HyfOrO--4RPstxwtlKQyGNeH_06N-Ba2ElaG8WE8o5BgubjJrM3DK8d5-TsbvM8',
		searchText: 'grab_bag_1_salt_shaker A salt shaker 1.49 USD',
	},
	{
		value: 'grab_bag_1_thumbs_down',
		label: 'A blue thumbs down with "NOPE" written on it',
		amount: '1.49',
		currency: 'USD',
		helperText: '$1.49',
		imageUrl: 'https://lh3.googleusercontent.com/4F88CkS2CGcoqowp9bjrBN0MsfsuhxGJVqnTetSf9ppas0WpH5a2OH0dKt5dUlQj47HV124dO_p8U6TOAN4',
		searchText: 'grab_bag_1_thumbs_down A blue thumbs down with "NOPE" written on it 1.49 USD',
	},
	{
		value: 'grab_bag_1_rainbow',
		label: 'A rainbow',
		amount: '1.49',
		currency: 'USD',
		helperText: '$1.49',
		imageUrl: 'https://lh3.googleusercontent.com/iStR4l8lnBa_v_V6HWFAOg8qGhDgL3TRk1peNQmQRVsI57q1O4XqmzMTKg08YSfrxN0XnOEg5BGVG2I00YM',
		searchText: 'grab_bag_1_rainbow A rainbow 1.49 USD',
	},
	{
		value: 'grab_bag_1_hotdog',
		label: 'A hotdog with ketchup',
		amount: '1.49',
		currency: 'USD',
		helperText: '$1.49',
		imageUrl: 'https://lh3.googleusercontent.com/XG0h-PzZVXv7xptZWrd9b6iv_GF2W6V1rASFaknc-Q_5iL9z_O2lto2Ly-Iw5O45qLS6Pr5FkClqIcIVYg',
		searchText: 'grab_bag_1_hotdog A hotdog with ketchup 1.49 USD',
	},
	{
		value: 'grab_bag_1_cat_v2',
		label: 'A purple cat',
		amount: '1.49',
		currency: 'USD',
		helperText: '$1.49',
		imageUrl: 'https://lh3.googleusercontent.com/2qIxdFdKKwlpGtkzQaXuoARRZqyjGfrpk8t1uJxqzi1UfBJDLEYEE0wA2jbwMXI-MI9CXQEdLawaofopEg0',
		searchText: 'grab_bag_1_cat_v2 A purple cat 1.49 USD',
	},
	{
		value: 'grab_bag_1_rose',
		label: 'A red rose',
		amount: '1.49',
		currency: 'USD',
		helperText: '$1.49',
		imageUrl: 'https://lh3.googleusercontent.com/acG-SAG7ylVgatVjcqc27fwccRYRGSp7C-uiCRYw4-2_qqcWkbjZ1g6hGy6JPd2ZNHpo5JnyfZrDRPh9VcMy',
		searchText: 'grab_bag_1_rose A red rose 1.49 USD',
	},
	{
		value: 'grab_bag_1_banana',
		label: 'A banana',
		amount: '1.49',
		currency: 'USD',
		helperText: '$1.49',
		imageUrl: 'https://lh3.googleusercontent.com/8sRNhkB6yGOqSUVd8UE4Aveg1-kkFaHH7ucqa7wydYrFGYrhB2sBfk5kAoT-AgyHX84KHNrx7lcM7WvC_NM',
		searchText: 'grab_bag_1_banana A banana 1.49 USD',
	},
	{
		value: 'grab_bag_1_banana_peel',
		label: 'A banana peel',
		amount: '1.49',
		currency: 'USD',
		helperText: '$1.49',
		imageUrl: 'https://lh3.googleusercontent.com/3-7YAyIFsXJlib7vdy3tTeKiWkJ49GK7hJMxvRWLgzyTwm2x8urOLNH6N1KMWUbX73Lh3wH63IPKMj1PZw',
		searchText: 'grab_bag_1_banana_peel A banana peel 1.49 USD',
	},
	{
		value: 'grab_bag_1_mustache_v2',
		label: 'A purple mustache',
		amount: '1.49',
		currency: 'USD',
		helperText: '$1.49',
		imageUrl: 'https://lh3.googleusercontent.com/NguWbaI8VkAwTX3qwXWrA_OJrtkRM3T1ECXzlaiTZcmtVdLa__V3ZZY0M1pcs6RHpOiPBDSZ9dPPYSjOBQ',
		searchText: 'grab_bag_1_mustache_v2 A purple mustache 1.49 USD',
	},
	{
		value: 'grab_bag_1_dog',
		label: 'A yellow dog',
		amount: '1.49',
		currency: 'USD',
		helperText: '$1.49',
		imageUrl: 'https://lh3.googleusercontent.com/tbE9pBZzE2iisT_wuVtzcmigVWQOtec1p3AVeH1t26H1BaVeGN6SO6ekz0kV8-3PucHGMOhIUEeehGtuHg',
		searchText: 'grab_bag_1_dog A yellow dog 1.49 USD',
	},
	{
		value: 'grab_bag_1_pie',
		label: 'A slice of cherry pie',
		amount: '1.49',
		currency: 'USD',
		helperText: '$1.49',
		imageUrl: 'https://lh3.googleusercontent.com/YgAHOBTParawJT3UOUWvFhroVrPD467axldWRFBRJsadh386ckdDpugbvADqfJoTA3kH9BF8jbHVXBAdt_s',
		searchText: 'grab_bag_1_pie A slice of cherry pie 1.49 USD',
	},
	{
		value: 'grab_bag_1_cake_v2',
		label: 'A slice of pink birthday cake with purple icing and a candle',
		amount: '1.49',
		currency: 'USD',
		helperText: '$1.49',
		imageUrl: 'https://lh3.googleusercontent.com/BjRTIlB_D0LuNneZdeXwIHEe7tW8eGkse2isUtxyXhdRWpR_vl-xuZB1FYUcqaTsFLs2--OjJQYRAgBbCqA',
		searchText: 'grab_bag_1_cake_v2 A slice of pink birthday cake with purple icing and a candle 1.49 USD',
	},
	{
		value: 'grab_bag_1_coin_v2',
		label: 'A coin with a star',
		amount: '1.49',
		currency: 'USD',
		helperText: '$1.49',
		imageUrl: 'https://lh3.googleusercontent.com/x26kGGmv-VZm3lBtRx4n6xkT3_SMsSNg84e7YvcAm_ZBIS9SqG_zLFIG6t-qgjdl3ixaZGMtUkpr3wv0vQ',
		searchText: 'grab_bag_1_coin_v2 A coin with a star 1.49 USD',
	},
	{
		value: 'grab_bag_1_diamond_v2',
		label: 'A sparkling diamond',
		amount: '1.49',
		currency: 'USD',
		helperText: '$1.49',
		imageUrl: 'https://lh3.googleusercontent.com/Fryc6VzC5-27CbpEeSYVeTNEW1FYkk4s_NqCmUFT4-k8vcxpdh7p6jLN2qSKRaT8lJ9nI1xlQDP13UCOHg',
		searchText: 'grab_bag_1_diamond_v2 A sparkling diamond 1.49 USD',
	},
	{
		value: 'grab_bag_1_ice_cream',
		label: 'A pink ice cream cone',
		amount: '1.49',
		currency: 'USD',
		helperText: '$1.49',
		imageUrl: 'https://lh3.googleusercontent.com/YNizykJQdIBsnKTLUJ1hI2H7n2ZI7Kntmthb49awxtCaJIFbLUjY6fduE6OyLkVl_dibFmWAHz_vtX78Htk',
		searchText: 'grab_bag_1_ice_cream A pink ice cream cone 1.49 USD',
	},
	{
		value: 'grab_bag_1_popcorn',
		label: 'A red box of popcorn',
		amount: '1.49',
		currency: 'USD',
		helperText: '$1.49',
		imageUrl: 'https://lh3.googleusercontent.com/kGTLH1GswTnrbgH_eTKYcmF8ZWZ7bVkksx_hziExoVY7lfyjTn81xkcSl2UgT0gl88rOz9edeKGJDaN1c1A',
		searchText: 'grab_bag_1_popcorn A red box of popcorn 1.49 USD',
	},
	{
		value: 'grab_bag_1_hamburger',
		label: 'A hamburger',
		amount: '1.49',
		currency: 'USD',
		helperText: '$1.49',
		imageUrl: 'https://lh3.googleusercontent.com/ngp0gBLJp_zXUdsaEoV2V2UNcZ9ngxS0nCFRNKGo6PaGGRhwV-BR6Obo7h_5m6ihkgekVCkcZ3N9GippjmWN',
		searchText: 'grab_bag_1_hamburger A hamburger 1.49 USD',
	},
	{
		value: 'grab_bag_1_dumbbell_v2',
		label: 'A dumbbell',
		amount: '1.49',
		currency: 'USD',
		helperText: '$1.49',
		imageUrl: 'https://lh3.googleusercontent.com/JOeRUwQdgDshhyOGX1sQc0xIVWWXhMX_SQssim08sVM6gpLrOS7cqsr347If8MZXY-4NLCBXwSXEoqgSTkU',
		searchText: 'grab_bag_1_dumbbell_v2 A dumbbell 1.49 USD',
	},
	{
		value: 'grab_bag_1_hearts',
		label: '3 red hearts of differing sizes',
		amount: '1.49',
		currency: 'USD',
		helperText: '$1.49',
		imageUrl: 'https://lh3.googleusercontent.com/b4iH0B4JeE2ZeX30t5Pu3JkhyyQj2Gc1o19t9Tf4pPnnMwA04w0AaBTJLKsaC31uZ3ihE4TMr6oWVBO4lg',
		searchText: 'grab_bag_1_hearts 3 red hearts of differing sizes 1.49 USD',
	},
	{
		value: 'grab_bag_1_umbrella',
		label: 'A pink umbrella on a beach',
		amount: '1.49',
		currency: 'USD',
		helperText: '$1.49',
		imageUrl: 'https://lh3.googleusercontent.com/s4WSr077EXGJByLkB21KySVeJcuCKhfKszX-eLmItL-VQl0lCn_WpsvuT9_8V7SudpaMbAnPma8mVKTfiKQ',
		searchText: 'grab_bag_1_umbrella A pink umbrella on a beach 1.49 USD',
	},
	{
		value: 'grab_bag_1_city',
		label: 'A cityscape',
		amount: '1.49',
		currency: 'USD',
		helperText: '$1.49',
		imageUrl: 'https://lh3.googleusercontent.com/j6waOxqgEb326Qvcnua0wCdFjuDPa1J5xHRFYHE7gcfN3gIx8LBj6M4JhCPzwNg6RkuYuEYOhcibRKKHh4M',
		searchText: 'grab_bag_1_city A cityscape 1.49 USD',
	},
	{
		value: 'grab_bag_1_trees',
		label: '3 evergreen trees',
		amount: '1.49',
		currency: 'USD',
		helperText: '$1.49',
		imageUrl: 'https://lh3.googleusercontent.com/LeCLE_IAIBDWnVeZzOnokFAKXU80jIqXgFWIHgwYfRGXbAA2MFiXIWnTytsOVr16bdrBejzf1jGLzXNf5TYV',
		searchText: 'grab_bag_1_trees 3 evergreen trees 1.49 USD',
	},
	{
		value: 'emoji_beaming_face',
		label: 'Beaming face with smiling eyes',
		amount: '0.99',
		currency: 'USD',
		helperText: '$0.99',
		imageUrl: 'https://lh3.googleusercontent.com/yAtGAw9ew-yy9o6oQ9EDVAfbmusNmazN-nunVbcixsmCIFER30HMdjt5nchJ6viSBuYNfrMwwBrkZ83oFA',
		searchText: 'emoji_beaming_face Beaming face with smiling eyes 0.99 USD',
	},
	{
		value: 'emoji_winking_face',
		label: 'Winking face',
		amount: '0.99',
		currency: 'USD',
		helperText: '$0.99',
		imageUrl: 'https://lh3.googleusercontent.com/GnFvdD9mlTgzcfR89wULMCM03Q-FqsSGUZ1sHO_qXX5fh7mqr-868gHNl3rpoxpal4Pc4ikhgFQ16Z0GMw',
		searchText: 'emoji_winking_face Winking face 0.99 USD',
	},
	{
		value: 'emoji_sunglasses_face',
		label: 'Smiling face with sunglasses',
		amount: '0.99',
		currency: 'USD',
		helperText: '$0.99',
		imageUrl: 'https://lh3.googleusercontent.com/Kr0buuCDwGzC_VXTXiF0owRaMPsX-Tzg80Q9TC4XsdwLrj7ZqijDorMzTsgQnymbnwdudh7FsokGYa0zeO6x',
		searchText: 'emoji_sunglasses_face Smiling face with sunglasses 0.99 USD',
	},
	{
		value: 'emoji_heart_face',
		label: 'Smiling face with heart-eyes',
		amount: '0.99',
		currency: 'USD',
		helperText: '$0.99',
		imageUrl: 'https://lh3.googleusercontent.com/jQ3s4VHdriiuVFFRlfhAThFBUS0mScp2iJgAfYh6LIIn9K5849FSE_di8QJk_gKZEOqJqjHLHnB5Efvxc-I',
		searchText: 'emoji_heart_face Smiling face with heart-eyes 0.99 USD',
	},
	{
		value: 'emoji_money_face',
		label: 'Money-mouth face',
		amount: '0.99',
		currency: 'USD',
		helperText: '$0.99',
		imageUrl: 'https://lh3.googleusercontent.com/uimZTz5ijPAGLvJyA1dOW8VIdlPsyVHxqETgB0Fa17rMs35ZgoD_fUJ0lsh_Oh28r13N-8RJP5XZCF3eRw',
		searchText: 'emoji_money_face Money-mouth face 0.99 USD',
	},
	{
		value: 'emoji_poop_face',
		label: 'A pile of poop with a face',
		amount: '0.99',
		currency: 'USD',
		helperText: '$0.99',
		imageUrl: 'https://lh3.googleusercontent.com/kgcJnLI6rRPD1Jm7xko7FNnl0k9qVFGzNvu8TmtTcAs4vHwigbTfa0N7N98r1TfqUPfHfRRln47UiRbeCr3Z',
		searchText: 'emoji_poop_face A pile of poop with a face 0.99 USD',
	},
	{
		value: 'emoji_one_hundred',
		label: '100 underlined twice',
		amount: '0.99',
		currency: 'USD',
		helperText: '$0.99',
		imageUrl: 'https://lh3.googleusercontent.com/sE214N2V_KPOY00qwan1wn1xnI3Rf1OzEtA9T_iImdoS7toVw8PWMS_4YH7gS975SgCxiATt6jxgp-YJ830',
		searchText: 'emoji_one_hundred 100 underlined twice 0.99 USD',
	},
	{
		value: 'emoji_thinking_face',
		label: 'Thinking face',
		amount: '0.99',
		currency: 'USD',
		helperText: '$0.99',
		imageUrl: 'https://lh3.googleusercontent.com/03Uh55eQVzrjor1utm_sUp50apHhXmeTq27iGc6mgvORwhrejife2n4FmQBqCW5tREIJBRNiKLLmQr5EZQ',
		searchText: 'emoji_thinking_face Thinking face 0.99 USD',
	},
	{
		value: 'emoji_expressionless_face',
		label: 'Expressionless face',
		amount: '0.99',
		currency: 'USD',
		helperText: '$0.99',
		imageUrl: 'https://lh3.googleusercontent.com/eRnFs8HtnTaAjejVy_5U9f-YLOGpxbVOpRdoDfevxweXtx1jLjOFPn35qvaBapYCRQIfw9lLfk8Qfu-C0i4',
		searchText: 'emoji_expressionless_face Expressionless face 0.99 USD',
	},
	{
		value: 'emoji_mouthless_face',
		label: 'Face without mouth',
		amount: '0.99',
		currency: 'USD',
		helperText: '$0.99',
		imageUrl: 'https://lh3.googleusercontent.com/xU6N4RaZgfBOF5cmmR47nIZJPjIok7v54wyZetN1pcdSHwhFkdkABBOxj7WHECu8lC5t_ZZTdcOO2KdXHQ',
		searchText: 'emoji_mouthless_face Face without mouth 0.99 USD',
	},
	{
		value: 'emoji_anxious_face',
		label: 'Anxious Face With Sweat',
		amount: '0.99',
		currency: 'USD',
		helperText: '$0.99',
		imageUrl: 'https://lh3.googleusercontent.com/yuXGjsVf6AxxV0yVYCUI9ENleLYWE-EvhXGt8CuTKQeM8085m-2hB4A0TnXwBdxJGOaEgPJxjwYapt34KHY',
		searchText: 'emoji_anxious_face Anxious Face With Sweat 0.99 USD',
	},
	{
		value: 'emoji_sleeping_face',
		label: 'Sleeping face',
		amount: '0.99',
		currency: 'USD',
		helperText: '$0.99',
		imageUrl: 'https://lh3.googleusercontent.com/gYUVO_6_yuSW2UBihm6Sy6eJtPhSnkf1IrmJ2sjFmW74kzh9ISFkye7N0npF2WpSjUIQTT2XrNSttdBreJo',
		searchText: 'emoji_sleeping_face Sleeping face 0.99 USD',
	},
	{
		value: 'emoji_astonished_face',
		label: 'Astonished face',
		amount: '0.99',
		currency: 'USD',
		helperText: '$0.99',
		imageUrl: 'https://lh3.googleusercontent.com/IfmSWx-VFoP8uTSSMqiz47ZwWmOGC_ueQ8mZjRwXu74ZIXZA-LQ6zEU2onUwdFEkaic024KIIsPfdt-RXQ',
		searchText: 'emoji_astonished_face Astonished face 0.99 USD',
	},
	{
		value: 'emoji_drooling_face',
		label: 'Drooling face',
		amount: '0.99',
		currency: 'USD',
		helperText: '$0.99',
		imageUrl: 'https://lh3.googleusercontent.com/5qs_bwK8CsKAiwwXnD65PwYEt641PMrVDJ7wlYj5OpBAz1OwIoJ0LRnJDEFEGypZdtnIVsC5nnHRPgZiMowc',
		searchText: 'emoji_drooling_face Drooling face 0.99 USD',
	},
	{
		value: 'emoji_vomiting_face',
		label: 'Face vomiting',
		amount: '0.99',
		currency: 'USD',
		helperText: '$0.99',
		imageUrl: 'https://lh3.googleusercontent.com/oG4xFy5BO6Mhc3KZna2VifxqSmOYmCJ5jirJrD5FQVB4fqYL_eAKZ52S9fsN5DcCpr8Yp3pL_I01ULz4aNI',
		searchText: 'emoji_vomiting_face Face vomiting 0.99 USD',
	},
	{
		value: 'emoji_screaming_face',
		label: 'Face screaming in fear',
		amount: '0.99',
		currency: 'USD',
		helperText: '$0.99',
		imageUrl: 'https://lh3.googleusercontent.com/xFALl3j_3ZaRkvgucOw-11IuVPtTk8MYOWfNH4Ba4frclWSIxqiyWGBZHENqsv1pFBH8MX9fKvHx2dTTjxU',
		searchText: 'emoji_screaming_face Face screaming in fear 0.99 USD',
	},
	{
		value: 'emoji_steamed_face',
		label: 'Face with steam from nose',
		amount: '0.99',
		currency: 'USD',
		helperText: '$0.99',
		imageUrl: 'https://lh3.googleusercontent.com/cRmnz_OL0-JxITld2ll_j210NhBcu81WvYSnHcLbyl-ry0v3ixqSgDTHjjNuOagy5zQS53udvUg_jo9sMVU',
		searchText: 'emoji_steamed_face Face with steam from nose 0.99 USD',
	},
	{
		value: 'emoji_angry_face',
		label: 'Angry face',
		amount: '0.99',
		currency: 'USD',
		helperText: '$0.99',
		imageUrl: 'https://lh3.googleusercontent.com/FRBcO0bhH0WRSX3cosVK0H-366_2S5yAHFZDiqtF-8IV1_WqMLqfarHM7wOAxOBxfx8aTzOfbHBX9Y3-4w',
		searchText: 'emoji_angry_face Angry face 0.99 USD',
	},
	{
		value: 'emoji_devil_face',
		label: 'Smiling face with horns',
		amount: '0.99',
		currency: 'USD',
		helperText: '$0.99',
		imageUrl: 'https://lh3.googleusercontent.com/1_MfYzC_HTHyxQyp_PGiOewATOHlpowG8K5xy2Ew0lrIpO0SHiQs3Sd-L3as9pnNixTPSQo3VILRcNtAUYQ',
		searchText: 'emoji_devil_face Smiling face with horns 0.99 USD',
	},
	{
		value: 'emoji_angel_face',
		label: 'Smiling face with halo',
		amount: '0.99',
		currency: 'USD',
		helperText: '$0.99',
		imageUrl: 'https://lh3.googleusercontent.com/R91GUP-aqeMbN33DS7b_oxRjfB2gmtVCZr733zWetlBnDYm_vuCGdgvr1y9jqhviBJXLw5bjnzQQqC4M_lWj',
		searchText: 'emoji_angel_face Smiling face with halo 0.99 USD',
	},
	{
		value: 'emoji_sad_face',
		label: 'Frowning face',
		amount: '0.99',
		currency: 'USD',
		helperText: '$0.99',
		imageUrl: 'https://lh3.googleusercontent.com/8vp984AxvRZYLNOzp9l8sG_-sOAwkLY9xU6i56h5qVUUThb8X8XscMnd9ZeBl3-g_6xATCU8TNFewdEeSUo',
		searchText: 'emoji_sad_face Frowning face 0.99 USD',
	},
	{
		value: 'emoji_crying_face',
		label: 'Loudly crying face',
		amount: '0.99',
		currency: 'USD',
		helperText: '$0.99',
		imageUrl: 'https://lh3.googleusercontent.com/aiRqKeOZBt3YEmL8SIoO-0almokONqzYw0FD6K4VQOCZFZ5rIV3I8IJ8BLz57QZfDV3b4wMyCbS9Z-faJfM',
		searchText: 'emoji_crying_face Loudly crying face 0.99 USD',
	},
	{
		value: 'emoji_dizzy_face',
		label: 'Dizzy face',
		amount: '0.99',
		currency: 'USD',
		helperText: '$0.99',
		imageUrl: 'https://lh3.googleusercontent.com/qI1nakkeortf5qi4EX8wZiRapizSONpIKf8pTdihTW9DhNX9n26t4Y3xa_0-MZBGyQ4TrEKc1pTQxfJH6LY',
		searchText: 'emoji_dizzy_face Dizzy face 0.99 USD',
	},
	{
		value: 'emoji_upside_down_face',
		label: 'Upside down face',
		amount: '0.99',
		currency: 'USD',
		helperText: '$0.99',
		imageUrl: 'https://lh3.googleusercontent.com/47NnZDn6_Mo747LN9QMSIvM-PEOUUNJdwxsJ3Tvlem_m1GNYP9jB4z1_LK5Hj0V0Mx75MgamAENsg2t4qlU',
		searchText: 'emoji_upside_down_face Upside down face 0.99 USD',
	},
	{
		value: 'masher_gg_thumbs_up',
		label: 'Video game controller gives a thumbs up and says "GG"',
		amount: '2.00',
		currency: 'USD',
		helperText: '$2.00',
		imageUrl: 'https://lh3.googleusercontent.com/fxpn6BjHNVZBeeWA2SHSa6K4XFvrhVg1K1yDxdlL9bFuc9rRxkwBrNN2ASAZLQa3ZCkYshvO2rqiznfSVA',
		searchText: 'masher_gg_thumbs_up Video game controller gives a thumbs up and says "GG" 2.00 USD',
	},
	{
		value: 'masher_glhf',
		label: "Video game controller spins around as the word 'GLHF' appears behind",
		amount: '2.00',
		currency: 'USD',
		helperText: '$2.00',
		imageUrl: 'https://lh3.googleusercontent.com/A7uKIHwpRemVJPl5tfzj0oKDYfsqOTldI4ZHpXDAjm1SO8_O3uCLoICNVVOryKWm9384Ubqy_jmEG_HyFACo',
		searchText: "masher_glhf Video game controller spins around as the word 'GLHF' appears behind 2.00 USD",
	},
	{
		value: 'masher_jumping',
		label: 'Video game controller jumps up and down excitedly',
		amount: '5.00',
		currency: 'USD',
		helperText: '$5.00',
		imageUrl: 'https://lh3.googleusercontent.com/87X3pbYA7KFeJiFR3jB8vHX67g75Gm5SzEWRmMHK7h4GdMWvr1vqxPbghlJvp7ds_6lhy7kVgVg8Erroqw0',
		searchText: 'masher_jumping Video game controller jumps up and down excitedly 5.00 USD',
	},
	{
		value: 'masher_broken_arm',
		label: 'Video game controller hobbles along unhappily with a broken arm',
		amount: '5.00',
		currency: 'USD',
		helperText: '$5.00',
		imageUrl: 'https://lh3.googleusercontent.com/PuQjYs_zVY4FxyKG31eVDs1kRhHZXXl5BN9MAGgamWSiLYpeUcFNhyCmGh4c6IMrXAvUnmyLVtZWJVqsB8s',
		searchText: 'masher_broken_arm Video game controller hobbles along unhappily with a broken arm 5.00 USD',
	},
	{
		value: 'masher_noob',
		label: "Baby video game controller sits in a diaper under the word 'Noob'",
		amount: '5.00',
		currency: 'USD',
		helperText: '$5.00',
		imageUrl: 'https://lh3.googleusercontent.com/qFMEkSOH7SPgNZKDHuuk-DLnBhh8JBIfXcswFaU01_XLKzVej9KSLbUoZDN-bfnR72NTxaWXC5Wa4V6MPQ',
		searchText: "masher_noob Baby video game controller sits in a diaper under the word 'Noob' 5.00 USD",
	},
	{
		value: 'masher_try_again',
		label: "Video game controller looks forlorn in between the words 'Try again'",
		amount: '5.00',
		currency: 'USD',
		helperText: '$5.00',
		imageUrl: 'https://lh3.googleusercontent.com/cGURv7bBTnUVSEzo9gcW1apZZznXzk4CV6jzrlT3tmhNBERIBRnvNwYQQKTcjo6MamLtAjaXUY_DrJ6wbx8',
		searchText: "masher_try_again Video game controller looks forlorn in between the words 'Try again' 5.00 USD",
	},
	{
		value: 'masher_critical_hit',
		label: "Video game controller poses triumphantly in between the words 'Critical Hit!'",
		amount: '5.00',
		currency: 'USD',
		helperText: '$5.00',
		imageUrl: 'https://lh3.googleusercontent.com/I3ZXOQj8Jt0NqhpIWxANO8wrk2darynI6skHOHlL6cO5VSQbQtSQN_P73rsXQcUlGEJ8PV551Wrj8eVQryE',
		searchText: "masher_critical_hit Video game controller poses triumphantly in between the words 'Critical Hit!' 5.00 USD",
	},
	{
		value: 'masher_level_up',
		label: "Video game controller evolves into a muscled version of itself under the word 'LVL+'",
		amount: '10.00',
		currency: 'USD',
		helperText: '$10.00',
		imageUrl: 'https://lh3.googleusercontent.com/rl_D9CbL1VXcyUXPxGm9YahzHGkKbuF96ZGFDAXv9L_IlwQkCnLfhREiVAffbEP3dL8PGApByNiEIabGAH8',
		searchText: "masher_level_up Video game controller evolves into a muscled version of itself under the word 'LVL+' 10.00 USD",
	},
	{
		value: 'masher_sunglasses',
		label: "Sunglasses perpetually fall onto video game controller's proud face",
		amount: '10.00',
		currency: 'USD',
		helperText: '$10.00',
		imageUrl: 'https://lh3.googleusercontent.com/7NUanCM7WTzYks25uS2uYxdMLzKo09_p5IKE--vikS7FYXyRFDzIUQt0L7QIdKm3nxMDcRBhp0NNFAdDbQ',
		searchText: "masher_sunglasses Sunglasses perpetually fall onto video game controller's proud face 10.00 USD",
	},
	{
		value: 'masher_woot',
		label: "Video game controller dances goofily under the word 'Woot'",
		amount: '20.00',
		currency: 'USD',
		helperText: '$20.00',
		imageUrl: 'https://lh3.googleusercontent.com/feAVtS9aF4EgKoYZR-j9ab75-P4qrE5rEjCYNuF3lmzxU6L0iInf4WSpLdpXmXuxDaUHWgUbW_NaopWFyw',
		searchText: "masher_woot Video game controller dances goofily under the word 'Woot' 20.00 USD",
	},
	{
		value: 'masher_rage_quit',
		label: "Video game controller throws a facedown tantrum in between the words 'Rage Quit'",
		amount: '20.00',
		currency: 'USD',
		helperText: '$20.00',
		imageUrl: 'https://lh3.googleusercontent.com/-6U5kOQo9-blpNhv5TkTkhLLZitaaUc7cueU1VKUl9g2QBbwwL9akKJGe6YfPWzcz_KTi793LQq8bJe9PfM',
		searchText: "masher_rage_quit Video game controller throws a facedown tantrum in between the words 'Rage Quit' 20.00 USD",
	},
	{
		value: 'masher_super_effective',
		label: "Video game controller punches and kicks in between the words 'Super Effective'",
		amount: '50.00',
		currency: 'USD',
		helperText: '$50.00',
		imageUrl: 'https://lh3.googleusercontent.com/WRST9d-NTu-wHbgIsiLwkU9VcooInpgJU0rlWpkA8AIVhg9aVm1vmFvSs1tHcTlWsSLSDFNOvl4ljedWWvoE',
		searchText: "masher_super_effective Video game controller punches and kicks in between the words 'Super Effective' 50.00 USD",
	},
];
