export const YoutubeSuperstickersData = [
	{
		value: 'pearfect_hey_you_ja_v2',
		label: "Pear character turning around waving his hand, saying 'Hey you' while lowering his glasses",
		amount: '2.00',
		currency: 'USD',
	},
	{
		value: 'pearfect_cool_ja_v2',
		label: "Pear character doing a shaka sign with his hand saying 'Cool'",
		amount: '2.00',
		currency: 'USD',
	},
	{
		value: 'pearfect_blush_v2',
		label: 'Pear character putting his hand in front of his mouth while blushing',
		amount: '2.00',
		currency: 'USD',
	},
	{
		value: 'pearfect_fist_bump_ja_v2',
		label: "Pear character punching the air with 'Fist' and 'Bump' written on his knuckles",
		amount: '3.00',
		currency: 'USD',
	},
	{
		value: 'pearfect_thumbs_up_v2',
		label: 'Pear character stretching his arm forward raising his thumb up',
		amount: '3.00',
		currency: 'USD',
	},
	{
		value: 'pearfect_blowing_hearts_v2',
		label: 'Pear character with lovey dovey eyes blowing red hearts in the air',
		amount: '3.00',
		currency: 'USD',
	},
	{
		value: 'pearfect_offer_coffee_v2',
		label: 'Pear character exaggeratedly stretching his arm forward to offer a cup of coffee',
		amount: '4.00',
		currency: 'USD',
	},
	{
		value: 'pearfect_lol_ja_v2',
		label: 'Pear character holding his belly laughing out loud',
		amount: '5.00',
		currency: 'USD',
	},
	{
		value: 'pearfect_hows_it_going_ja_v2',
		label: "Pear character lying on the side, raising his arm while saying 'How's it going?'",
		amount: '5.00',
		currency: 'USD',
	},
	{
		value: 'pearfect_horn_v2',
		label: 'Pear character cheerfully blowing a party horn',
		amount: '5.00',
		currency: 'USD',
	},
	{
		value: 'pearfect_mic_drop_v2',
		label: 'Pear character doing a classic mic drop',
		amount: '5.00',
		currency: 'USD',
	},
	{
		value: 'pearfect_keep_it_up_ja_v2',
		label: "Pear character lifting some weights saying 'Keep it up'",
		amount: '5.00',
		currency: 'USD',
	},
	{
		value: 'pearfect_flying_v2',
		label: 'Pear character flying in the air with a red cape and a smile on his face',
		amount: '10.00',
		currency: 'USD',
	},
	{
		value: 'pearfect_number_1_fan_ja_v2',
		label: "Pear character jumping up and down saying '#1 Fan'",
		amount: '10.00',
		currency: 'USD',
	},
	{
		value: 'pearfect_thank_you_ja_v2',
		label: "Pear character bowing down saying 'Thank you'",
		amount: '10.00',
		currency: 'USD',
	},
	{
		value: 'pearfect_rofl',
		label: 'Pear character rolling on the floor laughing',
		amount: '10.00',
		currency: 'USD',
	},
	{
		value: 'pearfect_goal_ja_v2',
		label: 'Pear character sliding on the floor on his knees saying "GOAL"',
		amount: '20.00',
		currency: 'USD',
	},
	{
		value: 'pearfect_thanks_heart_mirror_ja_v2',
		label: "Pear character looking at himself in the mirror, saying 'Thanks for being you' with hearts popping out of his eyes",
		amount: '20.00',
		currency: 'USD',
	},
	{
		value: 'pearfect_you_are_amazing_ja_v2',
		label: "Pear character dancing under a rain of confetti and taking his hat off to say 'You are amazing'",
		amount: '20.00',
		currency: 'USD',
	},
	{
		value: 'pearfect_building_riot_v2',
		label: 'Giant Pear character waving flags and turning around, making the buildings in front of him tremble',
		amount: '50.00',
		currency: 'USD',
	},
	{
		value: 'pearfect_ride_rocket_explode',
		label: 'Pear character riding a firework rocket disappearing away before bursting in the sky',
		amount: '50.00',
		currency: 'USD',
	},
	{
		value: 'hi_po_po_1up',
		label: 'A pixelated hippo chomps on a 1up',
		amount: '2.00',
		currency: 'USD',
	},
	{
		value: 'hi_po_po_game_over_v2',
		label: "A ghost of our hippo character floats in front of the words 'Game Over'",
		amount: '2.00',
		currency: 'USD',
	},
	{
		value: 'hi_po_po_next_time_v2',
		label: "Hippo character waves goodbye with the words 'Next Time' behind him",
		amount: '3.00',
		currency: 'USD',
	},
	{
		value: 'hi_po_po_pilot_gesture',
		label: 'Hippo character in tactical gear does tactical flanking maneuver hand gestures',
		amount: '3.00',
		currency: 'USD',
	},
	{
		value: 'hi_po_po_collar_tug',
		label: 'Hippo character waves his hand in front of his neck with an awkward look on his face to signal that the player is done',
		amount: '4.00',
		currency: 'USD',
	},
	{
		value: 'hi_po_po_omg',
		label: 'Hippo character smacks his hands onto his face and looks around to see if anyone saw what he just saw',
		amount: '4.00',
		currency: 'USD',
	},
	{
		value: 'hi_po_po_hype_v2',
		label: "Hippo character with stars growing in his eyes, pumping his arms in the air with the word 'Hype' pulsating above him",
		amount: '5.00',
		currency: 'USD',
	},
	{
		value: 'hi_po_po_git_gud_v2',
		label: "Hippo character repeatedly points to the streamer while chanting 'Git Gud'",
		amount: '5.00',
		currency: 'USD',
	},
	{
		value: 'hi_po_po_gg',
		label: 'Hippo character applauds whilst nodding in approval, saying ‘GG’',
		amount: '5.00',
		currency: 'USD',
	},
	{
		value: 'hi_po_po_running_fast_v2',
		label: 'Hippo character runs at high speed, his legs forming a ball-like blur',
		amount: '5.00',
		currency: 'USD',
	},
	{
		value: 'hi_po_po_squad',
		label: "Hippo character's head pops out of water, surounded by his hippo squad",
		amount: '5.00',
		currency: 'USD',
	},
	{
		value: 'hi_po_po_chair_spin_yay',
		label: 'Hippo character spins around in his chair, arms flung up in the air',
		amount: '10.00',
		currency: 'USD',
	},
	{
		value: 'hi_po_po_ko_uppercut_v2',
		label: "Hippo character throwing a blazing upper cut into the air while the word 'KO' appears in the background",
		amount: '10.00',
		currency: 'USD',
	},
	{
		value: 'hi_po_po_chair_drift',
		label: 'Hippo character going really fast on his chair, propelling the chair across the room',
		amount: '10.00',
		currency: 'USD',
	},
	{
		value: 'hi_po_po_rekt_v2',
		label: "Hippo character collapses to the ground as his chair breaks, while the words 'REKT' appear above him",
		amount: '10.00',
		currency: 'USD',
	},
	{
		value: 'hi_po_po_backwards_hat_thumbs_up_v2',
		label: 'Hippo character with a pink hat, flips it backward and raises his thumb up in the air',
		amount: '10.00',
		currency: 'USD',
	},
	{
		value: 'hi_po_po_op_v2',
		label: "Hippo character stands idle whilst his new and most powerful body attachments do their thing, with the word 'OP' in the background",
		amount: '20.00',
		currency: 'USD',
	},
	{
		value: 'hi_po_po_victory_v2',
		label: "Hippo character flips around and does a V sign with his hand while the word 'Victory' appears in the background",
		amount: '20.00',
		currency: 'USD',
	},
	{
		value: 'hi_po_po_epic_fail_v2',
		label: "Hippo character falling to the ground in a dramatic way, bursting into tears with the words 'Epic Fail' in the background",
		amount: '20.00',
		currency: 'USD',
	},
	{
		value: 'hi_po_po_tossing_money',
		label: 'Hippo character wearing cool sunglasses comes out of a treasure chest tossing coins around him',
		amount: '50.00',
		currency: 'USD',
	},
	{
		value: 'hi_po_po_mecha_transform_v2',
		label: 'Hippo character sitting into an office chair, when they both transform into a mecha chair / hippo hero',
		amount: '50.00',
		currency: 'USD',
	},
	{
		value: 'bushiba_heart_wobble',
		label: 'Shiba dog shaking his body from left to right, surrounded by red hearts',
		amount: '2.00',
		currency: 'USD',
	},
	{
		value: 'bushiba_head_tilt',
		label: 'Shiba dog with a big smile on his face, tilting his head',
		amount: '2.00',
		currency: 'USD',
	},
	{
		value: 'bushiba_number_one',
		label: 'Shiba dog raises and lowers his index finger to get noticed',
		amount: '2.00',
		currency: 'USD',
	},
	{
		value: 'bushiba_greeting',
		label: "Shiba dog raising an arm to greet someone, asking 'How is it going?'",
		amount: '3.00',
		currency: 'USD',
	},
	{
		value: 'bushiba_goodbye',
		label: 'Shiba dog moves his arm saying goodbye',
		amount: '3.00',
		currency: 'USD',
	},
	{
		value: 'bushiba_massage_cheeks',
		label: 'Shiba dog happily massaging his cheeks with his mouth wide open',
		amount: '3.00',
		currency: 'USD',
	},
	{
		value: 'bushiba_hero',
		label: "Shiba dog with sparkles in his eyes saying 'My hero'",
		amount: '3.00',
		currency: 'USD',
	},
	{
		value: 'bushiba_bone_bow',
		label: 'Shiba dog gifting a large bone, bowing respectfully',
		amount: '4.00',
		currency: 'USD',
	},
	{
		value: 'bushiba_blush_laugh',
		label: 'Shiba dog laughing slightly while blushing and covering his mouth with one arm',
		amount: '5.00',
		currency: 'USD',
	},
	{
		value: 'bushiba_bow',
		label: 'Shiba dog bowing respectfully',
		amount: '5.00',
		currency: 'USD',
	},
	{
		value: 'bushiba_clapping',
		label: 'Shiba dog clapping his hands',
		amount: '5.00',
		currency: 'USD',
	},
	{
		value: 'bushiba_hey_you',
		label: "Shiba dog saying 'Hey you', greeting joyfully",
		amount: '5.00',
		currency: 'USD',
	},
	{
		value: 'bushiba_combat',
		label: 'Shiba dog in a combat position',
		amount: '5.00',
		currency: 'USD',
	},
	{
		value: 'bushiba_number_one_paper',
		label: "Shiba dog writing with a brush, writing 'Number 1' on a piece of paper",
		amount: '5.00',
		currency: 'USD',
	},
	{
		value: 'bushiba_thumbs_up',
		label: "Shiba dog saying 'Good job' while raising his thumb up",
		amount: '5.00',
		currency: 'USD',
	},
	{
		value: 'bushiba_fan_wave',
		label: 'Shiba dog dressed in a traditional outfit waving Japanese fans',
		amount: '10.00',
		currency: 'USD',
	},
	{
		value: 'bushiba_rofl',
		label: 'Shiba dog rolling on the floor, laughing out loud',
		amount: '10.00',
		currency: 'USD',
	},
	{
		value: 'bushiba_good_luck',
		label: 'Shiba dog shouting good luck in a megaphone',
		amount: '10.00',
		currency: 'USD',
	},
	{
		value: 'bushiba_squeeze_heart',
		label: 'Shiba dog squeezing a big red heart',
		amount: '10.00',
		currency: 'USD',
	},
	{
		value: 'bushiba_thank_you',
		label: "Shiba dog shaking his hips saying 'Thank you'",
		amount: '10.00',
		currency: 'USD',
	},
	{
		value: 'bushiba_samurai_trophy',
		label: 'Shiba dog in samurai armor holding a golden trophy',
		amount: '20.00',
		currency: 'USD',
	},
	{
		value: 'bushiba_samurai_number_one_flag',
		label: 'Shiba dog in samurai armour, waving a banner saying #1',
		amount: '20.00',
		currency: 'USD',
	},
	{
		value: 'bushiba_samurai_amazing',
		label: "Shiba dog wearing samurai armor writing 'You're amazing' in the air with sparklers",
		amount: '50.00',
		currency: 'USD',
	},
	{
		value: 'bushiba_fireworks',
		label: 'Shiba dog jumping in the air with fireworks around him',
		amount: '50.00',
		currency: 'USD',
	},
	{
		value: 'biggest_fans_heart_shaped_sunglasses_lowered_stare',
		label: 'Fan character wearing heart shaped sunglasses',
		amount: '2.00',
		currency: 'USD',
	},
	{
		value: 'biggest_fans_hand_pick_me_ja',
		label: 'Character waving their hand saying "Me!"',
		amount: '2.00',
		currency: 'USD',
	},
	{
		value: 'biggest_fans_fist_bump_handshake',
		label: 'Hands doing a fist bump',
		amount: '2.00',
		currency: 'USD',
	},
	{
		value: 'biggest_fans_brb_ja',
		label: 'A post it note with the text "I\'ll be back" appearing on it',
		amount: '3.00',
		currency: 'USD',
	},
	{
		value: 'biggest_fans_how_you_doing_jp_v2',
		label: 'Character holding their head in their hand saying "How is it going?"',
		amount: '3.00',
		currency: 'USD',
	},
	{
		value: 'biggest_fans_hands_horn_sign',
		label: 'Hands doing the sign of the horns with sparkles around',
		amount: '3.00',
		currency: 'USD',
	},
	{
		value: 'biggest_fans_thumbs_up_ja',
		label: 'A thumps-up hand gesture with the words "Top!"',
		amount: '3.00',
		currency: 'USD',
	},
	{
		value: 'biggest_fans_have_some_coffee_jp_v2',
		label: 'Character handing over a cup of coffee saying "For you"',
		amount: '4.00',
		currency: 'USD',
	},
	{
		value: 'biggest_fans_lol_cry_ja',
		label: 'Fan character laughing out loud, with tears in their eyes',
		amount: '5.00',
		currency: 'USD',
	},
	{
		value: 'biggest_fans_head_in_hands_heart_wink_ja',
		label: 'Character holding their head in their hands, saying "You\'re my #1"',
		amount: '5.00',
		currency: 'USD',
	},
	{
		value: 'biggest_fans_whoa_shake_head_ja',
		label: 'Character looking really impressed saying "Whoa"',
		amount: '5.00',
		currency: 'USD',
	},
	{
		value: 'biggest_fans_flex_bicep_you_rock_jp_v2',
		label: 'Character saying "You rock" whilst showing their pumped bicep',
		amount: '5.00',
		currency: 'USD',
	},
	{
		value: 'biggest_fans_hiya_jp_v2',
		label: 'Character appearing from behind a cloud saying "Hiya"',
		amount: '5.00',
		currency: 'USD',
	},
	{
		value: 'biggest_fans_hands_high_five',
		label: 'Hands doing a high five',
		amount: '5.00',
		currency: 'USD',
	},
	{
		value: 'biggest_fans_face_in_hands_incredible_ja',
		label: 'Character holding their head in their hands saying "Incredible"',
		amount: '5.00',
		currency: 'USD',
	},
	{
		value: 'biggest_fans_blush_v2',
		label: 'Fan character with eyes wide open, blushing',
		amount: '10.00',
		currency: 'USD',
	},
	{
		value: 'biggest_fans_rofl_fist_pound_ja',
		label: 'Character on the floor laughing really hard',
		amount: '10.00',
		currency: 'USD',
	},
	{
		value: 'biggest_fans_clasp_hands_thanks_jp_v2',
		label: 'Character holding their hands together saying "Thanks"',
		amount: '10.00',
		currency: 'USD',
	},
	{
		value: 'biggest_fans_cheerleader_air_jump',
		label: 'Fan character dressed as a cheerleader jumping in the air',
		amount: '10.00',
		currency: 'USD',
	},
	{
		value: 'biggest_fans_jump_hurray_jp_v2',
		label: 'Character jumping in the air joyfully, saying "Yippee"',
		amount: '10.00',
		currency: 'USD',
	},
	{
		value: 'biggest_fans_heart_hands_v2',
		label: 'Fan character sending hearts with their hands',
		amount: '20.00',
		currency: 'USD',
	},
	{
		value: 'biggest_fans_ponytail_heart_star_eyes_v2',
		label: 'Fan character bouncing their heart shaped ponytail, with stars in their eye',
		amount: '20.00',
		currency: 'USD',
	},
	{
		value: 'biggest_fans_cheerleader_jumps_in_front_of_heart',
		label: 'Fan character jumping in the air in front of a big red heart with pompom in their hands',
		amount: '50.00',
		currency: 'USD',
	},
	{
		value: 'biggest_fans_fireworks_sunglass_amazed',
		label: 'Fan character wearing sunglasses with fireworks appearing on the lenses',
		amount: '50.00',
		currency: 'USD',
	},
	{
		value: 'energetic_lemon_and_baby_lemon_superhero',
		label: 'Baby Lemon looking up to our lemon character standing in a super hero position',
		amount: '2.00',
		currency: 'USD',
	},
	{
		value: 'energetic_lemon_and_baby_lemon_running_kneel',
		label: 'Lemon character running then kneeling on the floor, his arms wide open and a slice of lemon appearing behind him',
		amount: '2.00',
		currency: 'USD',
	},
	{
		value: 'energetic_lemon_and_baby_lemon_blow_heart',
		label: 'Lemon character blowing a big red heart',
		amount: '2.00',
		currency: 'USD',
	},
	{
		value: 'energetic_lemon_and_baby_lemon_wave_hello',
		label: 'Lemon character waving his arm to say hello with his mouth open',
		amount: '3.00',
		currency: 'USD',
	},
	{
		value: 'energetic_lemon_and_baby_lemon_wink_goodbye',
		label: 'Lemon character waving goodbye while winking and sending a shooting star',
		amount: '3.00',
		currency: 'USD',
	},
	{
		value: 'energetic_lemon_and_baby_lemon_two_thumbs_up',
		label: 'Lemon character raising both his thumbs up',
		amount: '3.00',
		currency: 'USD',
	},
	{
		value: 'energetic_lemon_and_baby_lemon_cheerleading',
		label: 'Baby Lemon with pom poms in his hands, cheerleading',
		amount: '3.00',
		currency: 'USD',
	},
	{
		value: 'energetic_lemon_and_baby_lemon_gift',
		label: 'Lemon character offering a gift to Baby Lemon',
		amount: '4.00',
		currency: 'USD',
	},
	{
		value: 'energetic_lemon_and_baby_lemon_hehe',
		label: 'Lemon character holding his hand in front of his mouth, grinning',
		amount: '5.00',
		currency: 'USD',
	},
	{
		value: 'energetic_lemon_and_baby_lemon_heart_eyes',
		label: 'Lemon character moving his head from left to right with his mouth wide open and red hearts in his eyes',
		amount: '5.00',
		currency: 'USD',
	},
	{
		value: 'energetic_lemon_and_baby_lemon_lift_congratulate',
		label: 'Lemon character lifting Baby Lemon in the air to congratulate him',
		amount: '5.00',
		currency: 'USD',
	},
	{
		value: 'energetic_lemon_and_baby_lemon_sunglass_greeting',
		label: 'Lemon character taking his sunglasses off and raising his arm to greet someone, imitated by Baby Lemon',
		amount: '5.00',
		currency: 'USD',
	},
	{
		value: 'energetic_lemon_and_baby_lemon_horns',
		label: 'Lemon character and Baby Lemon blowing a party horn while marching',
		amount: '5.00',
		currency: 'USD',
	},
	{
		value: 'energetic_lemon_and_baby_lemon_high_five',
		label: 'Lemon character and Baby Lemon jumping in the air to do a high five',
		amount: '5.00',
		currency: 'USD',
	},
	{
		value: 'energetic_lemon_and_baby_lemon_shimmy',
		label: 'Lemon character doing shoulder shimmy dance moves',
		amount: '5.00',
		currency: 'USD',
	},
	{
		value: 'energetic_lemon_and_baby_lemon_heart_thump',
		label: 'Lemon character jumping in excitement with his heart beating out of his chest',
		amount: '10.00',
		currency: 'USD',
	},
	{
		value: 'energetic_lemon_and_baby_lemon_lol',
		label: 'Lemon character laughing out loud',
		amount: '10.00',
		currency: 'USD',
	},
	{
		value: 'energetic_lemon_and_baby_lemon_yay',
		label: 'Lemon character moving in excitement',
		amount: '10.00',
		currency: 'USD',
	},
	{
		value: 'energetic_lemon_and_baby_lemon_maracas',
		label: 'Lemon character doing a victory dance with maracas in his hands',
		amount: '10.00',
		currency: 'USD',
	},
	{
		value: 'energetic_lemon_and_baby_lemon_grateful',
		label: 'Lemon character holding his hands with gratitude on his face',
		amount: '10.00',
		currency: 'USD',
	},
	{
		value: 'energetic_lemon_and_baby_lemon_bowing_heart',
		label: 'Lemon character bowing his head while spreading hearts with his arms',
		amount: '20.00',
		currency: 'USD',
	},
	{
		value: 'energetic_lemon_and_baby_lemon_jump_hug',
		label: "Baby Lemon jumping in our lemon character's arms to hug him",
		amount: '20.00',
		currency: 'USD',
	},
	{
		value: 'energetic_lemon_and_baby_lemon_twirl_hug',
		label: 'Lemon character and Baby Lemon twirling around in the air, hugging',
		amount: '50.00',
		currency: 'USD',
	},
	{
		value: 'energetic_lemon_and_baby_lemon_fireworks',
		label: 'Lemon character and Baby Lemon jumping in the air with fireworks behind them',
		amount: '50.00',
		currency: 'USD',
	},
	{
		value: 'youtube_object_thumbs_up_red',
		label: 'A thumbs up',
		amount: '1.99',
		currency: 'USD',
	},
	{
		value: 'youtube_object_on_set',
		label: 'Director\'s chair with the words "ON SET"',
		amount: '1.99',
		currency: 'USD',
	},
	{
		value: 'youtube_object_vlog',
		label: 'Cursive red lettering spelling out "vlog"',
		amount: '1.99',
		currency: 'USD',
	},
	{
		value: 'youtube_object_thanks',
		label: '"Thanks!" written on top of a purple heart',
		amount: '1.99',
		currency: 'USD',
	},
	{
		value: 'youtube_object_unboxing',
		label: 'An opened cardboard box with the word "Unboxing"',
		amount: '1.99',
		currency: 'USD',
	},
	{
		value: 'youtube_object_sneak_peek',
		label: 'An open eye with the words "SNEAK PEEK!"',
		amount: '1.99',
		currency: 'USD',
	},
	{
		value: 'youtube_object_arrow_here',
		label: 'A red down arrow with vertical words "HERE"',
		amount: '1.99',
		currency: 'USD',
	},
	{
		value: 'youtube_object_tired',
		label: 'A coffee cup with the words "TIRED"',
		amount: '1.99',
		currency: 'USD',
	},
	{
		value: 'youtube_object_spoiler_alert',
		label: 'A beacon light with words "SPOILER ALERT"',
		amount: '1.99',
		currency: 'USD',
	},
	{
		value: 'youtube_object_wait_for_it',
		label: '"Wait for it..." words with a clock as the "a"',
		amount: '1.99',
		currency: 'USD',
	},
	{
		value: 'youtube_object_behind_the_scenes',
		label: 'A rainbow clapperboard with the words "BEHIND the SCENES"',
		amount: '1.99',
		currency: 'USD',
	},
	{
		value: 'youtube_object_mood',
		label: '"mood" written with smiley faces as the "oo"',
		amount: '1.99',
		currency: 'USD',
	},
	{
		value: 'youtube_object_yum',
		label: 'Cursive teal lettering spelling out "Yum!"',
		amount: '1.99',
		currency: 'USD',
	},
	{
		value: 'youtube_object_vibes',
		label: '"vibes" surrounded with little purple stars',
		amount: '1.99',
		currency: 'USD',
	},
	{
		value: 'youtube_object_point_up',
		label: 'A red hand pointing up',
		amount: '1.99',
		currency: 'USD',
	},
	{
		value: 'youtube_object_heart',
		label: 'A red heart',
		amount: '1.99',
		currency: 'USD',
	},
	{
		value: 'youtube_object_coming_soon',
		label: '"COMING SOON" surrounded by yellow stars',
		amount: '1.99',
		currency: 'USD',
	},
	{
		value: 'youtube_object_new',
		label: '"NEW" lettering in red, orange, and yellow',
		amount: '1.99',
		currency: 'USD',
	},
	{
		value: 'youtube_object_game_over',
		label: '"GAME OVER" written in a pixellated way',
		amount: '1.99',
		currency: 'USD',
	},
	{
		value: 'youtube_object_work',
		label: 'A laptop computer with "WORK" on the screen',
		amount: '1.99',
		currency: 'USD',
	},
	{
		value: 'youtube_object_microphone',
		label: 'A microphone',
		amount: '1.99',
		currency: 'USD',
	},
	{
		value: 'youtube_object_luggage',
		label: 'An orange suitcase with travel stickers',
		amount: '1.99',
		currency: 'USD',
	},
	{
		value: 'grab_bag_1_unicorn',
		label: 'A white unicorn with rainbow hair',
		amount: '1.49',
		currency: 'USD',
	},
	{
		value: 'grab_bag_1_peach',
		label: 'A peach',
		amount: '1.49',
		currency: 'USD',
	},
	{
		value: 'grab_bag_1_salt_shaker',
		label: 'A salt shaker',
		amount: '1.49',
		currency: 'USD',
	},
	{
		value: 'grab_bag_1_thumbs_down',
		label: 'A blue thumbs down with "NOPE" written on it',
		amount: '1.49',
		currency: 'USD',
	},
	{
		value: 'grab_bag_1_rainbow',
		label: 'A rainbow',
		amount: '1.49',
		currency: 'USD',
	},
	{
		value: 'grab_bag_1_hotdog',
		label: 'A hotdog with ketchup',
		amount: '1.49',
		currency: 'USD',
	},
	{
		value: 'grab_bag_1_cat_v2',
		label: 'A purple cat',
		amount: '1.49',
		currency: 'USD',
	},
	{
		value: 'grab_bag_1_rose',
		label: 'A red rose',
		amount: '1.49',
		currency: 'USD',
	},
	{
		value: 'grab_bag_1_banana',
		label: 'A banana',
		amount: '1.49',
		currency: 'USD',
	},
	{
		value: 'grab_bag_1_banana_peel',
		label: 'A banana peel',
		amount: '1.49',
		currency: 'USD',
	},
	{
		value: 'grab_bag_1_mustache_v2',
		label: 'A purple mustache',
		amount: '1.49',
		currency: 'USD',
	},
	{
		value: 'grab_bag_1_dog',
		label: 'A yellow dog',
		amount: '1.49',
		currency: 'USD',
	},
	{
		value: 'grab_bag_1_pie',
		label: 'A slice of cherry pie',
		amount: '1.49',
		currency: 'USD',
	},
	{
		value: 'grab_bag_1_cake_v2',
		label: 'A slice of pink birthday cake with purple icing and a candle',
		amount: '1.49',
		currency: 'USD',
	},
	{
		value: 'grab_bag_1_coin_v2',
		label: 'A coin with a star',
		amount: '1.49',
		currency: 'USD',
	},
	{
		value: 'grab_bag_1_diamond_v2',
		label: 'A sparkling diamond',
		amount: '1.49',
		currency: 'USD',
	},
	{
		value: 'grab_bag_1_ice_cream',
		label: 'A pink ice cream cone',
		amount: '1.49',
		currency: 'USD',
	},
	{
		value: 'grab_bag_1_popcorn',
		label: 'A red box of popcorn',
		amount: '1.49',
		currency: 'USD',
	},
	{
		value: 'grab_bag_1_hamburger',
		label: 'A hamburger',
		amount: '1.49',
		currency: 'USD',
	},
	{
		value: 'grab_bag_1_dumbbell_v2',
		label: 'A dumbbell',
		amount: '1.49',
		currency: 'USD',
	},
	{
		value: 'grab_bag_1_hearts',
		label: '3 red hearts of differing sizes',
		amount: '1.49',
		currency: 'USD',
	},
	{
		value: 'grab_bag_1_umbrella',
		label: 'A pink umbrella on a beach',
		amount: '1.49',
		currency: 'USD',
	},
	{
		value: 'grab_bag_1_city',
		label: 'A cityscape',
		amount: '1.49',
		currency: 'USD',
	},
	{
		value: 'grab_bag_1_trees',
		label: '3 evergreen trees',
		amount: '1.49',
		currency: 'USD',
	},
	{
		value: 'emoji_beaming_face',
		label: 'Beaming face with smiling eyes',
		amount: '0.99',
		currency: 'USD',
	},
	{
		value: 'emoji_winking_face',
		label: 'Winking face',
		amount: '0.99',
		currency: 'USD',
	},
	{
		value: 'emoji_sunglasses_face',
		label: 'Smiling face with sunglasses',
		amount: '0.99',
		currency: 'USD',
	},
	{
		value: 'emoji_heart_face',
		label: 'Smiling face with heart-eyes',
		amount: '0.99',
		currency: 'USD',
	},
	{
		value: 'emoji_money_face',
		label: 'Money-mouth face',
		amount: '0.99',
		currency: 'USD',
	},
	{
		value: 'emoji_poop_face',
		label: 'A pile of poop with a face',
		amount: '0.99',
		currency: 'USD',
	},
	{
		value: 'emoji_one_hundred',
		label: '100 underlined twice',
		amount: '0.99',
		currency: 'USD',
	},
	{
		value: 'emoji_thinking_face',
		label: 'Thinking face',
		amount: '0.99',
		currency: 'USD',
	},
	{
		value: 'emoji_expressionless_face',
		label: 'Expressionless face',
		amount: '0.99',
		currency: 'USD',
	},
	{
		value: 'emoji_mouthless_face',
		label: 'Face without mouth',
		amount: '0.99',
		currency: 'USD',
	},
	{
		value: 'emoji_anxious_face',
		label: 'Anxious Face With Sweat',
		amount: '0.99',
		currency: 'USD',
	},
	{
		value: 'emoji_sleeping_face',
		label: 'Sleeping face',
		amount: '0.99',
		currency: 'USD',
	},
	{
		value: 'emoji_astonished_face',
		label: 'Astonished face',
		amount: '0.99',
		currency: 'USD',
	},
	{
		value: 'emoji_drooling_face',
		label: 'Drooling face',
		amount: '0.99',
		currency: 'USD',
	},
	{
		value: 'emoji_vomiting_face',
		label: 'Face vomiting',
		amount: '0.99',
		currency: 'USD',
	},
	{
		value: 'emoji_screaming_face',
		label: 'Face screaming in fear',
		amount: '0.99',
		currency: 'USD',
	},
	{
		value: 'emoji_steamed_face',
		label: 'Face with steam from nose',
		amount: '0.99',
		currency: 'USD',
	},
	{
		value: 'emoji_angry_face',
		label: 'Angry face',
		amount: '0.99',
		currency: 'USD',
	},
	{
		value: 'emoji_devil_face',
		label: 'Smiling face with horns',
		amount: '0.99',
		currency: 'USD',
	},
	{
		value: 'emoji_angel_face',
		label: 'Smiling face with halo',
		amount: '0.99',
		currency: 'USD',
	},
	{
		value: 'emoji_sad_face',
		label: 'Frowning face',
		amount: '0.99',
		currency: 'USD',
	},
	{
		value: 'emoji_crying_face',
		label: 'Loudly crying face',
		amount: '0.99',
		currency: 'USD',
	},
	{
		value: 'emoji_dizzy_face',
		label: 'Dizzy face',
		amount: '0.99',
		currency: 'USD',
	},
	{
		value: 'emoji_upside_down_face',
		label: 'Upside down face',
		amount: '0.99',
		currency: 'USD',
	},
	{
		value: 'masher_gg_thumbs_up',
		label: 'Video game controller gives a thumbs up and says "GG"',
		amount: '2.00',
		currency: 'USD',
	},
	{
		value: 'masher_glhf',
		label: "Video game controller spins around as the word 'GLHF' appears behind",
		amount: '2.00',
		currency: 'USD',
	},
	{
		value: 'masher_jumping',
		label: 'Video game controller jumps up and down excitedly',
		amount: '5.00',
		currency: 'USD',
	},
	{
		value: 'masher_broken_arm',
		label: 'Video game controller hobbles along unhappily with a broken arm',
		amount: '5.00',
		currency: 'USD',
	},
	{
		value: 'masher_noob',
		label: "Baby video game controller sits in a diaper under the word 'Noob'",
		amount: '5.00',
		currency: 'USD',
	},
	{
		value: 'masher_try_again',
		label: "Video game controller looks forlorn in between the words 'Try again'",
		amount: '5.00',
		currency: 'USD',
	},
	{
		value: 'masher_critical_hit',
		label: "Video game controller poses triumphantly in between the words 'Critical Hit!'",
		amount: '5.00',
		currency: 'USD',
	},
	{
		value: 'masher_level_up',
		label: "Video game controller evolves into a muscled version of itself under the word 'LVL+'",
		amount: '10.00',
		currency: 'USD',
	},
	{
		value: 'masher_sunglasses',
		label: "Sunglasses perpetually fall onto video game controller's proud face",
		amount: '10.00',
		currency: 'USD',
	},
	{
		value: 'masher_woot',
		label: "Video game controller dances goofily under the word 'Woot'",
		amount: '20.00',
		currency: 'USD',
	},
	{
		value: 'masher_rage_quit',
		label: "Video game controller throws a facedown tantrum in between the words 'Rage Quit'",
		amount: '20.00',
		currency: 'USD',
	},
	{
		value: 'masher_super_effective',
		label: "Video game controller punches and kicks in between the words 'Super Effective'",
		amount: '50.00',
		currency: 'USD',
	},
];
